### ISSUE TITLE
Unable to provision Ubuntu 18.04

### ISSUE THREAD

**Issue by igolman** [chef-cookbooks/docker#1005]
### Cookbook version
4.3.0

### Chef-client version
12.19.36

### Platform Details
Ubuntu 18.04 

### Scenario:
Server provision: install docker-ce package.

### Steps to Reproduce:
```
  docker_installation_package 'default' do
    action :create
  end

```

### Expected Result:
Docker package should be installed

### Actual Result:
chef-client aborts, since package wasn't found.

In docker/libraries/docker_installation_package.rb:

**Minor problem:** this package version doesn't exist:
```
def default_docker_version
      '18.03.0'
end
```

**Major problem:** this link is not valid, since Docker repo has only 18.03.1\~ce\~3\-0\~ubuntu version of the package. 
```
 return "#{v}#{edition}-0~ubuntu#{codename}" if node['platform'] == 'ubuntu'
```

**Comment by zicklag** [comment]
I have the same issue.

**Comment by smcavallo** [comment]
should be fixed as part of https://github.com/chef-cookbooks/docker/pull/1006
first bionic supported docker-ce package is '18.03.1'

**Comment by tdg5** [comment]
I can confirm that cookbook v4.4.0 fixed the issue for me.

**Comment by stantonk** [comment]
Does this mean 18.04 is officially supported in this cookbook now? README still only says 14.04/16.04
