### ISSUE TITLE
Recipe Compile Error

### ISSUE THREAD

**Issue by kishan0001** [chef-cookbooks/docker#1009]
###docker cookbook 4.3.0

### Scenario:

I have bootstrapped one node to the chef management console.
I have uploaded this docker 4.3.0 docker cookbook to the chef management console.
I can see the cookbook in the policy tab of chef management console.
But while i am trying to edit run list after click on the node, the docker cookbook is not visible there.
I tried to execute the cookbook. But i am facing an error. 

### Expected Result:

this should install docker in the node.

### Actual Result:

-----> Existing Chef installation detected
Starting the first Chef Client run...
Starting Chef Client, version 14.3.37
resolving cookbooks for run list: ["docker"]
Synchronizing Cookbooks:
- docker (4.3.0)
Installing Cookbook Gems:
Compiling Cookbooks...
 
================================================================================
10.142.0.5 Recipe Compile Error
10.142.0.5 ================================================================================

 Chef::Exceptions::RecipeNotFound
 --------------------------------
 could not find recipe default for cookbook docker
 
System Info:
 ------------
 chef_version=14.3.37
 platform=ubuntu
 platform_version=14.04
 ruby=ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
 program_name=/usr/bin/chef-client
 executable=/opt/chef/bin/chef-client

 Running handlers:
 [2018-07-16T10:16:00+00:00] ERROR: Running exception handlers
Running handlers complete
[2018-07-16T10:16:00+00:00] ERROR: Exception handlers complete
10.142.0.5 Chef Client failed. 0 resources updated in 03 seconds
[2018-07-16T10:16:00+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
 [2018-07-16T10:16:00+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
 [2018-07-16T10:16:00+00:00] FATAL: Chef::Exceptions::RecipeNotFound: could not find recipe default for cookbook docker

**Comment by dheerajd-msys** [comment]
Hi @kishan0001 We have been working on latest cookbook but didn't faced any such errors and able to execute the cookbook on node.

Please check with latest cookbook/chef and confirm.

**Comment by dheerajd-msys** [comment]
@kishan0001 Please follow https://github.com/chef-cookbooks/docker#usage. You need to create sample cookbook and add `depends 'docker'` in your cookbook `metadata.rb` in order to use the cookbook.

Closing it for now. Please let us know if there is anything.
