### ISSUE TITLE
How to increase the share memory size for a docker image

### ISSUE THREAD

**Issue by dinosavings** [chef-cookbooks/docker#1030]
### Cookbook version
v4.6.2 

### Chef-client version
12.5.1

### Platform Details
Centos 6.5

### Scenario:

I am using this cookbook to deploy the selenium test grid and it requires the shared memory of the image to be at a minimum of 2g (see https://github.com/SeleniumHQ/docker-selenium#running-the-images).

I wish to change the shared memory size of the image. Basically add "--shm-size=2g" to the docker run.

### Steps to Reproduce:
None. It is a general question and not a bug.

### Expected Result:
na

### Actual Result:
na

**Comment by dheerajd-msys** [comment]
@dinosavings Closing as it's fixed in #1060 

Please let us know if there is anything.
