### ISSUE TITLE
log-opt should not be quotted

### ISSUE THREAD

**Issue by ttr** [chef-cookbooks/docker#1056]
### Cookbook version
4.9.0

### Chef-client version
14.9.13

### Platform Details
Devuan ascii (debian Jessie no sysyemD)
docker version: 18.06.1~ce~3-0~debian

### Scenario:
Specifying multiple log options will cause them to be quoted (I think #936 introduced this).
This will, on sysvinit system, update init script to something like:
`DOCKER_OPTS="--log-driver=syslog --log-opt 'syslog-facility=local5' --log-opt 'tag={{.ImageName}}/{{.Name}}' "`
This is causing error on start:
> Error starting daemon: failed to set log opts: unknown log opt ''tag' for syslog log driver

Two solutions to address this (IMO):
1) remove quotes - parameters should not have white spaces (and if user wants them they should add them in proper place)
2) move options to docker.json as is now advised by docker standards (does not apply when overriding options on container basis)

Also - quotes where introduced into cookbook 1y ago so I'm gonna see if updating docker daemon will help in this

### Steps to Reproduce:
* use systemv (not sure if upstart / systemD is affected)
* add multiple log_opt as dict into docker_service
run chef-client and then try to (re-)start docker service using init script

### Expected Result:
no quotes around options and service to start

### Actual Result:
service refuse to start as quote is interpreted as part of option

**Comment by kapilchouhan99** [comment]
Hi @ttr, In order to Specify multiple log options, we need to pass `log_opts` in array format like this:
```
docker_service 'default' do
  log_opts ['mode=non-blocking', 'max-buffer-size=4m']
  action [:create, :start]
end
```
Could you please check it on the latest version of the docker cookbook?
I have verified, its working fine on the latest version of the docker cookbook

**Comment by kapilchouhan99** [comment]
It's working on the latest version of the Docker cookbook, So closing this issue.

If you are still facing this issue, you can reopen it.

Thanks!
