### ISSUE TITLE
Upgrading docker version

### ISSUE THREAD

**Issue by codereflection** [chef-cookbooks/docker#1065]
### Cookbook version
4.9.2

### Chef-client version
14.3

### Platform Details
Ubuntu 16.04

### Scenario:
Attempting to upgrade previously installed version of docker does not work.

### Steps to Reproduce:
Converge with `docker_installation_package` resource with `version` set to `17.12.1` and then converge again with `version` set to `18.09.2`.

### Expected Result:
Expected the 1st converge to install docker 17.12.1
Manually update version property
Expected the 2nd converge to upgrade docker to 18.09.2

### Actual Result:
The upgrade of docker does not happen.  The `package` resource called by `docker_installation_package` is marked up-to-date and skipped.

I believe this is happening because `docker_installation_package`'s use of the `package` resource is only setting the `action` to `:install` and not `:upgrade`.  Is there another way to go about upgrading the docker engine with this cookbook?

**Comment by mlcooper** [comment]
Yes, have a look at this resource https://github.com/chef-cookbooks/docker#docker_installation_package, which permits you to specify the version you want.

**Comment by codereflection** [comment]
@mlcooper right, as I mentioned, the `version` property is what I'm setting. Yet if the engine is already installed and that version property is set to a higher version in the resource, the resource does not upgrade the engine at all.

**Comment by sean-nixon** [comment]
I'm also seeing issues upgrading docker even when specifying the version on resource. I converged with '18.09.7', then again with '19.03.2' and get this warning:

```
yum_package[docker-ce] action install[2019-09-09T15:34:36+00:00] WARN: yum_package[docker-ce] docker-ce has installed version 3:18.09.7-3.el7.x86_64, which is newer than available version 19.03.2-3.el7. Skipping...)
```

Chef-client: 14.13.11
Cookbook version:  4.9.3

**Comment by mvh** [comment]
The original issue was with Ubuntu, a RHEL fix shouldn't close this ticket.

**Comment by kapilchouhan99** [comment]
@mvh Could you please check it on the latest version?
because it fixed on the latest version.

**Comment by dheerajd-msys** [comment]
@mvh Please check ^

**Comment by kapilchouhan99** [comment]
It's working on the latest version of the Docker cookbook, So closing this issue.

If you are still facing this issue, you can reopen it.

Thanks!
