### ISSUE TITLE
docker_image - handling movement of the 'latest' tag in an image repository

### ISSUE THREAD

**Issue by mlcooper** [chef-cookbooks/docker#1073]
### Cookbook version
`4.9.2`

### Chef-client version
`Chef: 14.12.9`

### Platform Details
`CentOS Linux release 7.6.1810 (Core)`

### Scenario:
I have a `docker_image` resource, as shown below, and what I'm not sure I understand is if this resource will recognize that the `latest` tag has been moved by the maintainer of  `quay.io/newrelic/synthetics-minion` and that it now needs to download the new image that the `latest` tag is referencing.  

Based on what I am seeing in the code of this cookbook, [here](https://github.com/chef-cookbooks/docker/blob/cf6b6fa5217f863bdfc26749a98048e116657ea2/libraries/docker_image.rb#L135-L137), I do not think it will.  It looks like it is only considering the name of the tag, not if the image ID has changed.
```
docker_image 'newrelic-minion' do
  tag 'latest'
  repo 'quay.io/newrelic/synthetics-minion'
  action :pull_if_missing
end
```
### Steps to Reproduce:
Use the code example from the Scenario section above.
The code will download a docker image.
Move the `latest` tag in the repo to a newer image.
Run `chef-client` again and observe that even though the `latest` tag is pointing to a newer image, the newer image is not downloaded.

### Expected Result:
Can you confirm if the `latest` tag has been moved in a repo to a new image, if the code I pasted above should download it automatically on the next chef run?

### Actual Result:
It does not appear that the code example I've provided downloads the newer image when the `latest` tag is moved in a repo.

**Comment by antima-gupta** [comment]
@mlcooper if this resource will recognize that the latest tag has been moved by the maintainer of quay.io/newrelic/synthetics-minion and that it now needs to download the new image that the latest tag is referencing
In this case you should use pull action instead of pull_if_missing.  pull action identify the new image with latest tag if the image ID has changed and download it automatically on the next chef run.

**Comment by dheerajd-msys** [comment]
@mlcooper Please check ^^ and confirm.

**Comment by antima-gupta** [comment]
@mlcooper I'm closing this ticket based on [comment]( https://github.com/chef-cookbooks/docker/issues/1073#issuecomment-641790141).
