### ISSUE TITLE
docker_container resource no longer idempotent with chef-client > 15.4

### ISSUE THREAD

**Issue by smcavallo** [chef-cookbooks/docker#1083]
### Cookbook version
4.10.0 and below

### Chef-client version
15.4 and greater

### Platform Details
n/a

### Scenario:
See - https://github.com/chef/chef/blob/master/RELEASE_NOTES.md#converge_if_changed-improvements 
This has a major impact to the docker_container resource which will result in the containers being redeployed upon each converge.
```
- update your_container
    -   set ipc_mode    to "" (was "shareable")
    -   set memory_swap to 0 (was -1)
```
https://github.com/chef-cookbooks/docker/blob/master/libraries/docker_container.rb#L32
`property :ipc_mode, String, default: ''`
https://github.com/chef-cookbooks/docker/blob/master/libraries/docker_container.rb (edited) 
`property :memory_swap, [String, Integer], coerce: proc { |v| coerce_to_bytes(v) }, default: 0`

it's now taking into consideration the default values and restarting the containers.
chef < 15.4 return ipc_mode shareable and memory_swap -1 but do not converge/restart.

this cookbook will require investigation/fixes into default value handling.

### Steps to Reproduce:
run the docker_container resource with chef-client > 15.4

### Expected Result:
converge_if_changed says there are no changes and the container does not restart

### Actual Result:
converge_if_changed says there ARE changes (default values) and the container restarts upon every converge

**Comment by skipperza** [comment]
quick workaround would be to implement a not_if guard, but I'm also getting this error on chef-client 15.5.9

For those who don't know, the not_if guard would check using grep if the container is running, and skip the :run action.

Something like this:
```
docker_container 'nexus3' do
  repo 'sonatype/nexus3'
  tag node['nexus']['version']
  port '8081:8081'
  host_name 'nexus'
  volumes [ '/opt/app/nexus:/nexus-data' ]
  env ['INSTALL4J_ADD_VM_PARAMS=-Xms2g -Xmx6g -XX:MaxDirectMemorySize=3g']
  action :run
  not_if 'docker ps | grep nexus3'
end
```

**Comment by duncaan** [comment]
This issue should not be closed - I still have chef-client restarting containers during every converge:
```
    - stopping container
    - deleting container
    - update container
    -   set memory_swap to 0 (was -1)
    -   set working_dir to "" (was "/usr/local/tomcat")
    - starting container
```

**Comment by tas50** [comment]
@duncaan We're going to work the workin_dir issue in #1092
