### ISSUE TITLE
No candidate version available for docker-ce on ubuntu 19.10

### ISSUE THREAD

**Issue by jlosito** [chef-cookbooks/docker#1084]
### Cookbook version
4.10.0

### Chef-client version
14.8.12

### Platform Details
Ubuntu 19.10

### Scenario:
Install docker-ce on Ubuntu 19.10.

For what it's worth, it doesn't look like there's a eoan repo yet. https://download.docker.com/linux/ubuntu/dists/

### Steps to Reproduce:
Run a `docker_installation_package 'default'` on an Ubuntu 19.10 instance.

### Expected Result:
Install docker-ce

### Actual Result:
https://gist.github.com/jlosito/354a3b08682bfa65546bd80ddd1e52a6

**Comment by kapilchouhan99** [comment]
Hi @jlosito, Could you please check it on the latest version of the docker cookbook?
I have verified, its working fine on the latest version of the docker cookbook with chef-client 14, 15 and 16.

**Comment by kapilchouhan99** [comment]
It's working on the latest version of the Docker cookbook, So closing this issue. Thanks!
