### ISSUE TITLE
docker_exec not working 

### ISSUE THREAD

**Issue by kmf** [chef-cookbooks/docker#1101]
This code isn't working.

```
docker_image 'postgres' do
    tag '10'
    action :pull
 end

docker_container 'mydb' do
    image 'postgres'
    tag '10'
    env ["POSTGRES_PASSWORD=jellyfish"]
end

docker_exec 'create mydb database' do
  container 'mydb'
  command ["createdb", "-U", "postgres", "-l", "C", "-E", "UTF8", "-T", "template0", "mydb"]
end
```

When this running this I get this 
```
* docker_exec[create mydb database] action run[2020-04-21T06:18:31+00:00] INFO: Processing docker_exec[create mydb database] action run (docker_jira::db line 12)
- executing ["createdb", "-U", "postgres", "-l", "C", "-E", "UTF8", "-T", "template0", "mydb"] on mydb
```

doesn't create the database

![image](https://user-images.githubusercontent.com/78700/79833512-c8384a80-83ab-11ea-838d-af7c79f28f5e.png)

This works `docker exec -it mydb createdb -U postgres -l C -E UTF8 -T template0 mydb`

![image](https://user-images.githubusercontent.com/78700/79833473-b656a780-83ab-11ea-8b62-6d51eb40d940.png)

**Comment by antima-gupta** [comment]
Hi @kmf
We've tried with latest docker cookbook on a node with same recipe as above but included `docker_service` resource as well. This resulted into `mydb` created.

Recipe we used :

```
docker_service 'default' do
action [:create, :start]
end

docker_image 'postgres' do
tag '10'
action :pull
end

docker_container 'mydb' do
image 'postgres'
tag '10'
env ["POSTGRES_PASSWORD=jellyfish"]
end

docker_exec 'create mydb database' do
container 'mydb'
command ["createdb", "-U", "postgres", "-l", "C", "-E", "UTF8", "-T", "template0", "mydb"]
end
```
Please check if this works for you?

**Comment by dheerajd-msys** [comment]
@kmf Could you please check and confirm ^ ?

**Comment by kmf** [comment]
Tested your suggestion and it's working. 
Did find another work around.
