### ISSUE TITLE
"no subsystem for mount" Error

### ISSUE THREAD

**Issue by sidharthaggarwal** [chef-cookbooks/docker#1108]
Hello Team,

I am getting below error while trying to start docker 

Error response from daemon: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:359: container init caused \\\"rootfs_linux.go:53: mounting \\\\\\\"cgroup\\\\\\\" to rootfs \\\\\\\"/var/lib/docker/aufs/mnt/5c5ba2dd2eb23394e9040d56e3e48768ecd74fc5cf1fea90cff81859787c96b0\\\\\\\" at \\\\\\\"/sys/fs/cgroup\\\\\\\" caused \\\\\\\"no subsystem for mount\\\\\\\"\\\"\"\n"

OS - VERSION="18.04.4 LTS (Bionic Beaver)"
Docker Version - Docker version 1.12.3, build 6b644ec

Can someone please help here?

**Comment by chenhao424055** [comment]
----You try to configure the go locale

**Comment by sidharthaggarwal** [comment]
@chenhao424055  Can you please explain more and how can i resolve this ?

Also my kernal version - 4.15.0-1065-aws
systemed version - systemd 237
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid

**Comment by chenhao424055** [comment]
Oh, I see

**Comment by dheerajd-msys** [comment]
Hi @sidharthaggarwal you can raise your question in docker forum https://forums.docker.com/.
This repo is mostly related to cookbook related issues.

Closing this issue
