### ISSUE TITLE
Migrate Repository to chef-cookbooks

### ISSUE THREAD

**Issue by bflad** [chef-cookbooks/docker#524]
Per @someara to enable fancy Chef integration testing!

Unless I hear any major complaints or get asked to do it sooner, this repository will be transferred away from bflad/chef-docker midday on Monday, October 19th.

**Comment by chasebolt** [comment]
:+1:

**Comment by bflad** [comment]
@someara please delete (and not just rename) your fork of this repository then I can transfer it over to you

**Comment by someara** [comment]
Deleted.

**Comment by bflad** [comment]
> Repository transfer to someara requested

:+1:

**Comment by someara** [comment]
successfully moved to someara...

I just realized I need to sort out the CLA issue before moving it over to chef-cookbooks and wiring up to Delivery.

stay tuned

-s

**Comment by someara** [comment]
Marked as blocked until we can hammer out some process things on Chef side around Delivery and Github integration.

**Comment by st-isidore-de-seville** [comment]
As @bflad referred to it, is this "fancy Chef integration testing!" available to everybody who authors cookbooks or is it an internal Chef pipeline?

**Comment by someara** [comment]
The system referred to is our CD product Delivery, which isn't quite GA
yet. The idea is to make it available to everyone eventually... it's not
quite ready today.

To start, you'll be able to see status, but viewing details will be
internal for moment.
We'll mirror the CI work in Travis as much as possible until that's fixed.

You can see how it'll look in the chef-web-docs repo -
https://github.com/chef/chef-web-docs/pull/702

The larger point is the pipeline around the CI... that is, Delivery will
gate the master branch so less regressions sneak in.

I'll also have to break my bad habit of doing yolo commits to master =)

-s

**Comment by st-isidore-de-seville** [comment]
@someara awesome.  I look forward to seeing it soon!

**Comment by someara** [comment]
Case in point... a proper pipeline would have prevented Travis from turning
red just now. (I forgot to run foodcritic)

https://travis-ci.org/someara/chef-docker/builds/87237587

-s

**Comment by st-isidore-de-seville** [comment]
Understood @someara :smile:

**Comment by someara** [comment]
Finally got this past Legal =)

-s
