### ISSUE TITLE
docker_image should have action :load

### ISSUE THREAD

**Issue by kkeane** [chef-cookbooks/docker#539]
The docker_image resource currently supports the :import action, but not the :load action.

These two are different in a subtle way: import will only import the file system itself, while load will import the complete docker image (volumes, entrypoint, cmd, expose, tags).

Or said differently: import is the counterpart to export (on a docker container), while load is the counterpart to save on a docker image.

**Comment by chasebolt** [comment]
Can you please post a link to the documentation on this? I'll take a look at implementing it.

**Comment by kkeane** [comment]
The best documentation for this is probably in the man pages for docker-load and docker-import, respectively. A couple more links:

https://github.com/docker/docker/issues/8334
https://docs.docker.com/reference/commandline/import/
https://docs.docker.com/reference/commandline/load/

Hope that helps!

**Comment by cbalducci** [comment]
I've just submitted a PR (https://github.com/swipely/docker-api/pull/345) which provides *docker load* support in docker-api ruby library. I'm willing to implement it in this cookbook as soon as it gets merged

**Comment by someara** [comment]
excellent. I have a PR on that repo too... should be a useful release =)

**Comment by cbalducci** [comment]
done, it was only 6 lines of code :smile: I'll wait for the docker-api's PR to get merged and then submit a PR here

**Comment by cbalducci** [comment]
Since my previous docker-api PR got #stuck (my fault), i've cleaned up and submitted another one (https://github.com/swipely/docker-api/pull/380)

**Comment by mdkent** [comment]
Just a heads up for anyone else trying to use this: this was merged and released in docker 2.6.3 but remains broken as the docker-api dep is stuck on 1.26.2. This functionality requires docker-api >= 1.27.

Tried working around it in my wrapper cookbook but was thwarted by [libraries/_autoload.rb](https://github.com/chef-cookbooks/docker/blob/master/libraries/_autoload.rb) which loads its version first when it resolves the dependency at compile time (related #682).

Tried bumping docker-api today to 1.28.0 but r-train is also pinned to 1.26.2.

Ugh!

**Comment by chasebolt** [comment]
fixed in v2.6.8

tests added for `action :load` in this release as well
