### ISSUE TITLE
Check for conflicting properties

### ISSUE THREAD

**Issue by someara** [chef-cookbooks/docker#557]
With Custom Resource, we can use coerce to perform mutual exclusivity checking.

This will let us generate compilation errors up front and avoid half-built clusters when things error on the server side.

For example, specifying both auto-restart and auto-remove makes no sense and should generate an error.

The Docker CLI does a ton of this. 

For example, in run.go -

https://github.com/docker/docker/blob/b664a8825ea20a729f14a49dcc0fc51ca4e01d8b/api/client/run.go#L79-L81

Without this, we will continue to see things silently ignored, or appear as server-side errors.
For example #542

**Comment by jkeiser** [comment]
@someara here's one way to do it with coerce:

```
      property :autoremove, Boolean, coerce: proc { |v| if autoremove && v != 'no') { raise Chef::Exceptions::ValidationError, "" } }
      property :restart_policy, Boolean, coerce: proc { |v| if autoremove && v != 'no') { raise ValidationError, "" } }
```
