### ISSUE TITLE
docker compose

### ISSUE THREAD

**Issue by computerlyrik** [chef-cookbooks/docker#564]
https://docs.docker.com/compose/

I want setup this docker tool using chef.
I think about coding it into this cookbook - what do you think?
Or should i add a cookbook by my own?

How do you think it should be integrated with the current chef-docker-cookbook infrastructure?

**Comment by someara** [comment]
As far as I know, this cookbook lets you do the exact same thing as compose, except you use a Chef recipe instead of the compose.yml.

**Comment by scalp42** [comment]
Correct, there's overlap here.

Also remember (not saying it's a good idea), you could just issue an execute to run `docker-compose up -d` after a git pull for example.

**Comment by someara** [comment]
closing due to inactionability

**Comment by obazoud** [comment]
@computerlyrik see https://github.com/uzyexe/chef-docker-compose
