### ISSUE TITLE
Docker::Error::TimeoutError: read timeout reached while delete/redeploy docker container

### ISSUE THREAD

**Issue by BlindButcher** [chef-cookbooks/docker#567]
My recipe
```
docker_service 'default' do
  version '1.8.2'
  action [:create, :start]
end

docker_image 'quay.io/coreos/etcd' do
  tag 'v2.0.3'
  action :pull
end

docker_container 'etcd' do
  repo 'quay.io/coreos/etcd'
  tag 'v2.0.3'
  env ['ETCD_NAME=etcd0', "ETCD_ADVERTISE_CLIENT_URLS=http://#{node['ipaddress']}:2380, http://#{node['ipaddress']}:4001", "ETCD_INITIAL_CLUSTER=etcd0=http://#{node['ipaddress']}:2380", "ETCD_INITIAL_ADVERTISE_PEER_URLS=http://#{node['ipaddress']}:2380", "ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380", "ETCD_LISTEN_CLIENT_URLS= http://0.0.0.0:2379, http://0.0.0.0:4001", "T=test"]
  publish_all_ports true
  action :redeploy
end
```
Here is an exception
```
Docker::Error::TimeoutError: docker_container[etcd] (try-docker::default line 22) had an error: Docker::Error::TimeoutError: read timeout reached
/tmp/kitchen/cookbooks/docker/files/default/vendor/gems/docker-api-1.22.4/lib/docker/connection.rb:52:in `rescue in request'
/tmp/kitchen/cookbooks/docker/files/default/vendor/gems/docker-api-1.22.4/lib/docker/connection.rb:38:in `request'
/tmp/kitchen/cookbooks/docker/files/default/vendor/gems/docker-api-1.22.4/lib/docker/connection.rb:65:in `block (2 levels) in <class:Connection>'
/tmp/kitchen/cookbooks/docker/files/default/vendor/gems/docker-api-1.22.4/lib/docker/container.rb:190:in `block (2 levels) in <class:Container>'
/tmp/kitchen/cookbooks/docker/libraries/docker_container.rb:258:in `block (3 levels) in <class:DockerContainer>'
/tmp/kitchen/cookbooks/docker/libraries/helpers_base.rb:67:in `call'
/tmp/kitchen/cookbooks/docker/libraries/helpers_base.rb:67:in `with_retries'
/tmp/kitchen/cookbooks/docker/libraries/docker_container.rb:258:in `block (2 levels) in <class:DockerContainer>'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/mixin/why_run.rb:52:in `call'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/mixin/why_run.rb:52:in `add_action'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/provider.rb:175:in `converge_by'
/tmp/kitchen/cookbooks/docker/libraries/docker_container.rb:257:in `block in <class:DockerContainer>'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/provider.rb:362:in `action_stop'
/tmp/kitchen/cookbooks/docker/libraries/docker_container.rb:159:in `call_action'
/tmp/kitchen/cookbooks/docker/libraries/docker_container.rb:315:in `block in <class:DockerContainer>'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/provider.rb:362:in `action_delete'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/provider.rb:144:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource.rb:585:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/runner.rb:49:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/runner.rb:81:in `block (2 levels) in converge'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/runner.rb:81:in `each'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/runner.rb:81:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/runner.rb:80:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/client.rb:653:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/client.rb:648:in `catch'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/client.rb:648:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/client.rb:687:in `converge_and_save'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/client.rb:269:in `run'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application.rb:270:in `block in fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application.rb:258:in `fork'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application.rb:258:in `fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application.rb:224:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application.rb:212:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application/solo.rb:280:in `block in interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application/solo.rb:269:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application/solo.rb:269:in `interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application/solo.rb:247:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application.rb:60:in `run'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/bin/chef-solo:25:in `<top (required)>'
/opt/chef/bin/chef-solo:54:in `load'
/opt/chef/bin/chef-solo:54:in `<main>'[root@default-centos-71 ~]# 
```
I'm using cookbook version 
depends 'docker', '~> 2.2.10' (taken form metadata.rb)

I've switched to [:kill, :run] now and it seems to work as expected - redeploy container only on resource change.

**Comment by someara** [comment]
Can you paste that into a gist?






On Wednesday, Dec 2, 2015 at 6:57 PM, BlindButcher <notifications@github.com>, wrote:

My recipe


docker_service 'default' do
  version '1.8.2'
  action [:create, :start]
end

docker_image 'quay.io/coreos/etcd' do
  tag 'v2.0.3'
  action :pull
end

docker_container 'etcd' do
  repo 'quay.io/coreos/etcd'
  tag 'v2.0.3'
  env ['ETCD_NAME=etcd0', "ETCD_ADVERTISE_CLIENT_URLS=http://#{node['ipaddress']}:2380, http://#{node['ipaddress']}:4001", "ETCD_INITIAL_CLUSTER=etcd0=http://#{node['ipaddress']}:2380", "ETCD_INITIAL_ADVERTISE_PEER_URLS=http://#{node['ipaddress']}:2380", "ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380", "ETCD_LISTEN_CLIENT_URLS= http://0.0.0.0:2379, http://0.0.0.0:4001", "T=test"]
  publish_all_ports true
  action :redeploy
end


Here is an exception


Docker::Error::TimeoutError: docker_container[etcd] (try-docker::default line 22) had an error: Docker::Error::TimeoutError: read timeout reached
/tmp/kitchen/cookbooks/docker/files/default/vendor/gems/docker-api-1.22.4/lib/docker/connection.rb:52:in `rescue in request'
/tmp/kitchen/cookbooks/docker/files/default/vendor/gems/docker-api-1.22.4/lib/docker/connection.rb:38:in `request'
/tmp/kitchen/cookbooks/docker/files/default/vendor/gems/docker-api-1.22.4/lib/docker/connection.rb:65:in `block (2 levels) in <class:Connection>'
/tmp/kitchen/cookbooks/docker/files/default/vendor/gems/docker-api-1.22.4/lib/docker/container.rb:190:in `block (2 levels) in <class:Container>'
/tmp/kitchen/cookbooks/docker/libraries/docker_container.rb:258:in `block (3 levels) in <class:DockerContainer>'
/tmp/kitchen/cookbooks/docker/libraries/helpers_base.rb:67:in `call'
/tmp/kitchen/cookbooks/docker/libraries/helpers_base.rb:67:in `with_retries'
/tmp/kitchen/cookbooks/docker/libraries/docker_container.rb:258:in `block (2 levels) in <class:DockerContainer>'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/mixin/why_run.rb:52:in `call'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/mixin/why_run.rb:52:in `add_action'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/provider.rb:175:in `converge_by'
/tmp/kitchen/cookbooks/docker/libraries/docker_container.rb:257:in `block in <class:DockerContainer>'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/provider.rb:362:in `action_stop'
/tmp/kitchen/cookbooks/docker/libraries/docker_container.rb:159:in `call_action'
/tmp/kitchen/cookbooks/docker/libraries/docker_container.rb:315:in `block in <class:DockerContainer>'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/provider.rb:362:in `action_delete'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/provider.rb:144:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource.rb:585:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/runner.rb:49:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/runner.rb:81:in `block (2 levels) in converge'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/runner.rb:81:in `each'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/runner.rb:81:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/runner.rb:80:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/client.rb:653:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/client.rb:648:in `catch'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/client.rb:648:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/client.rb:687:in `converge_and_save'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/client.rb:269:in `run'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application.rb:270:in `block in fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application.rb:258:in `fork'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application.rb:258:in `fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application.rb:224:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application.rb:212:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application/solo.rb:280:in `block in interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application/solo.rb:269:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application/solo.rb:269:in `interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application/solo.rb:247:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application.rb:60:in `run'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/bin/chef-solo:25:in `<top (required)>'
/opt/chef/bin/chef-solo:54:in `load'
/opt/chef/bin/chef-solo:54:in `<main>'[root@default-centos-71 ~]# 


I'm using cookbook version 

depends 'docker', '~> 2.2.10' (taken form metadata.rb)


I've switched to [:kill, :run] now and it seems to work as expected - redeploy container only on resource change.

**Comment by BlindButcher** [comment]
https://gist.github.com/BlindButcher/ead60381188fb5556866

**Comment by chasebolt** [comment]
off the top of my head, my guess would be the container doesn't gracefully exit with a kill command. which then the docker_container would eventually hit the docker-api read timeout and fail.

try using this resource block
```ruby
docker_container 'etcd' do
  repo 'quay.io/coreos/etcd'
  tag 'v2.0.3'
  env ['ETCD_NAME=etcd0', "ETCD_ADVERTISE_CLIENT_URLS=http://#{node['ipaddress']}:2380, http://#{node['ipaddress']}:4001", "ETCD_INITIAL_CLUSTER=etcd0=http://#{node['ipaddress']}:2380", "ETCD_INITIAL_ADVERTISE_PEER_URLS=http://#{node['ipaddress']}:2380", "ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380", "ETCD_LISTEN_CLIENT_URLS= http://0.0.0.0:2379, http://0.0.0.0:4001", "T=test"]
  publish_all_ports true
  kill_after 10
  action :redeploy
end
```

**Comment by BlindButcher** [comment]
It is working, but it is only a workaround, is not it?
I mean pure :delete action is not working as expected or I miss something?

**Comment by chasebolt** [comment]
the reason this case happens is we do not want to force kill containers. what if you were running a database in the container and we force killed it by default after 10 seconds? that would end up corrupting the database and be a huge headache.

in a perfect world, containers should be designed so they can be gracefully killed. if this is true the redeploy works fine. but if it is not, then you need to specify a kill_after property and set a value that you find is reasonable to your environment.

here is a good article to read on this topic. https://labs.ctl.io/gracefully-stopping-docker-containers/

**Comment by BlindButcher** [comment]
Thank you, I think I've got an idea. 
So, it is a more an concrete container issue, then recipe issues that is the right point?

**Comment by BlindButcher** [comment]
But in case I use 'docker stop' on this container it is stopped after several seconds without any troubles?
Why recipe can't do the same thing?
I've check container logs
**received terminated signal, shutting down**
seems  like graceful shutdown

**Comment by BlindButcher** [comment]
Sorry, I'm wrong. It is not a graceful shutdown.

**Comment by BlindButcher** [comment]
More like a image issues, which is not handling shutdown in the proper way. Not an issue of recipe.

**Comment by chasebolt** [comment]
Yup exactly right. Some containers are built to handle graceful shutdown, others rely on docker forcibly killing it. Docker defaults to killing it after 10 seconds, we decided to never force kill and make it a user configurable option.

**Comment by chasebolt** [comment]
Yup you got it! Docker stop actually force kills after 10 seconds, just
seems like it is graceful 😕
