### ISSUE TITLE
Resource to get container volume path?

### ISSUE THREAD

**Issue by brianwallace** [chef-cookbooks/docker#569]
Question: is there an existing resource to get the location of a container volume path (i.e. `/var/lib/docker/volumes/xxxxx/_data`)?

I would like to use Chef to write some canned template data into a container volume.  I would normally bind a host directory (path which I would prescribe) to a container volume, but that does not seem to be working with the container I am working with (artifactory).

**Comment by someara** [comment]
Sorry.. there is no native mechanism in the resource for getting this information through the resource...
You can get the path from docker inspect, but I wouldn't recommend manually dropping files into /var/lib/docker like you're trying to do

-s
