### ISSUE TITLE
berks upload fails from Jenkins

### ISSUE THREAD

**Issue by jsmickey** [chef-cookbooks/docker#571]
I have an Ubuntu Jenkins instance handling berkshelf uploads to Chef server.

When trying to upload the Docker cookbook, it fails with the following:
```
00:07:51.842 E, [2015-12-07T17:46:40.055930 #5600] ERROR -- : Cookbook file /var/lib/jenkins/.berkshelf/cookbooks/docker-2.3.2/files/default/vendor/gems/json-1.8.3/tools/server.rb has a ruby syntax error:
00:07:51.843 E, [2015-12-07T17:46:40.056000 #5600] ERROR -- : /var/lib/jenkins/.berkshelf/cookbooks/docker-2.3.2/files/default/vendor/gems/json-1.8.3/tools/server.rb:16: invalid multibyte char (US-ASCII)
00:07:51.843 E, [2015-12-07T17:46:40.056031 #5600] ERROR -- : /var/lib/jenkins/.berkshelf/cookbooks/docker-2.3.2/files/default/vendor/gems/json-1.8.3/tools/server.rb:16: invalid multibyte char (US-ASCII)
00:07:51.843 E, [2015-12-07T17:46:40.056054 #5600] ERROR -- : /var/lib/jenkins/.berkshelf/cookbooks/docker-2.3.2/files/default/vendor/gems/json-1.8.3/tools/server.rb:16: syntax error, unexpected end-of-input, expecting '}'
00:07:51.844 E, [2015-12-07T17:46:40.056074 #5600] ERROR -- :       "foo" => "B��r",
00:07:51.844 E, [2015-12-07T17:46:40.056093 #5600] ERROR -- :                    ^
00:07:51.844 E, [2015-12-07T17:46:40.058086 #5600] ERROR -- : Ridley::Errors::CookbookSyntaxError: Invalid ruby files in cookbook: docker (2.3.2).
00:07:51.844 E, [2015-12-07T17:46:40.058233 #5600] ERROR -- : /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/ridley-4.2.0/lib/ridley/chef/cookbook.rb:198:in `validate'
```

On an Ubuntu desktop, I am able to upload the cookbook with Berkshelf.  The problem appears to be related to the ASCII characters.  This could be a Jenkins problem, but I figured I would start here.  Anybody seen this issue or have ideas for a fix?

**Comment by chasebolt** [comment]
sounds like an utf-8 issue. what version of berkshelf and chef-server are you using?

there is a lot of talk about this issue here, though I just skimmed the topic as it is long: https://github.com/berkshelf/berkshelf-api/issues/112

**Comment by chasebolt** [comment]
definitely not a docker cookbook issue though :smile:

**Comment by jsmickey** [comment]
@chasebolt Agreed, not a docker cookbook issue, thank you for the link

I added this to my Jenkins job and it worked,
export LANG=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8

**Comment by chasebolt** [comment]
np glad you got it worked out
