### ISSUE TITLE
bridge parameter validation is incorrect

### ISSUE THREAD

**Issue by hojerst** [chef-cookbooks/docker#593]
Currently the "bridge" attribute of a docker_service is validated to be an ipv4 or ipv6 address. However, according to https://docs.docker.com/engine/userguide/networking/default_network/build-bridges/ it is a bridge name.

This renders the option unusable at the moment.

**Comment by chasebolt** [comment]
what property on docker_container are you specifically referring to? can you provide your docker_container resource?

**Comment by hojerst** [comment]
I'm refering to the "bridge" attribute of a "docker_service" resource - not a container.
I'd like to run the docker daemon process with "--bridge=bridgename", so docker uses this existing bridge instead of its own "docker0" (which is correct according to dockers documentation referenced in my first comment)

The following resource definition can be used to reproduce the error:

docker_service "default" do
   bridge "br0"
end

=> should install a docker service with "docker daemon --bridge=br0", currently the validation prevents this however.

---

I think https://github.com/chef-cookbooks/docker/blob/master/libraries/docker_service_base.rb#L23 needs to be changed to check for "String" instead of a IP-address. (This validation makes no sense for this option; the ip address is specified by the --bip argument)

**Comment by chasebolt** [comment]
yup you are right :smile: 

feel free to submit a PR with that change

**Comment by someara** [comment]
Fixed merged and released in v2.3.23
