### ISSUE TITLE
cookbook trying to create a service which was already created by package installation

### ISSUE THREAD

**Issue by anojansivarajah-awin** [chef-cookbooks/docker#603]
My code block look like the following
  docker_service 'default' do
    host ['unix:///var/run/docker.sock', 'tcp://0.0.0.0:2375']
    tls_verify false
    action :create
  end 

Kitchen converge gives the following:

 * service[docker] action enable (up to date)
       
            
            ================================================================================
            Error executing action `start` on resource 'service[docker]'
            ================================================================================
            
            Mixlib::ShellOut::ShellCommandFailed
            ------------------------------------
            Expected process to exit with [0], but received '3'
            ---- Begin output of /etc/init.d/docker start ----
            STDOUT: /usr/bin/docker daemon -H unix:///var/run/docker.sock -H tcp://0.0.0.0:2375 --pidfile=/var/run/docker.pid --tlsverify=false >> /var/log/docker.log 2>&1 &
       
            Could not start docker
            STDERR: 
            ---- End output of /etc/init.d/docker start ----
            Ran /etc/init.d/docker start returned 3
            
            Cookbook Trace:
            ---------------
            /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:119:in `compile_and_converge_action'
       
            /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:118:in `instance_eval'
            /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:118:in `compile_and_converge_action'
            /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:119:in `compile_and_converge_action'
            /tmp/kitchen/cache/cookbooks/docker/libraries/docker_service_manager_sysvinit.rb:23:in `block in <class:DockerServiceManagerSysvinit>'
            /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:118:in `instance_eval'
            /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:118:in `compile_and_converge_action'
            /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:119:in `compile_and_converge_action'
            /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:119:in `compile_and_converge_action'
            
            Resource Declaration:
            ---------------------
            # In /tmp/kitchen/cache/cookbooks/docker/libraries/docker_service_manager_sysvinit.rb
            
             53:         service docker_name do
             54:           provider Chef::Provider::Service::Init::Redhat if platform_family?('rhel')
             55:           provider Chef::Provider::Service::Init::Debian if platform_family?('debian')
             56:           supports restart: true, status: true
             57:           action [:enable, :start]
             58:         end
             59:       end
            
            Compiled Resource:
       ------------------
            # Declared in /tmp/kitchen/cache/cookbooks/docker/libraries/docker_service_manager_sysvinit.rb:53:in `create_service'
            
            service("docker") do
              provider Chef::Provider::Service::Debian
              action [:enable, :start]
              supports {:restart=>true, :status=>true}
              retries 0
              retry_delay 2
              default_guard_interpreter :default
              service_name "docker"
              enabled true
              pattern "docker"
              declared_type :service
              cookbook_name "docker-zanox"
            end
            
       
          ================================================================================
          Error executing action `restart` on resource 'docker_service_manager_sysvinit[default]'
          ================================================================================
          
          Mixlib::ShellOut::ShellCommandFailed
          ------------------------------------
          service[docker] (/tmp/kitchen/cache/cookbooks/docker/libraries/docker_service_manager_sysvinit.rb line 53) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '3'
          ---- Begin output of /etc/init.d/docker start ----
          STDOUT: /usr/bin/docker daemon -H unix:///var/run/docker.sock -H tcp://0.0.0.0:2375 --pidfile=/var/run/docker.pid --tlsverify=false >> /var/log/docker.log 2>&1 &
          Starting docker
          Could not start docker
          STDERR: 
          ---- End output of /etc/init.d/docker start ----
          Ran /etc/init.d/docker start returned 3
       
          Cookbook Trace:
          ---------------
          /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:119:in `compile_and_converge_action'
          /tmp/kitchen/cache/cookbooks/docker/libraries/docker_service_manager_sysvinit.rb:24:in `block in <class:DockerServiceManagerSysvinit>'
          /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:118:in `instance_eval'
          /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:118:in `compile_and_converge_action'
          /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:119:in `compile_and_converge_action'
          /tmp/kitchen/cache/cookbooks/docker/libraries/docker_service_manager_sysvinit.rb:23:in `block in <class:DockerServiceManagerSysvinit>'
          /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:118:in `instance_eval'
          /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:118:in `compile_and_converge_action'
          /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:119:in `compile_and_converge_action'
          /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:119:in `compile_and_converge_action'
          
          Resource Declaration:
          ---------------------
       # In /tmp/kitchen/cache/cookbooks/docker/libraries/docker_service.rb
          
           64:           svc = docker_service_manager(name, &block)
           65:         when 'execute'
           66:           svc = docker_service_manager_execute(name, &block)
           67:         when 'sysvinit'
       
           69:         when 'upstart'
           70:           svc = docker_service_manager_upstart(name, &block)
           71:         when 'systemd'
           72:           svc = docker_service_manager_systemd(name, &block)
           73:         end
           74:         copy_properties_to(svc)
           75:         svc
           76:       end
           77:     end
           78: 
           79:     #########
           80:     # Actions
           81:     #########
           82: 
           83:     action :create do
           84:       installation do
           85:         action :create
           86:         notifies :restart, new_resource
           87:       end
           88:     end
           89: 
           90:     action :delete do
           91:       installation do
           92:         action :delete
           93:       end
           94:     end
           95: 
           96:     action :start do
           97:       svc_manager do
           98:         action :start
           99:       end
       
          101: 
          102:     action :stop do
          103:       svc_manager do
          104:         action :stop
          105:       end
          106:     end
          107: 
          108:     action :restart do
          109:       svc_manager do
          110:         action :restart
          111:       end
          112:     end
          113:   end
          114: end
          
          Compiled Resource:
          ------------------
          # Declared in /tmp/kitchen/cache/cookbooks/docker/libraries/docker_service.rb:64:in `svc_manager'
          
          docker_service_manager_sysvinit("default") do
            action [:restart]
            retries 0
            retry_delay 2
            default_guard_interpreter :default
            declared_type :docker_service_manager
            cookbook_name "docker-zanox"
            host ["unix:///var/run/docker.sock", "tcp://0.0.0.0:2375"]
            pidfile "/var/run/docker.pid"
            logfile "/var/log/docker.log"
            ipv4_forward true
            ipv6_forward true
          end
          
       
        ================================================================================
        Error executing action `restart` on resource 'docker_service_manager_sysvinit[default]'
        ================================================================================
        
        Mixlib::ShellOut::ShellCommandFailed
        ------------------------------------
        docker_service_manager_sysvinit[default] (/tmp/kitchen/cache/cookbooks/docker/libraries/docker_service.rb line 64) had an error: Mixlib::ShellOut::ShellCommandFailed: service[docker] (/tmp/kitchen/cache/cookbooks/docker/libraries/docker_service_manager_sysvinit.rb line 53) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '3'
        ---- Begin output of /etc/init.d/docker start ----
        STDOUT: /usr/bin/docker daemon -H unix:///var/run/docker.sock -H tcp://0.0.0.0:2375 --pidfile=/var/run/docker.pid --tlsverify=false >> /var/log/docker.log 2>&1 &
        Starting docker
        Could not start docker
        STDERR: 
        ---- End output of /etc/init.d/docker start ----
        Ran /etc/init.d/docker start returned 3
        
       Cookbook Trace:
        ---------------
        /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:119:in `compile_and_converge_action'
        /tmp/kitchen/cache/cookbooks/docker/libraries/docker_service_manager_sysvinit.rb:24:in `block in <class:DockerServiceManagerSysvinit>'
        /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:118:in `instance_eval'
        /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:118:in `compile_and_converge_action'
        /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:119:in `compile_and_converge_action'
        /tmp/kitchen/cache/cookbooks/docker/libraries/docker_service_manager_sysvinit.rb:23:in `block in <class:DockerServiceManagerSysvinit>'
        /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:118:in `instance_eval'
        /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:118:in `compile_and_converge_action'
        /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:119:in `compile_and_converge_action'
        /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:119:in `compile_and_converge_action'
       
        Resource Declaration:
        ---------------------
        # In /tmp/kitchen/cache/cookbooks/docker/libraries/docker_service.rb
        
         64:           svc = docker_service_manager(name, &block)
         65:         when 'execute'
         66:           svc = docker_service_manager_execute(name, &block)
         67:         when 'sysvinit'
         68:           svc = docker_service_manager_sysvinit(name, &block)
         69:         when 'upstart'
         70:           svc = docker_service_manager_upstart(name, &block)
         71:         when 'systemd'
         72:           svc = docker_service_manager_systemd(name, &block)
         73:         end
         74:         copy_properties_to(svc)
         75:         svc
         76:       end
         77:     end
         78: 
         79:     #########
         80:     # Actions
         81:     #########
         82: 
         83:     action :create do
         84:       installation do
         85:         action :create
         86:         notifies :restart, new_resource
         87:       end
         88:     end
         89: 
         90:     action :delete do
         91:       installation do
       
         93:       end
         94:     end
         95: 
         96:     action :start do
         97:       svc_manager do
         98:         action :start
         99:       end
        100:     end
        101: 
        102:     action :stop do
       
        104:         action :stop
        105:       end
        106:     end
        107: 
        108:     action :restart do
        109:       svc_manager do
        110:         action :restart
        111:       end
        112:     end
        113:   end
        114: end
        
        Compiled Resource:
        ------------------
        # Declared in /tmp/kitchen/cache/cookbooks/docker/libraries/docker_service.rb:64:in `svc_manager'
        
        docker_service_manager_sysvinit("default") do
          action [:restart]
          updated true
          updated_by_last_action true
          retries 0
          retry_delay 2
          default_guard_interpreter :default
          declared_type :docker_service_manager
          cookbook_name "docker-zanox"
          host ["unix:///var/run/docker.sock", "tcp://0.0.0.0:2375"]
          pidfile "/var/run/docker.pid"
          logfile "/var/log/docker.log"
          ipv4_forward true
          ipv6_forward true
        end
       
             
             ================================================================================
             Error executing action `restart` on resource 'docker_service[default]'
             ================================================================================
             
             Mixlib::ShellOut::ShellCommandFailed
             ------------------------------------
             docker_service_manager_sysvinit[default] (/tmp/kitchen/cache/cookbooks/docker/libraries/docker_service.rb line 64) had an error: Mixlib::ShellOut::ShellCommandFailed: docker_service_manager_sysvinit[default] (/tmp/kitchen/cache/cookbooks/docker/libraries/docker_service.rb line 64) had an error: Mixlib::ShellOut::ShellCommandFailed: service[docker] (/tmp/kitchen/cache/cookbooks/docker/libraries/docker_service_manager_sysvinit.rb line 53) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '3'
             ---- Begin output of /etc/init.d/docker start ----
             STDOUT: /usr/bin/docker daemon -H unix:///var/run/docker.sock -H tcp://0.0.0.0:2375 --pidfile=/var/run/docker.pid --tlsverify=false >> /var/log/docker.log 2>&1 &
             Starting docker
             Could not start docker
             STDERR: 
       ---- End output of /etc/init.d/docker start ----
             Ran /etc/init.d/docker start returned 3
             
             Cookbook Trace:
             ---------------
             /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:119:in `compile_and_converge_action'
             /tmp/kitchen/cache/cookbooks/docker/libraries/docker_service_manager_sysvinit.rb:24:in `block in <class:DockerServiceManagerSysvinit>'
             /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:118:in `instance_eval'
             /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:118:in `compile_and_converge_action'
             /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:119:in `compile_and_converge_action'
             /tmp/kitchen/cache/cookbooks/docker/libraries/docker_service_manager_sysvinit.rb:23:in `block in <class:DockerServiceManagerSysvinit>'
             /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:118:in `instance_eval'
             /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:118:in `compile_and_converge_action'
             /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:119:in `compile_and_converge_action'
             /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:119:in `compile_and_converge_action'
       
             Resource Declaration:
             ---------------------
             # In /tmp/kitchen/cache/cookbooks/docker-zanox/recipes/new.rb
             
       23:   docker_service 'default' do
       24:     host ['unix:///var/run/docker.sock', 'tcp://0.0.0.0:2375']
       25:     tls_verify false
       26:     action :create
       27:   end
       28: 
             
             Compiled Resource:
             ------------------
       # Declared in /tmp/kitchen/cache/cookbooks/docker-zanox/recipes/new.rb:23:in `from_file'
             
             docker_service("default") do
        action [:create]
        updated true
        updated_by_last_action true
        retries 0
        retry_delay 2
        default_guard_interpreter :default
        declared_type :docker_service
        cookbook_name "docker-zanox"
        recipe_name "new"
        host ["unix:///var/run/docker.sock", "tcp://0.0.0.0:2375"]
        install_method "auto"
        service_manager "auto"
             end
             
       
           ================================================================================
           Error executing action `create` on resource 'docker_service[default]'
           ================================================================================
           
           Mixlib::ShellOut::ShellCommandFailed
           ------------------------------------
           docker_service[default] (docker-zanox::new line 23) had an error: Mixlib::ShellOut::ShellCommandFailed: docker_service_manager_sysvinit[default] (/tmp/kitchen/cache/cookbooks/docker/libraries/docker_service.rb line 64) had an error: Mixlib::ShellOut::ShellCommandFailed: docker_service_manager_sysvinit[default] (/tmp/kitchen/cache/cookbooks/docker/libraries/docker_service.rb line 64) had an error: Mixlib::ShellOut::ShellCommandFailed: service[docker] (/tmp/kitchen/cache/cookbooks/docker/libraries/docker_service_manager_sysvinit.rb line 53) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '3'
           ---- Begin output of /etc/init.d/docker start ----
           STDOUT: /usr/bin/docker daemon -H unix:///var/run/docker.sock -H tcp://0.0.0.0:2375 --pidfile=/var/run/docker.pid --tlsverify=false >> /var/log/docker.log 2>&1 &
           Starting docker
           Could not start docker
           STDERR: 
           ---- End output of /etc/init.d/docker start ----
           Ran /etc/init.d/docker start returned 3
           
       Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:119:in `compile_and_converge_action'
           /tmp/kitchen/cache/cookbooks/docker/libraries/docker_service_manager_sysvinit.rb:24:in `block in <class:DockerServiceManagerSysvinit>'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:118:in `instance_eval'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:118:in `compile_and_converge_action'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:119:in `compile_and_converge_action'
           /tmp/kitchen/cache/cookbooks/docker/libraries/docker_service_manager_sysvinit.rb:23:in `block in <class:DockerServiceManagerSysvinit>'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:118:in `instance_eval'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:118:in `compile_and_converge_action'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:119:in `compile_and_converge_action'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:119:in `compile_and_converge_action'
           
       
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/docker-zanox/recipes/new.rb
           
            23:   docker_service 'default' do
            24:     host ['unix:///var/run/docker.sock', 'tcp://0.0.0.0:2375']
            25:     tls_verify false
            26:     action :create
            27:   end
            28: 
           
           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/docker-zanox/recipes/new.rb:23:in `from_file'
           
           docker_service("default") do
             action [:create]
             updated true
             updated_by_last_action true
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :docker_service
             cookbook_name "docker-zanox"
             recipe_name "new"
             host ["unix:///var/run/docker.sock", "tcp://0.0.0.0:2375"]
             install_method "auto"
             service_manager "auto"
           end
           
       
       Running handlers:
       [2016-01-14T15:46:21+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2016-01-14T15:46:21+00:00] ERROR: Exception handlers complete
       Chef Client failed. 19 resources updated in 01 minutes 07 seconds
       [2016-01-14T15:46:21+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2016-01-14T15:46:21+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2016-01-14T15:46:21+00:00] ERROR: docker_service[default] (docker-zanox::new line 23) had an error: Mixlib::ShellOut::ShellCommandFailed: docker_service[default] (docker-zanox::new line 23) had an error: Mixlib::ShellOut::ShellCommandFailed: docker_service_manager_sysvinit[default] (/tmp/kitchen/cache/cookbooks/docker/libraries/docker_service.rb line 64) had an error: Mixlib::ShellOut::ShellCommandFailed: docker_service_manager_sysvinit[default] (/tmp/kitchen/cache/cookbooks/docker/libraries/docker_service.rb line 64) had an error: Mixlib::ShellOut::ShellCommandFailed: service[docker] (/tmp/kitchen/cache/cookbooks/docker/libraries/docker_service_manager_sysvinit.rb line 53) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '3'
       ---- Begin output of /etc/init.d/docker start ----
       STDOUT: /usr/bin/docker daemon -H unix:///var/run/docker.sock -H tcp://0.0.0.0:2375 --pidfile=/var/run/docker.pid --tlsverify=false >> /var/log/docker.log 2>&1 &
       Starting docker
       Could not start docker
       STDERR: 
       ---- End output of /etc/init.d/docker start ----
       Ran /etc/init.d/docker start returned 3
       [2016-01-14T15:46:22+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
>>>>>> Converge failed on instance <default-ubuntu>.

**Comment by someara** [comment]
What platform / versions are you on?
-s

**Comment by anojansivarajah-awin** [comment]
debian 7.9

**Comment by someara** [comment]
This should be fixed up in 2.4.21
