### ISSUE TITLE
Containers being redeployed due to link array order

### ISSUE THREAD

**Issue by paustin01** [chef-cookbooks/docker#613]
Killer cookbook!  First time caller.  Apologies if someone has already reported this but... Running 2.4.4 on ubuntu trusty with docker 1.8.3.  Finding 2 of my containers redeploying on every chef run seemingly due to the links being evaluated in a different order or altogether incorrectly.  For the time being I've reverted to run_if_missing but would be great to have this correctly evaluated.

#### Chef run output
```
  * docker_container[fpm] action run
    - stopping fpm  (will kill after 30s)
    - deleting fpm
    - update fpm
    -   set links to ["cache:cache", "cache-session:cache-session", "db:db"] (was ["cache-session:cache-session", "db:db", "cache:cache"])
    - starting fpm
  * docker_container[web] action run
    - stopping web  (will kill after 30s)
    - deleting web
    - update web
    -   set links to ["fpm:fpm"] (was nil)
    - starting web
```
#### Inspecting the containers

In the case of the "fpm" container upon inspecting I find the order to match the order I defined in the resource properties in my recipe, so it seems the order is getting shuffled on reading it from docker.  Would be great to fix, or can order be ignored altogether?

```
"Links": [
  "/cache:/fpm/cache",
  "/cache-session:/fpm/cache-session",
  "/db:/fpm/db"
],
```

In the case of the "web" container saying links was nil, upon inspecting the container I see the following.  This too matches what I defined in the resource properties but for some reason is being evaluated as nil.

```
"Links": [
  "/fpm:/web/fpm"
],
```

**Comment by someara** [comment]
Fix released in v2.4.6
