### ISSUE TITLE
Upstart and DOCKER_DAEMON_OPTS

### ISSUE THREAD

**Issue by dontrebootme** [chef-cookbooks/docker#617]
If I look at: [upstart template](https://github.com/chef-cookbooks/docker/blob/master/templates/default/upstart/docker.conf.erb#L45-L49), it seems as though we source /etc/default/$UPSTART_NAME and then read that into DOCKER_DAEMON_OPTS. We then move on to launch the docker daemon, but I don't see us passing the DOCKER_DAEMON_OPTS to `docker daemon` line. Additionally, I dont see anywhere from the Docker side of things that it inherently looks for DOCKER_DAEMON_OPTS leading me to believe that this isn't being passed.

In addition to what seems to be populating a variable that we don't pass to the daemon, the cookbook currently does not create the /etc/default/$UPSTART_NAME file, so options passed to the service don't seem to be configured when using upstart based systems.

**Comment by chasebolt** [comment]
https://github.com/chef-cookbooks/docker/blob/master/libraries/helpers_service.rb#L107-L109

**Comment by chasebolt** [comment]
DOCKER_DAEMON_OPTS appears just to be unused. We are pulling from the variable @docker_daemon_cmd which contains the docker bin, docker daemon opts, etc.

https://github.com/chef-cookbooks/docker/blob/master/libraries/helpers_service.rb#L107-L109

**Comment by dontrebootme** [comment]
@chasebolt I see that helper, but I'm not seeing the attribute populated correctly, only `--pidfile` default is coming over as an option.

```script
  # modify these in /etc/default/$UPSTART_JOB (/etc/default/docker)
  DOCKER=/usr/bin/$UPSTART_JOB
  DOCKER_DAEMON_OPTS=
  if [ -f /etc/default/$UPSTART_JOB ]; then
    . /etc/default/$UPSTART_JOB
  fi
  exec /usr/bin/docker daemon --pidfile=/var/run/docker-some-name.pid >> /var/log/docker.log
end script```

```
docker_service 'some-name' do
  version     docker_version
  insecure_registry "registry.mydomain.local"
  action [:create, :start]
end
```

**Comment by dontrebootme** [comment]
I found that I had two colliding recipes in the run list for both a leader and a host role and that it was unsetting the flags set in the first.
