### ISSUE TITLE
load_current_value to only load set properties

### ISSUE THREAD

**Issue by chasebolt** [chef-cookbooks/docker#619]
@jkeiser do you have any ideas on how to see if a property is set within load_current_value? property_is_set?(foo) seems too early in the process to use, _i think_.

**Comment by someara** [comment]
property_is_set tells if the property had a value set by either loading OR user input... this method isn't going to work here. closing for now

**Comment by chasebolt** [comment]
Why you close this lol? The question is based on how to check if a value is set before load current value. My example of property_is_set was just to describe a way of accomplishing my question.
