### ISSUE TITLE
Testing the "bind" property of docker_container with chefspec

### ISSUE THREAD

**Issue by sirkjohannsen** [chef-cookbooks/docker#625]
We ran into the following issue testing the `bind` property of the `docker_container` resource. 

if you use 
`expect(chef_run).to run_docker_container('registry').with(binds: ['/tmp:/var/lib/registry'],tag: 'latest')`
for example and you actually pass this value, the check fails. `binds` value is `{}` 
I found that `binds` is an alias of `volumes` and in your tests I also found that you use `volumes_binds` to test the value passed via `binds` . 
Is this the wanted behaviour ? It seems a little inconsistent to me.

Best,

Sirk

**Comment by chasebolt** [comment]
Preferably don't use binds any more. You should use only volumes OR binds, but not both.

Setting both will cause unwanted behavior because of the aliasing. 

We have removed binds from the README and only refer to volumes now.

**Comment by sirkjohannsen** [comment]
Thank you.  
But with volumes the same problem exists. 
The spec test needs to be `volumes_binds` and not `volumes`. 
If I test for `volumes` I get 
```      
 expected "docker_container[registry]" to have parameters:

         volumes ["/tmp:/var/lib/registry"], was {}
```

**Comment by chasebolt** [comment]
You are correct volumes_binds is what you want to use for spec testing. Sorry on mobile so I can't link easily, but there are already written test on this that should point you in the right direction.

**Comment by sirkjohannsen** [comment]
okay. thank you. I already found it. 
https://github.com/chef-cookbooks/docker/commit/2340da3d64716c95eb572ff9c9f3da2394688093
