### ISSUE TITLE
:run action of docker_container does not trigger a re-creation if volumes change

### ISSUE THREAD

**Issue by caleb** [chef-cookbooks/docker#627]
Hi,

I am not 100% sure this is supposed to work, but it seems like it is the intention.

I have a resource:

```ruby
docker_container 'postgres' do
  repo 'postgres'
  env ["POSTGRES_PASSWORD=password"]
  volumes ['/postgres:/var/lib/postgresql/data']
end
```

If I run my cookbook with this resource, the container is created and starts running.

If I change the resource to:

```ruby
docker_container 'postgres' do
  repo 'postgres'
  env ["POSTGRES_PASSWORD=password"]
  volumes ['/postgres:/var/lib/postgresql/data', '/tmp:/this-is-a-test:ro']
end
```

And re-run my cookbook, the `postgres` container does not get restarted. If I add/change the environment variables and re-deploy the container is restarted.

Any ideas?

**Comment by chasebolt** [comment]
load_current_value needs to set Binds to volumes_binds; currently it does
nothing with this value. We also need to remove `desired_state: false` from
the property.

**Comment by someara** [comment]
Definitely a bug. 

I'll take a look tomorrow...
PS: I'm +1 GMT until the 15th

-s

**Comment by chasebolt** [comment]
I'm currently in Cabo until Saturday. I may get to this tonight depending... 🍻🏄
