### ISSUE TITLE
No such image after upgrading to docker 1.10.0

### ISSUE THREAD

**Issue by gionn** [chef-cookbooks/docker#629]
Pull works if done from command line, there is probably some breakage in the Docker API for image pulling.

```
[2016-02-05T09:43:37+00:00] ERROR: docker_image[mysql] (cd-docker::default line 108) had an error: Docker::Error::NotFoundError: No such image: a500ac2ea36b
```

```
           docker_image("mysql") do
             action [:pull_if_missing]
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :docker_image
             cookbook_name :"cd-docker"
             recipe_name "default"
             repo "mysql"
             tag "5.5.41"
             connection #<Docker::Connection:0x00000005f3a688 @url="unix:///", @options={:socket=>"/var/run/docker.sock", :read_timeout=>120}>
           end
```

**Comment by mads79** [comment]
I have the same issue - is it possible that it's related to the migration issued mentioned in this blog post?
http://blog.docker.com/2016/01/docker-1-10-rc/

It mentions that when you spin up the daemon the first time it will calculate new ID's which includes calculating an SHA256 hash of the image. That can take some time... 

I'm thinking that when you pull an image with an old ID there is a delay before the new ID is calculated, while chef will try to spin up a container immediately... hence the failure?

Adding:
 sleep 360 
after each pull command seems to fix the issue for me, but it's a horrible hack :-(

**Comment by dajudge** [comment]
I am seeing this effect as well.

**Comment by scalp42** [comment]
Not sure if related but there's a bug related to images pull: https://github.com/docker/docker/issues/20051

**Comment by horkhe** [comment]
We are using docker registry:2.3.0 (released along with docker-engine 1.10.0) and the bug is still reproducible, therefore docker/docker#20051 is irrelevant for it refers to pulling from older registry versions.

**Comment by caleb** [comment]
I ran into this as well (hmm, it worked yesterday, but why doesn't it work now :).

For anybody who finds this issue, this is how I manually installed 1.9.1 again:

```ruby
include_recipe 'apt-docker::default'
docker_installation_package('default') { version '1.9.1' }
```

Just include the `apt-docker` (or `yum-docker`, though I haven't tried that) cookbook.

**Comment by alappe** [comment]
I used this to keep the version pinned to 1.9.1:

```ruby
  1 group 'docker' do
  2   action :create
  3 end
  4 
  5 docker_service 'default' do
  6   source 'https://get.docker.com/builds/Linux/x86_64/docker-1.9.1'
  7   checksum '52286a92999f003e1129422e78be3e1049f963be1888afc3c9a99d5a9af04666'
  8   install_method 'binary'
  9   group 'docker'
 10   action [:create, :start]
 11 end
```

**Comment by someara** [comment]
I tracked this down with pry.... reproduced it on pulling hello-world from the hub.

There isn't much to do until the underlying docker-api gem addresses 1.10.0.

https://github.com/chef-cookbooks/docker/blob/3a20780e75a6ab6914a0db49b50f0b6cd0c28885/libraries/helpers_image.rb#L71

-s

**Comment by horkhe** [comment]
@someara has a bug against the docker-api gem been created? Could you please reference it from this issue. Thanks.

**Comment by someara** [comment]
Not yet... I'm still trying to track down exactly what's going on

**Comment by someara** [comment]
v2.4.15 contains a temporary fix until this gets fixed upstream
https://github.com/swipely/docker-api/issues/369

**Comment by someara** [comment]
Closing this here... I'm going to keep an eye on the fix in the other repo
-s

**Comment by gionn** [comment]
it works, great! :dancers:
