### ISSUE TITLE
Validation: Cannot specify hostname, … when network_mode is host.

### ISSUE THREAD

**Issue by alappe** [chef-cookbooks/docker#634]
I'm having a problem with containers where the `network_mode` is `host`:

> Cannot specify hostname, dns, dns_search, mac_address, or extra_hosts when network_mode is host.

The resource declaration is

```ruby
docker_container 'nginx' do
  repo 'nginx'
  tag '1.9'
  restart_policy 'always'
  kill_after 10
  network_mode 'host'
  binds [
    '/container/configs/nginx.conf:/etc/nginx/nginx.conf:ro',
  ]
  action :run_if_missing
end
```

So I did not set any of those properties leading to this validation error. What am I missing?

**Comment by chasebolt** [comment]
open up two terminals. in the first terminal run this https://gist.github.com/chasebolt/3e58bc05203a6fcf5d71 and in the second terminal run chef-client.

gist the full dump from the first terminal

**Comment by chasebolt** [comment]
make sure you have `socat` installed

**Comment by alappe** [comment]
There's the output:

https://gist.github.com/alappe/e9f445ec541b90e4111e

**Comment by gionn** [comment]
Same of #626? This almost drive me crazy...

**Comment by chasebolt** [comment]
thanks. testing fix in test-kitchen right now.
