### ISSUE TITLE
STDERR: start: Job failed to start with docker 1.10.0

### ISSUE THREAD

**Issue by aaronblythe** [chef-cookbooks/docker#637]
I am receiving errors on all my converges with this cookbook (at least on Ubuntu):

     Mixlib::ShellOut::ShellCommandFailed
        ------------------------------------
        Expected process to exit with [0], but received '1'
        ---- Begin output of /sbin/start docker ----
        STDOUT: 
        STDERR: start: Job failed to start
        ---- End output of /sbin/start docker ----
        Ran /sbin/start docker returned 1
...

       [2016-02-09T20:33:32+00:00] ERROR: 
    docker_service[default] (docker_hubot::default line 14) had an error: Mixlib::ShellOut::ShellCommandFailed: 
    docker_service_manager_upstart[default] (/tmp/kitchen/cookbooks/docker/libraries/docker_service.rb line 64) had an error: Mixlib::ShellOut::ShellCommandFailed: 
    service[docker] (/tmp/kitchen/cookbooks/docker/libraries/docker_service_manager_upstart.rb line 29) had an error: Mixlib::ShellOut::ShellCommandFailed: 
    Expected process to exit with [0], but received '1'

I believe I tracked this down by comparing a the /etc/init/docker.conf from a vanilla ubuntu install and the file produced from this cookbook.

https://gist.github.com/aaronblythe/d6fea532bb9d90329659

This cookbook:

    exec /usr/bin/docker -d --pidfile=/var/run/docker.pid >> /var/log/docker.log

Vanilla Ubuntu/Docker installed VM:

    exec "$DOCKER" daemon $DOCKER_OPTS

If I understand correctly, the docker -d option has been deprecated since 1.8 and possibly was removed at 1.10.0.  https://github.com/docker/docker/wiki/Engine-v1.10.0-content-addressability-migration

**Comment by coderanger** [comment]
Docker ships a sample upstart config at https://github.com/docker/docker/blob/v1.10.0/contrib/init/upstart/docker.conf

**Comment by aaronblythe** [comment]
This actually may have been from a Berksfile.lock in my cookbook that was constraining the version a couple back on this cookbook as a dependency.  Feel free to close this, I believe I am around this issue.

**Comment by someara** [comment]
I reproduced this when updating the inspecs for upstart. Marking as a bug.
