### ISSUE TITLE
docker_network: container already connected to network my_network

### ISSUE THREAD

**Issue by alappe** [chef-cookbooks/docker#638]
While I know that `docker_network` is experimental, I need this feature as soon as #629 is resolved so I can use docker `v1.10`. In lack of documentation, I wanted to ask for the way to use this in the future…

I tried it like this:

```ruby
docker_network 'my_network' do
  driver 'bridge'
  action :create
end
```

And then when I set up my containers, I use

```ruby
docker_network 'my_network' do
  container 'my_container
  action :connect'
end
```

Is the right way? On the second chef-run, the run fails with »container already connected to network my_network«.

Is there a guard-clause I can use (and miss) or is this part of the experimental feature, missing idempotency for now?

**Comment by gionn** [comment]
try with `network_mode 'my_network'` on a `docker_container` resource.

**Comment by alappe** [comment]
Ah, ok… thanks @gionn

**Comment by alappe** [comment]
@gionn Does this work for you?

Now that I had the time to test it, it doesn't for me…

**Comment by gionn** [comment]
If you use `network_mode` on `docker_container`, you don't have to use `docker_network` with `action :connect`, but only the first with `action :create`.

`network_mode` has been working for me for weeks, I am using cookbook version 2.4.15.

**Comment by alappe** [comment]
@gionn Thank you again, I must have had something else broken during my tests—indeed it works as you say!

**Comment by someara** [comment]
Hello!

I've been working on revamping the test recipe... 

https://github.com/chef-cookbooks/docker/blob/8f77c66b180e9bd998db975fe498620899b7ef3e/test/cookbooks/docker_test/recipes/network.rb#L114

I'm thinking the :connect and :disconnect actions should be removed and put into a docker_network_connection resource.

This reminds me of the docker_image :tag operation that was moved out into the docker_tag resource.

-s
