### ISSUE TITLE
docker_network aux_address property broken

### ISSUE THREAD

**Issue by someara** [chef-cookbooks/docker#645]
The aux_address property on the docker_network doesn't seem to be working.

https://github.com/chef-cookbooks/docker/blob/8f77c66b180e9bd998db975fe498620899b7ef3e/test/cookbooks/docker_test/recipes/network.rb#L76

Doing it by hand lets me figure out what the inspec should look like.

https://github.com/chef-cookbooks/docker/blob/f9b559c0e92f0bef1e9db5ba409bfa559b203d66/test/integration/network/serverspec/assert_functioning_spec.rb#L69-L73

-s

**Comment by someara** [comment]
Paging @gionn

**Comment by smgt** [comment]
Made a PR, kinda silly error. https://github.com/chef-cookbooks/docker/pull/646/files#diff-85ca069b2156679441b35497a4782412R38

**Comment by someara** [comment]
Fixed this up with property coersion and converge_if_changed.
Released in 2.5.0

**Comment by smgt** [comment]
Nice work!
