### ISSUE TITLE
Refactor documentation

### ISSUE THREAD

**Issue by someara** [chef-cookbooks/docker#650]
This README is getting a bit... long.

The documentation should exist in a docs/ tree and broken up into smaller sections.
This will make it more digestible, and allow for more detailed explanations and commentary

**Comment by chasebolt** [comment]
This will be a nice change! Tired of so much scrolling on the rare occasions I need to update / read through it.

**Comment by ikrauchanka** [comment]
@chasebolt in order to speed up the seearch try to use ctrl+F/cmd+F 
I found this documentation well formed - all is on one page.

**Comment by CVTJNII** [comment]
Agreed,  -1 for making the documentation harder to search.  I prefer to see it all in one page so I can quickly search in my browser to what I'm looking for.  I don't think the readme being long is a problem, instead I think it's a symptom of the cookbook becoming too complicated.
