### ISSUE TITLE
Add VolumeDriver into docker_container resource

### ISSUE THREAD

**Issue by yongtin** [chef-cookbooks/docker#654]
Can we add "VolumeDriver" as part of the docker_container resource?  

https://docs.docker.com/engine/reference/api/docker_remote_api_v1.22/#create-a-container

**Comment by chasebolt** [comment]
Looks like VolumeDriver is being deprecated in the next release.

https://github.com/docker/docker/issues/16069
https://github.com/docker/docker/pull/16595

**Comment by someara** [comment]
Indeed. The `docker_volume` resource has a driver property.

Looks like that's the way to go... There is a driver property on the `docker_volume` resource here
https://github.com/chef-cookbooks/docker/blob/master/libraries/docker_volume.rb#L7

You should be able to use it in a recipe that looks a lot like this one:
https://github.com/chef-cookbooks/docker/blob/master/test/cookbooks/docker_test/recipes/volume.rb

That's the quickest example of a volume driver we could get going in a test recipe?
I took a look at flocker, but it seems like a can of worms. Is there something easier to set up?

-s

**Comment by someara** [comment]
Making a note for myself here to check out rexray - https://github.com/emccode/rexray
Closing this issue for now... let me know if the `docker_volume` resource doesn't fit your needs.
-s

**Comment by vamsivv** [comment]
How do i pass nfs to volumes. Currently i'm passing volumes with json like below and using docker_container resource

			    "volumes":{
					"/opt/nfsshare":"/mnt"
				},

I would like to pass --volume-driver to above volume as nfs. How do i achieve this?
