### ISSUE TITLE
Add support for AWS ECR login in docker_registry

### ISSUE THREAD

**Issue by chrisferry** [chef-cookbooks/docker#660]
See here:
http://docs.aws.amazon.com/AmazonECR/latest/userguide/ECR_GetStarted.html

AWS ECR requires you retrieve login credentials using their API.
Currently the docker cookbook doesn't natively support this.

**Comment by someara** [comment]
Trying to figure out the best way to handle credentials...

The docs refer to parsing the output of `aws ecr get-login --region us-east-1`, which would require the installation of the Amazan SDK, and imply previous authentication creds stashed on disk somewhere.... 

The alternative would be to depend on the aws-sdk rubygem. Perhaps this resource belongs in the AWS cookbook?

Just thinking out loud. *rubs chin*

-s

**Comment by chasebolt** [comment]
I've only briefly went over the docs on this. But I think at best we should
just include an example in the docs of how to do this in the user's wrapper
cookbook. That way their wrapper is dependent on the AWS portion and it
stays outside of the docker cookbook.

**Comment by chasebolt** [comment]
We could also have this feature, to grab the login credentials, added to
the AWS cookbook to simplify the wrapper cookbook even further

**Comment by chrisferry** [comment]
Currently I have a definition that installs the latest stable awscli via pip and then parses the output of the get-login and uses that to login vi docker_registry.
https://gist.github.com/chrisferry/f716d3e74d534598eaa5
It's not the best solution, but it works.

**Comment by someara** [comment]
I'm going to close this here, as it's outside the scope of this cookbook.
However, can you open an issue in the AWS cookbook and reference this ticket?

I think the best thing to do would be to create an ecr_registry Custom Resource in the AWS cookbook that uses the docker_registry resource under the hood in the spirit of your definition.

```ruby
ecr_registry 'whatever' do
  region 'us-east-1'  
end
```
