### ISSUE TITLE
docker registry resource doesent log user in.

### ISSUE THREAD

**Issue by willejs** [chef-cookbooks/docker#668]
Im declaring the registry like so: 
```
docker_registry 'https://index.docker.io/v1/' do
  username item['username']
  password item['password']
  email    item['email']
end
```
I see this in the chef run logs
```  * docker_registry[https://index.docker.io/v1/] action login (up to date)```
However, When I run docker info it appears i am not logged in. there is no /root/.docker/config.json created either.

**Comment by someara** [comment]
Hi.

It doesn't shell out to `docker login`, it authenticates for the duration
of the chef-client run.
This lets any docker_container and docker_images resources do their thing.
Docker CLI doesn't even need to be on the machine.

-s

**Comment by willejs** [comment]
ahh, @someara that makes total sense now! I read the code but didnt realise how the /auth endpoint worked. Thanks!
