### ISSUE TITLE
Issue with two docker_services and iptables

### ISSUE THREAD

**Issue by michaelajr** [chef-cookbooks/docker#669]
We have followed the examples of how to run two containers as two different systemd services, but we are having trouble getting the networking to work and I worry that there might be a bug.
```
# JENKINS: create the on-demand systemd socket for jenkins
docker_service 'jenkins' do
  graph '/var/lib/docker-jenkins'
  host 'unix:///var/run/docker-jenkins.sock'
  action :start
end

# SONAR: create the on-demand systemd socket
docker_service 'sonar' do
  graph '/var/lib/docker-sonar'
  host 'unix:///var/run/docker-sonar.sock'
  action :start
end

# JENKINS: download the jenkins image
docker_image 'jenkins' do
  host 'unix:///var/run/docker-jenkins.sock'
  repo 'REPO/NAMESPACE/jenkins'
  tag node['jenkins_version']
  action :pull
end 

# SONAR: download the sonar image
docker_image 'sonar' do
  host 'unix:///var/run/docker-sonar.sock'
  repo 'REPO/NAMESPACE/sonar'
  tag node['sonar_version']
  action :pull
end 

# JENKINS: run the jenkins container
docker_container 'jenkins' do
  host 'unix:///var/run/docker-jenkins.sock'
  repo 'REPO/NAMESPACE/jenkins'
  tag node['jenkins_version']
  restart_policy 'always'
  container_name 'jenkins'
  user 'jenkins'
  volumes ['/var/lib/jenkins:/var/jenkins_home']
  port '8443:8443'
  action :run
end

# SONAR: run the sonar container (if not running)
docker_container 'sonar' do
  host 'unix:///var/run/docker-sonar.sock'
  repo 'REPO/NAMESPACE/sonar'
  tag node['sonar_version']
  restart_policy 'always'
  container_name 'sonar'
  port '9443:9443'
  env [
    "SONARQUBE_JDBC_URL=#{node['sonar_jdbc_url']}",
    "SONARQUBE_JDBC_USERNAME=#{node['sonar_jdbc_username']}",
    "SONARQUBE_JDBC_PASSWORD=#{node['sonar_jdbc_password']}",
  ]
  action :run
end 
```
They both come up. And they are both running. 
```
% docker -H unix:///var/run/docker-jenkins.sock ps
CONTAINER ID        IMAGE                                                         COMMAND                  CREATED             STATUS              PORTS                                         NAMES
d24d56b3942d        REPO/NAMESPACE/jenkins:1.642.1-PATCH   "/bin/tini -- /usr/lo"   5 minutes ago       Up 5 minutes        8080/tcp, 50000/tcp, 0.0.0.0:8443->8443/tcp   jenkins

% docker -H unix:///var/run/docker-sonar.sock ps
CONTAINER ID        IMAGE                                             COMMAND             CREATED             STATUS              PORTS                              NAMES
29e9ab136376        REPO/NAMESPACE/sonar:5.3   "./bin/run.sh"      6 minutes ago       Up 6 minutes        9000/tcp, 0.0.0.0:9443->9443/tcp   sonar
```
But both daemons seem to be using the same IP address:
```
% docker -H unix:///var/run/docker-sonar.sock inspect sonar | grep -i ipaddr
            "SecondaryIPAddresses": null,
            "IPAddress": "172.17.0.2",
                    "IPAddress": "172.17.0.2",

% docker -H unix:///var/run/docker-jenkins.sock inspect jenkins | grep -i ipaddr
            "SecondaryIPAddresses": null,
            "IPAddress": "172.17.0.2",
                    "IPAddress": "172.17.0.2",
```
And this is messing up the iptables routing. 
```
% iptables -S DOCKER
-N DOCKER
-A DOCKER -d 172.17.0.2/32 ! -i docker0 -o docker0 -p tcp -m tcp --dport 8443 -j ACCEPT
-A DOCKER -d 172.17.0.2/32 ! -i docker0 -o docker0 -p tcp -m tcp --dport 9443 -j ACCEPT
```
I can only route to one at a time.  I can stop one. Then the other works (routes). If I bring up the stopped one, I can not get to it (route to it) - until I stop the other one - then it works (routes). 

My apologies if this is user error and not an “issue”, but I wanted to bring it up in case this was a bug.

**Comment by chasebolt** [comment]
According to the docs there is a small chance of a network collision

https://docs.docker.com/v1.8/articles/networking
> When Docker starts, it creates a virtual interface named docker0 on the host machine. It randomly chooses an address and subnet from the private range defined by RFC 1918 that are not in use on the host machine, and assigns it to docker0.

You can set the `bip` on the `docker_service` resource to prevent a collision. In the future we may handle this case in the library, but that work around should suffice for now.

**Comment by chasebolt** [comment]
The issue appears to be both `docker_service` resources are using the same docker bridge `docker0`. At the moment I can't come up with a quick workaround for this issue.

In order to run two instances of `docker_service` with networking capabilities, we need to manually create custom bridges as assign each one to a `docker_service`.

https://docs.docker.com/v1.8/articles/networking/#docker0

**Comment by michaelajr** [comment]
Can this be done using the ``docker_network``` LWRP? I was looking at it, but was unable to get it to work with ```docker_container``` the way README indicates.

**Comment by chasebolt** [comment]
I haven't worked with `docker_network` much yet, but from a quick overview it doesn't appear it creates the same kind of bridge as `docker0`.

```
root@service-systemd-multi-ubuntu-1504:~# brctl show
bridge name	bridge id		STP enabled	interfaces
br-62a09963414c		8000.024237ea5e17	no
br-afec8f9163b6		8000.0242b1a6891a	no
docker0		8000.0242b8629114	no		vetha775b54
							vethb8d93a9
root@service-systemd-multi-ubuntu-1504:~#
```

**Comment by michaelajr** [comment]
I feel like the reason one would start multiple services - would be to use the services to manage the docker daemon (containers), and do so separately from other services/daemons/containers. So I think this is an important issue to fix (or document if there is a way to was easily do so via the LWRPs).

**Comment by chasebolt** [comment]
@michaelajr I went over the `docker_network` resource. You'll need to create a new network and then link the container to that network. If you want jenkins and sonar separate, then you will create two networks.

Here is an example of a multi-network layout with multiplate containers tied to them. https://github.com/chef-cookbooks/docker/blob/master/test/cookbooks/docker_test/recipes/network.rb

Hope this helps!

**Comment by michaelajr** [comment]
@chasebolt Thank you for the help. Will look this over and implement.

**Comment by chasebolt** [comment]
Closing but feel free to comment if you need additional assistance.
