### ISSUE TITLE
docker group attribute/method

### ISSUE THREAD

**Issue by ehaselwanter** [chef-cookbooks/docker#671]
Hi,

is there a way to get the current group used for docker?

```
group 'docker' do
  members [node['jenkins']['master']['user']]
  append true
  action :modify
end
```

feels so wrong

**Comment by chasebolt** [comment]
you can get the gid from `node['etc']['group']['docker']['gid']`

**Comment by ehaselwanter** [comment]
well. this does not solve my problem. I would like to find out the name of the group for the docker installation. not the gid of a known name.

**Comment by chasebolt** [comment]
The group name is always docker

**Comment by ehaselwanter** [comment]
it is? this line got me thinking: https://github.com/chef-cookbooks/docker/blob/master/libraries/helpers_service.rb#L144 which indicates a customization option.
but yes. I'll default to the hardcoded `docker` string for now

**Comment by chasebolt** [comment]
If the user is specifying a group then they need to be creating that on their own as this docker library just directly passes the property string to the docker daemon.

iirc the docker binary install runs as root while packages install runs as docker - I haven't seen it as a different group name so far.

Hope this help!

**Comment by ehaselwanter** [comment]
I guess so. we'll see. for now it is fine. I just would have used an obvious attribute/helper method if there would have been one.
