### ISSUE TITLE
Chefspec fails with undefined method `step_into?' for nil:NilClass

### ISSUE THREAD

**Issue by paustin01** [chef-cookbooks/docker#675]
Recently bumped from 2.5.5 to 2.5.8 and seeing the following error.  I'm guessing it has to do with the following change: https://github.com/chef-cookbooks/docker/commit/2de6d0cd0c0657c9396e0a87506a6acef40862f1

```
  1) lms_webhost::database When all attributes are default, on an unspecified platform creates the database
     Failure/Error: end.converge(described_recipe)
     NoMethodError:
       undefined method `step_into?' for nil:NilClass
     # /var/folders/r4/bbrc6qx91nv69qqgtrgqzfhr0000gn/T/d20160304-83805-22p9qs/cookbooks/docker/libraries/_autoload.rb:10:in `rescue in <top (required)>'
     # /var/folders/r4/bbrc6qx91nv69qqgtrgqzfhr0000gn/T/d20160304-83805-22p9qs/cookbooks/docker/libraries/_autoload.rb:1:in `<top (required)>'
     # ./spec/unit/recipes/database_spec.rb:14:in `block (3 levels) in <top (required)>'
     # ./spec/unit/recipes/database_spec.rb:46:in `block (3 levels) in <top (required)>'
```

**Comment by chasebolt** [comment]
Looks like you need to run `bundler install`

**Comment by chasebolt** [comment]
Actually are you trying to run rspec?

**Comment by paustin01** [comment]
Thanks for the quick response (and for the kickass cookbook)!  Should I need to run bundle install to test the cookbook?  Just running chefspec on my cookbook which has a dependency on the docker cookbook.

**Comment by chasebolt** [comment]
Yup! You need to run bundled install to install all the dependencies for the spec tests. This will install the docker gem for testing.

**Comment by paustin01** [comment]
My apologies then...didn't realize that was required.  Thanks for the help!

**Comment by chasebolt** [comment]
Not a problem! 😄

**Comment by ephracis** [comment]
I am getting the same error, even after running `bundle install`, `gem install docker` and `chef gem install docker`. I am also getting these errors:

> undefined method `pull_docker_image' for #<RSpec::ExampleGroups::ElkImages::WhenAllAttributesAreDefault:0x007f9cce5b2fa8>

They occur for every matcher (`import_docker_image`, `tag_docker_tag`, etc).
