### ISSUE TITLE
`docker_container` and guard clauses

### ISSUE THREAD

**Issue by alappe** [chef-cookbooks/docker#676]
I'm using multiple versions of `docker_container` with guard clauses like `only_if` for different environments (dev/staging/prod). This doesn't seem to work anymore, now the first definition of the `docker_container` is started…

Is this wrong usage or could it be a bug?

```ruby
 not_if { node.chef_environment == 'staging' }
```

*Versions*:
Cookbook: `2.4.24`
Chef: `12.5.1`
Docker: `1.10.2`

**Comment by chasebolt** [comment]
We have working examples of using not_if in test-kitchen. https://github.com/chef-cookbooks/docker/blob/master/test/cookbooks/docker_test/recipes/container.rb#L21-L26

**Comment by alappe** [comment]
Hey @chasebolt,

thanks for the quick response, sorry I didn't see them before. Alright, in that case it has to be something else…

Sorry for bothering
