### ISSUE TITLE
rspec fails on chefdk 0.11.2

### ISSUE THREAD

**Issue by vinyar** [chef-cookbooks/docker#677]
undefined method `step_into?' for nil:NilClass

$ chef -v
Chef Development Kit Version: 0.11.2
chef-client version: 12.7.2
berks version: 4.2.0
kitchen version: 1.5.0

full(er) error
```
$ chef exec rspec
Run options: include {:focus=>true}

All examples were filtered out; ignoring {:focus=>true}

================================================================================
Recipe Compile Error in /var/folders/9r/g1wlns1j29bg0c7b_6fr7b480000gr/T/d20160308-15455-1fq9xca/cookbooks/docker/libraries/_autoload.rb
================================================================================

NoMethodError
-------------
undefined method `step_into?' for nil:NilClass

Cookbook Trace:
---------------
  /var/folders/9r/g1wlns1j29bg0c7b_6fr7b480000gr/T/d20160308-15455-1fq9xca/cookbooks/docker/libraries/_autoload.rb:10:in `rescue in <top (required)>'
  /var/folders/9r/g1wlns1j29bg0c7b_6fr7b480000gr/T/d20160308-15455-1fq9xca/cookbooks/docker/libraries/_autoload.rb:1:in `<top (required)>'

Relevant File Content:
----------------------
/var/folders/9r/g1wlns1j29bg0c7b_6fr7b480000gr/T/d20160308-15455-1fq9xca/cookbooks/docker/libraries/_autoload.rb:

  3:  rescue LoadError
  4:    run_context = Chef::RunContext.new(Chef::Node.new, {}, Chef::EventDispatch::Dispatcher.new)
  5:
  6:    require 'chef/resource/chef_gem'
  7:
  8:    docker = Chef::Resource::ChefGem.new('docker-api', run_context)
  9:    docker.version '= 1.26.2'
 10>>   docker.run_action(:install)
 11:  end
 12:

F
```

**Comment by chasebolt** [comment]
you need to run `bundle install`

**Comment by b-dean** [comment]
This seems to be similar to sethvargo/chefspec#676

I wonder, is it normal to make a run_context in an rb file in the libaries folder? So you're trying to run resources during cookbook compilation? Would there maybe be some way to use the `chef_gem` resource in the various DockerCookbook resource actions so it has the real run_context?

**Comment by chasebolt** [comment]
We stay away from using chef_gem so a recipe doesn't need to be included.

This is only an issue if you don't install the gem deps listed in the Gemfile; which you should be if you are running these tools.

**Comment by b-dean** [comment]
But you are using chef_gem, just not in a recipe. And if you used a chef_gem resource as a resource in the actions of your resources, no one would need to have some recipe included either (the same way the DockerCookbook resources use all sorts of other resources in the actions: `execute`, `package`, etc.)

And certainly if someone is running the specs for the docker cookbook itself they should do `bundle install`. But there's nothing (that I could find at least) that gave me any indication that some *other* cookbook that depends on the docker should have `gem 'docker-api'` in its `Gemfile`

**Comment by chasebolt** [comment]
The current method is very much improved compared to our old method of vendoring the required gems; which caused gem conflicts (specifically excon). chef_gem isn't accessible during loading of the libraries, so it will fail out. That is why we load it the way we do.

With that said, we are all for improving it even further. Feel free to submit a PR if you get that working.

**Comment by vinyar** [comment]
Got ya. My usual first step with any cookbook is to run rspec.
I am using vanilla install of ChefDK which comes with docker-api (1.26.0). 

on a side note, I tried kitchen test xx against a few suits and got below error every time.
`Demand that cannot be met: (docker = 2.5.8)
Artifacts for which there are conflicting dependencies: compat_resource = 12.7.3 -> []Unable to find a solution for demands: apt (2.9.2), apt-docker (0.3.0), compat_resource (12.7.3), docker (2.5.8), docker_test (0.5.1), etcd (3.2.5), yum (3.10.0), yum-docker (0.3.0)]`

I am not against closing this bug.

**Comment by chasebolt** [comment]
Sounds like you need to run berks install

**Comment by vinyar** [comment]
I am not against having this issue closed, unless @b-dean has any additional comments.

**Comment by b-dean** [comment]
Feel free to close it. I putting `docker-api` in the Gemfile of any cookbook that depends on docker is a bit annoying, but solves the problem. I haven't had time to see if I could figure out a different way to get that docker-api gem installed in chef. If I ever look at it, I'll mention this issue on a PR.

**Comment by vinyar** [comment]
got ya. closing as is.
