### ISSUE TITLE
Exception class names and error messages renamed from fail ro raise

### ISSUE THREAD

**Issue by CVTJNII** [chef-cookbooks/docker#678]
In d763917c87dcf755300d64b10d32acffb4d60046 an indiscriminate search and replace appears to have been run to raise exceptions via raise instead of fail.  However, the string "fail" was not only present as fail() calls.  Exception class and error message strings were also changed:

- ["Container raiseed to stop" error](https://github.com/chef-cookbooks/docker/commit/d763917c87dcf755300d64b10d32acffb4d60046)
- [Chef::Exceptions::Validationraiseed class](https://github.com/chef-cookbooks/docker/blame/master/libraries/docker_container.rb#L214)

These should probably be changed back.  The error messages, specifically 'Container raiseed to stop', do not make sense as written.

**Comment by chasebolt** [comment]
#674 will fix this
