### ISSUE TITLE
Feature request : adding multiple insecure_registry

### ISSUE THREAD

**Issue by sunggun-yu** [chef-cookbooks/docker#684]
Hi,

Thank you for great cookbook!
currently, I'm doing like below to have multiple `insecure_registry`

```
docker_service 'default' do
	insecure_registry "#{node['mydocker']['registry']['hostname1']} --insecure-registry #{node['mydocker']['registry']['hostname2']}"
	action [:create, :start]
end
```
as a result, docker daemon runs like,
```
/usr/bin/docker daemon --insecure-registry=registry1 --insecure-registry registry2 --pidfile=/var/run/docker.pid
```

I works perfectly. however, It will be nice if `insecure_registry` support the Array type.

Please think about it.

Thank you.

**Comment by jperville** [comment]
Hi can do the PR this weekend, please keep good job on mongodb cookbook @sunggun-yu

**Comment by sunggun-yu** [comment]
@jperville Thank you!

**Comment by jperville** [comment]
@chasebolt is too fast, no time to even start writing the PR :)

**Comment by chasebolt** [comment]
:zap: :laughing: 

quick and easy feature :)
