### ISSUE TITLE
Changed volumes in docker_container not detected

### ISSUE THREAD

**Issue by ephracis** [chef-cookbooks/docker#692]
I have a `docker_container` resource with action `:create`. If I change the volumes to be mounted and rerun Chef Client it says that the resource is up to date and does not change the mounts.

**Comment by chasebolt** [comment]
Please paste your before and after resource

**Comment by ephracis** [comment]
The code is inside an air-gapped system so I cannot paste it for you, but what I am doing is changing the volumes of the container, which is set from a variable.

```ruby
docker_container 'foobar' do
    volumes config[:volumes]
end
```

In the first run, `config[:volumes] = ["/foo:/bar:Z"]` and in the second run `config[:volumes] = ["/foo:/baz:Z"]`. This change is not detected. I need to manually delete the container before running chef-client.

**Comment by chasebolt** [comment]
What version of the cookbook are you running?

**Comment by chasebolt** [comment]
I can't replicate this in the current version. Please submit a test case and I'll look further into it.

**Comment by chasebolt** [comment]
feel free to reopen when you have a test case for this
