### ISSUE TITLE
Converge fails with 'read timeout reached' on docker container restart action

### ISSUE THREAD

**Issue by razor-x** [chef-cookbooks/docker#693]
I made a cookbook with the steps to reproduce this issue:

https://github.com/rxbugs/chef-docker-read_timeout

**NOTE**: Originally, I only got this error with `$ kitchen test` and not `$ kitchen converge`, but now with the test cookbook, even `$ kitchen converge` is periodically failing with this error.

Given a recipe like the one below, `$ kitchen converge` will succeed, but `$ kitchen test` will fail with a read timeout error on the `restart` action, e.g.,

```
================================================================================
Error executing action `restart` on resource 'docker_container[nginx]'
================================================================================

Docker::Error::TimeoutError
---------------------------
read timeout reached
```

The `file` resource represents a config file or something that needs to notify the docker container to restart if it's updated.

This is not limited to the nginx container: the test cookbook also contains a failing php example. I've only tested this so far with platform `centos-7.2`.

```ruby
docker_service 'default' do
  action [:create, :start]
end

file '/tmp/test.conf' do
  content '# test'
  notifies :restart, 'docker_container[nginx]'
end

docker_image 'nginx' do
  tag 'latest'
  action :pull
  notifies :redeploy, 'docker_container[nginx]'
end

docker_container 'nginx' do
  repo 'nginx'
  tag 'latest'
  subscribes :run_if_missing, 'docker_service[default]'
end
```

**Comment by chasebolt** [comment]
this typically results in slow network connections during downloads. you can attempt at increasing the timeout (pulled from README examples).

```ruby
docker_image 'nginx' do
  read_timeout 120
  write_timeout 120
end
```

**Comment by chasebolt** [comment]
This issue seems to have surpassed. From my logs it appears docker hub was being slow during this time and hitting the read timeout. Increasing the read timeout can help get around the issue of a slow download.

**Comment by ephracis** [comment]
I am having this error too. It seems to be due to Chef restarting the container right after starting it.

I haven't been able to fix this. Increasing the read timeout on the container resource does not solve it.

**Comment by someara** [comment]
recipe? steps to reproduce?

**Comment by ephracis** [comment]
Pretty much same as OP:

```ruby
template "/srv/gitlab/config/gitlab.rb" do
  notifies :restart, 'docker_container[gitlab]', :delayed
end

docker_image 'gitlab/gitlab-ce' do
  tag 'latest'
end

docker_container 'gitlab' do
  repo 'gitlab/gitlab-ce'
  tag 'latest'
  volumes [
    "/srv/gitlab/config:/etc/gitlab",
    "/srv/gitlab/data:/var/opt/gitlab",
    "/srv/gitlab/logs:/var/log/gitlab"
  ]
  port ['80:80']
  restart_policy 'on-failure'
  restart_maximum_retry_count 2
  read_timeout 600
  action [:create, :start]
end
```

I believe the issue here is that at first convergence the template file is changing, this telling the container to restart at the end of the chef run. But the last thing that happens in the recipe is the startup of the container. So chef will first start the container and the immediately try to restart it.

I have no idea if what's in the container has any effect, but gitlab is pretty slow to start, especially the first time.
