### ISSUE TITLE
How to mimic 'docker stop -t...' command

### ISSUE THREAD

**Issue by AlvinFeng** [chef-cookbooks/docker#698]
I'm a bit confused from reading the documentation what is the proper way to replicate https://docs.docker.com/engine/reference/commandline/stop/.

What I'd like to do is if a config template changes for the container to gracefully (SIGTERM then SIGKILL after X seconds) restart.

I've tried a few different versions of the following but haven't had any luck.

```
template "config.yml" do
    notifies :kill, 'docker_container[registry]', :immediately
end

docker_container 'registry' do
    repo registry
    tag 2
    kill_after 300
    signal 'SIGTERM'
    action :run_if_missing
end
```

Any help would be appreciated.

**Comment by chasebolt** [comment]
by default the api will send SIGTERM first and then SIGKILL once `kill_after` timer expires.

```ruby
template "config.yml" do
    notifies :restart, 'docker_container[registry]', :immediately
end

docker_container 'registry' do
    repo registry
    tag 2
    kill_after 300
    action :run_if_missing
end
```

**Comment by AlvinFeng** [comment]
thanks!
