### ISSUE TITLE
Explain what is meant by "automatically select an installation method"

### ISSUE THREAD

**Issue by eherot** [chef-cookbooks/docker#704]

**Comment by chasebolt** [comment]
https://github.com/chef-cookbooks/docker#docker_installation

going to close this as the README does explain it. if you'd like to expand on this feel free to submit a PR.

**Comment by eherot** [comment]
The trouble is I'm not sure I quite understand what exactly the "provider resolution system" would do.

Am I correct in inferring that [this line](https://github.com/chef-cookbooks/docker/blob/master/libraries/docker_installation_script.rb#L8) means that the `script` method is actually the default?
