### ISSUE TITLE
Facing issue in pull ENV value in docker_container resource

### ISSUE THREAD

**Issue by sandeephello** [chef-cookbooks/docker#713]
### Cookbook version
v2.7.1

### Chef-client version
12.10.14

### Platform Details
Amazon Linux

### Scenario:
I am trying to use this docker cookbook for AWS ecs agent configuration by using environment variable option. I have private repository credentials in chef data bag so trying to pull those credentials and storing into ecs agent container configuration. 

I am using docker_container resource and Env property to run ecs-agent container but not able to get "auth" value from data bag.like

ECS_ENGINE_AUTH_DATA={"https://index.docker.io/v1/":{"auth":"XXXXXXXXXXXXXXXXXXXXX","email":"email@example.com"}}

the value is in curly brackets which is not working in docker resources.  I am getting ruby syntax error while uploading cookbook on Chef Server. I tried with  escape character also but still not working.

Is it possible to use environment file --env-file=[] option in this cookbook? If not then please consider this as a feature request.

**Comment by chasebolt** [comment]
Post full example code. If you are pulling from data bag then I don't understand, from your current example, on why you'd be getting syntax error since that data isn't present during a cookbook upload

**Comment by sandeephello** [comment]
sorry my mistake. 

I tired today morning the same code and now it is working fine. 

 "ECS_ENGINE_AUTH_DATA={\"#{node.repourl}\":{\"auth\":\"#{node.auth}\",\"email\":\"#{node.email}}}\""  

I am using this variable which is working now.
