### ISSUE TITLE
Can't mount docker.sock

### ISSUE THREAD

**Issue by sklemmer** [chef-cookbooks/docker#720]
### Cookbook version

2.6.8 & .8.0
### Chef-client version

12.11.18
### Platform Details

Ubuntu 14.04
### Scenario:

I'm trying to start a rancher agent. This requires to mount docker socket as volume
### Steps to Reproduce:

```
docker_image 'rancher/agent' do
  tag 'v1.0.1'
  action :pull
end

docker_container 'ranger-agent' do
  repo 'ranger/agent'
  tag 'v1.0.1'
  command 'register'
  volumes ['/var/lib/rancher:/var/lib/rancher', '/var/run/docker.sock:/var/run/docker.sock']
end
```
### Expected Result:

Container starts and log shows that the RANCHER_URL env variable is missing
### Actual Result:

Nothing seems to happen.

```
sudo docker ps -a 
```

shows that no container is or was running.
When i try to start the container with command and without volumes the container starts.
When i try to start again without command but with volumes the container also starts, but i need both; the volumes and the command

**Comment by someara** [comment]
Hi.

I set up a test to try and reproduce this, and got your expected result.

https://github.com/chef-cookbooks/docker/blob/someara/720-reproduce/test/cookbooks/docker_test/recipes/rancher.rb

^ I copy-pasta'ed your code and found a spelling error in your container property. "ranger" vs "rancher".

After converting that recipe, I can log in, inspect the logs, and see the following

```
root@vm:~# docker ps -a
CONTAINER ID        IMAGE                  COMMAND              CREATED             STATUS                          PORTS               NAMES
e272af6a008d        rancher/agent:v1.0.1   "/run.sh register"   20 minutes ago      Exited (0) About a minute ago                       ranger-agent
root@rancherubuntu14-someara-therailroad-zs3xxsv:~# docker logs ranger-agent

INFO: No RANCHER_URL environment variable, exiting

INFO: No RANCHER_URL environment variable, exiting
root@vm:~#
```
