### ISSUE TITLE
feature request: mount the container's root filesystem as read only

### ISSUE THREAD

**Issue by andrewhsu** [chef-cookbooks/docker#721]
Would be nice to have `docker_container` cookbook resource support running a container like the `--read-only` option of [docker run](https://docs.docker.com/engine/reference/commandline/run/).

The [docker remote api](https://docs.docker.com/engine/reference/api/docker_remote_api_v1.24/#create-a-container) for `POST /containers/create` accepts a JSON param for `HostConfig` called `ReadonlyRootfs`.

**Comment by andrewhsu** [comment]
@ johnbyrneio

**Comment by chasebolt** [comment]
released in v2.9.2

**Comment by docwhat** [comment]
FYI: The name of the option for the `docker_container` is `ro_rootfs`.
