### ISSUE TITLE
Support user namespace mode for containers

### ISSUE THREAD

**Issue by jwmarshall** [chef-cookbooks/docker#722]
### Cookbook version
2.9.0

### Chef-client version
12.6.0

### Platform Details
Ubuntu 14.04

### Scenario:
Since #715 implemented user namespace support for Docker daemon this cookbook should also support enabling it on containers.

### Steps to Reproduce:
N/A feature not implemented

### Expected Result:
Expecting to use user namespace remapping on deployed containers.

### Actual Result:
N/A feature not implemented

**Comment by chasebolt** [comment]
released in v2.9.1
