### ISSUE TITLE
500 error on container delete 

### ISSUE THREAD

**Issue by rlewkowicz** [chef-cookbooks/docker#729]
### Cookbook version

v2.9.2
### Chef-client version

12.12.13
### Platform Details

Vagrant centos-7.2 (I think it's just the bento box then)
### Scenario:

Trying to remove a custom docker container and getting a 500
### Steps to Reproduce:

https://github.com/spindance-ops/sd.chef.mediawiki

Should be able to pull and do a kitchen converge, then a second run throws an uninitialized 500 
### Expected Result:

Should remove the container.
### Actual Result:

It's a bit sloppy because I've been throwing stuff at the wall, but it will fail on a redeploy as well as delete.

```
  ================================================================================
           Error executing action `delete` on resource 'docker_container[remove hhvm]'
           ================================================================================

           NameError
           ---------
           uninitialized constant Excon::Errors::InternalServerError
```

I don't think this has come up. Googling has not been very fruitful.

**Comment by someara** [comment]
I can't seem to reproduce this....

:delete is exercise in test-kitchen here

https://github.com/chef-cookbooks/docker/blob/84a4b256a59493026b9f00b56f19d2ef63f7a9b1/test/cookbooks/docker_test/recipes/container.rb#L196-L214

Is this still an issue for you?

-s

**Comment by rlewkowicz** [comment]
I moved over to the core docker tooling for service definitions (I do appreciate the response though). I have to rewrite that cookbook at some point.
