### ISSUE TITLE
Docker installation sometimes requires more work… 

### ISSUE THREAD

**Issue by rmoriz** [chef-cookbooks/docker#735]
A proper docker installation on e.g. Debian and Ubuntu needs more work then just the installation of a package, because the linux kernel is by default not loaded with cgroup memory accounting:

https://github.com/docker/docker/issues/396#issuecomment-179470044
https://github.com/docker/docker/issues/18420

The steps are documented in the Docker manual for ubuntu:
https://docs.docker.com/engine/installation/linux/ubuntulinux/#/adjust-memory-and-swap-accounting

**Comment by someara** [comment]
Hi. As stated in the "Scope" section at the top of the README, this is out of scope for this cookbook.
