### ISSUE TITLE
Systemd: invalid /etc/systemd/system/docker.socket generated

### ISSUE THREAD

**Issue by drazzib** [chef-cookbooks/docker#737]
### Cookbook version
docker cookbook 2.9.5

### Chef-client version
Chef Zero 12.13.37

### Platform Details
Debian Jessie 8 (under systemd init)

### Scenario:
Trying to setup docker daemon using deb package + systemd
failing because of invalid systemd configuration generated
```
systemctl restart docker
Failed to restart docker.service: Unit docker.socket failed to load: Invalid argument. See system logs and 'systemctl status docker.socket' for details.
```

### Steps to Reproduce:
Here is my code in my wrapper cookbook :
```
include_recipe "apt-docker"

docker_installation_package 'default' do
  package_version DnDockerHelper.to_package_version(node)
  action :create
end

docker_service_manager_systemd 'default' do
  host ["unix:///var/run/docker.sock", "tcp://0.0.0.0:2375"]
  graph "/home/docker"
  iptables false
  ipv4_forward true
  ipv6_forward true
  action :start
end
```

### Expected Result:
/etc/systemd/system/docker.socket should contains
```
ListenStream=/var/run/docker.sock
```

### Actual Result:
/etc/systemd/system/docker.socket should contains
```
ListenStream=
```
because it seems that `templates/default/systemd/docker.socket-override.erb` expect a docker_socket variable which is **not provided** in `libraries/docker_service_manager_systemd.rb`

**Comment by chasebolt** [comment]
resolved in v2.9.6
