### ISSUE TITLE
Recipe Compile Error when using clief-client in whyrun mode

### ISSUE THREAD

**Issue by jessemcdowell-AI** [chef-cookbooks/docker#738]
### Cookbook version

2.9.2
### Chef-client version

12.12.15 and 12.13.37
### Platform Details

Ubuntu 14.04 x86 on AWS EC2
### Scenario:

on a node: `sudo chef-client -W`
### Steps to Reproduce:
1. create a recipe in a cookbook that uses the `docker_service` resource with `action [:create, :start]`
2. add the cookbook to the run list for a node
3. from that node: `sudo chef-client -W`
### Expected Result:

Chef client runs, and reports that it will install Docker
### Actual Result:

```
================================================================================
Recipe Compile Error in /var/chef/cache/cookbooks/docker/libraries/docker_container.rb
================================================================================

LoadError
---------
cannot load such file -- docker

Cookbook Trace:
---------------
  /var/chef/cache/cookbooks/docker/libraries/docker_container.rb:3:in `<class:DockerContainer>'
  /var/chef/cache/cookbooks/docker/libraries/docker_container.rb:2:in `<module:DockerCookbook>'
  /var/chef/cache/cookbooks/docker/libraries/docker_container.rb:1:in `<top (required)>'

Relevant File Content:
----------------------
/var/chef/cache/cookbooks/docker/libraries/docker_container.rb:

  1:  module DockerCookbook
  2:    class DockerContainer < DockerBase
  3>>     require 'docker'
  4:      require 'shellwords'
  5:      require_relative 'helpers_container'
  6:  
  7:      include DockerHelpers::Container
  8:  
  9:      resource_name :docker_container
 10:  
 11:      ###########################################################
 12:      # In Chef 12.5 and later, we no longer have to use separate

Platform:
---------
x86_64-linux
```

**Comment by chasebolt** [comment]
i dont see anyway around this. chef-client wont install the required gem
since you are in whyrun mode. you'd need to install it manually.

**Comment by shortdudey123** [comment]
Looks like this also causes issues loading the cookbook inside a CI environment

Cookbook version
2.9.6

**Comment by sean-kang** [comment]
I am seeing the same error while running unit tests using ChefSpec in our CI environment. Tested with docker cookbook 2.9.6.

**Comment by sean-kang** [comment]
Setting up the following gem resolved the problem in our CI environment.

gem 'docker-api', '= 1.31.0'

**Comment by someara** [comment]
As Chasbolt mentioned, There's no way around this one. This issue is more of a general Chef issue that a Docker Cookbooks one.

You'll run into this with *any* cookbook that requires a gem to be added to Chef to function. The Etcd cookbook is going to behave the same way.

The only way around this is to make sure you've installed docker-api into your Chef's environment with `/opt/chef/embedded/bin/gem install docker-api`

-s
