### ISSUE TITLE
Variable being reset in docker_container

### ISSUE THREAD

**Issue by butterhc** [chef-cookbooks/docker#740]
### Cookbook version

v2.6.8
### Chef-client version

Chef: 12.6.0
### Platform Details

rhel 7.1 aws instance running centos6.8 docker base image
### Scenario:

I would expect the vols variable to not change value after a docker_container resource is run/compiled.
  log "vols: #{vols}"
  # Execute docker container for the microservice
  docker_container microservice_name do
    detach true
    open_stdin true
    tty true
    hostname container_hn
    container_name microservice_name
    image image_uri
    env env_vars
    binds vols
    command "bash -c \"cd /root&&./startKafkaWorker.sh||true&&tail -F /root/kafkaWorker.log\""
    restart_policy 'always'
    restart_maximum_retry_count 20
    log_opts ['max-size=30m', 'max-file=10']
  end
  log "vols: #{vols}"

----------Chef client run-----------------
- log[vols: ["/dirs:/dirs"]] action write[2016-08-22T21:37:18+00:00] INFO: Processing log[vols: ["/dirs:/dirs"]] action write (bds::microservice line 61)
  [2016-08-22T21:37:18+00:00] INFO: vols: ["/dirs:/dirs"]
  - docker_container[label-microservice] action run[2016-08-22T21:37:18+00:00] INFO: Processing docker_container[label-microservice] action run (bds::microservice line 64)
    - create label-microservice
    -   set container_name              to "label-microservice"
    -   set repo                        to "127.0.0.1:5000/dev_u/jre8_11.3.4-snapshot"
    -   set tag                         to "latest"
    -   set command                     to "bash -c \"cd /root&&./startKafkaWorker.sh||true&&tail -F /root/kafkaWorker.log\""
    -   set cap_add                     to nil (default value)
    -   set cap_drop                    to nil (default value)
    -   set cgroup_parent               to "" (default value)
    -   set cpu_shares                  to 0 (default value)
    -   set cpuset_cpus                 to "" (default value)
    -   set devices                     to [](default value)
    -   set dns                         to [](default value)
    -   set dns_search                  to [](default value)
    -   set domain_name                 to "" (default value)
    -   set entrypoint                  to nil (default value)
    -   set env                         to ["ENV_PROPS_DIR=/dirs/dev02u/data/stat/common/environment/", "JKS=/dirs/dev02u/data/stat/common/certs/cacerts.jks", "JKS_PW=changeit"]
    -   set extra_hosts                 to nil (default value)
    -   set exposed_ports               to {} (default value)
    -   set hostname                    to "label-microservice-1.node.consul"
    -   set ipc_mode                    to "" (default value)
    -   set labels                      to {} (default value)
    -   set links                       to nil (default value)
    -   set mac_address                 to nil (default value)
    -   set memory                      to 0 (default value)
    -   set memory_swap                 to 0 (default value)
    -   set network_disabled            to false (default value)
    -   set network_mode                to "default"
    -   set outfile                     to nil (default value)
    -   set port_bindings               to {} (default value)
    -   set pid_mode                    to "" (default value)
    -   set privileged                  to false (default value)
    -   set publish_all_ports           to false (default value)
    -   set remove_volumes              to false (default value)
    -   set restart_maximum_retry_count to 20
    -   set restart_policy              to "always"
    -   set security_opts               to nil (default value)
    -   set signal                      to "SIGTERM" (default value)
    -   set tty                         to true
    -   set ulimits                     to nil (default value)
    -   set user                        to "" (default value)
    -   set volumes                     to {}
    -   set volumes_from                to nil (default value)
    -   set working_dir                 to "" (default value)
    -   set volumes_binds               to ["/dirs:/dirs"]
    - starting label-microservice
  - log[vols: []] action write[2016-08-22T21:37:19+00:00] INFO: Processing log[vols: []] action write (bds::microservice line 78)
    [2016-08-22T21:37:19+00:00] INFO: vols: []
### Steps to Reproduce:

Create recipe with docker_container.  Run recipe.
### Expected Result:

I expect that the vols variable would be populated and available for the next operation.
### Actual Result:

The vols variable is set to null after the docker_container resource is run.

**Comment by someara** [comment]
Hi.

This one is a head scratcher. It's confusing because "Chef does not work that way".

There is a compilation phase, where "#{vol}" is interpolated, and a resource is placed into an array called a `resource_collection`. 

At this point the vol varibale is done and will not be interpolated again. The `log[some_title]` resource will already have its values pre-set before the `docker_container[some_title]` resource ever runs.

From your pasted output, I suspect that you have two identicaly named `log[whatever]` resources in your recipe on either side of of the `docker_container` resource. This is probably generating a resource cloning warning as well as confusion.

I'd suggest writing a ChefSpec for this and throwing in some `require 'pry' ; binding.pry` lines and taking a look around.

Good luck!

-s
