### ISSUE TITLE
wait_running_state hard limit 20s

### ISSUE THREAD

**Issue by rmoriz** [chef-cookbooks/docker#749]
Can we make this retry-value configurable, please?

``` ruby
def wait_running_state(v)
        tries = 20
        tries.times do
          return if state['Running'] == v
          sleep 1
        end
…
```

https://github.com/chef-cookbooks/docker/blob/7c3e166a9ff6a208e9462eb178766865998bfc38/libraries/helpers_container.rb#L79-L83

**Comment by someara** [comment]
I don't see why not

**Comment by someara** [comment]
Here you go. f9bca5e0c00103c0ce0308e3f039f54be6287312
