### ISSUE TITLE
Add --cap-add and --cap-drop please

### ISSUE THREAD

**Issue by dennybaa** [chef-cookbooks/docker#751]
#317 is closed  more than year ago, but still nothing :(

cc: @someara

**Comment by someara** [comment]
Is this not working?

https://github.com/chef-cookbooks/docker/blob/master/libraries/docker_container.rb#L76

**Comment by dennybaa** [comment]
@someara Hey, I'm not sure. I think `--security-opt` might probably work, I guess smth went wrong that day I created issue)
I will rename the ticket because what I actually meant was `--cap-add` and `--cap-drop` .

**Comment by someara** [comment]
Those exist as well.

https://github.com/chef-cookbooks/docker/blob/9e073f3795587c48053869f83148399878bd680f/libraries/docker_container.rb#L39-L40

**Comment by dennybaa** [comment]
Well thank you Sean, I don't remember exact thing, just remember that privileges didn't work for me that time. However I can't check this now. Thanks @someara and this can resolved then.
