### ISSUE TITLE
What property we need to use to pass --volume-driver=nfs to the docker run

### ISSUE THREAD

**Issue by vamsivv** [chef-cookbooks/docker#753]
### Cookbook version

i think its 2.5.9
### Chef-client version

12.4.1
### Platform Details

AWS Amazon linux
### Scenario:

I'm trying to set --volume-driver=nfs to docker run. I can able to pass hostname,volumes,env,etc. Please help to pass nfs to the volume which i'm gonna mount it in container. I believe there should be property in our cookbook, kindly let me know what property i have to use?
### Steps to Reproduce:

I would like to what property we need to use to pass value for --volume-driver=nfs
### Expected Result:

Please help me soon and let me know if any info is missed
### Actual Result:

I'm able to pass all other properties to docker run.

**Comment by chasebolt** [comment]
added in 088f636

**Comment by chasebolt** [comment]
released in v2.13.6
