### ISSUE TITLE
MountFlags=private can not be configured

### ISSUE THREAD

**Issue by Lifang13** [chef-cookbooks/docker#756]
can MountFlags be allowed to be configurable

**Comment by dy-dx** [comment]
Or, the MountFlags line should be removed as has been done upstream: https://github.com/docker/docker/commit/2aee081cad72352f8b0c37ba0414ebc925b022e8#diff-ff907ce70a8c7e795bde1de91be6fa68

In the meantime I have done this: https://github.com/dy-dx/docker/commit/33f615a81c3da0c02673d5f457164be874dcd856

**Comment by someara** [comment]
Fixed up in v2.11.0
