### ISSUE TITLE
uninitialized constant DockerCookbook::ChefCompat in compile phase

### ISSUE THREAD

**Issue by michaelshobbs** [chef-cookbooks/docker#757]
### Cookbook version

2.9.6
### Chef-client version

[2016-10-01T21:00:32+00:00] INFO: **\* Chef 12.13.37 ***
### Platform Details

Ubuntu 14.04 on AWS OpsWorks
### Scenario:

Attempting to pull an image
### Steps to Reproduce:

NOTE: I never get close to this point as chef fails in compile

```
  docker_image 'gliderlabs/herokuish:latest' do
    action :pull
  end
```
### Expected Result:

I expect the image be pulled
### Actual Result:

```
NameError
---------
uninitialized constant DockerCookbook::ChefCompat

Cookbook Trace:
---------------
  /var/chef/runs/93c76751-df40-4221-b8fc-1852cd5eb771/local-mode-cache/cache/cookbooks/docker/libraries/docker_base.rb:2:in `<module:DockerCookbook>'
  /var/chef/runs/93c76751-df40-4221-b8fc-1852cd5eb771/local-mode-cache/cache/cookbooks/docker/libraries/docker_base.rb:1:in `<top (required)>'

Relevant File Content:
----------------------
/var/chef/runs/93c76751-df40-4221-b8fc-1852cd5eb771/local-mode-cache/cache/cookbooks/docker/libraries/docker_base.rb:

  1:  module DockerCookbook
  2>>   class DockerBase < ChefCompat::Resource
  3:      require_relative 'helpers_auth'
  4:      require_relative 'helpers_base'
  5:
  6:      include DockerHelpers::Base
  7:
  8:      #########
  9:      # Classes
 10:      #########
 11:

Platform:
---------
x86_64-linux
```

I'm sure I'm doing something silly but after a few hours of googling and trying some stuff out, I'm asking for help. 😄

**Comment by michaelshobbs** [comment]
Seems like this was an issue at some point: https://travis-ci.org/chef-cookbooks/docker/builds/158755041

**Comment by tas50** [comment]
This should be fixed in the current release. We made changes here and also required the latest compat_resource cookbook.

**Comment by michaelshobbs** [comment]
I'll check it out. Thank!
