### ISSUE TITLE
Upgrading using `docker_installation_tarball` doesn't replace binary file

### ISSUE THREAD

**Issue by eyalzek** [chef-cookbooks/docker#764]
### Cookbook version
2.9.7

### Chef-client version
12.8.1

### Platform Details
Ubuntu 14.04

### Scenario:
Trying to upgrade docker `v1.8.3` that was installed using `v2.6.1` of this cookbook with `docker_installation_binary`:

```
docker_installation_binary 'default' do
  version '1.8.3'
  checksum '...'
  action :create
end
```

Since docker `v.1.12.3` is not available as binary, I tried installing it using a tarball:

```
docker_installation_tarball 'default' do
  version '1.12.3'
  checksum '...'
  action :create
end
```

this is the output I see when converging:

```
         * docker_installation_tarball[default] action create
           * remote_file[/tmp/kitchen/cache/docker-1.12.3.tgz] action create
             - create new file /tmp/kitchen/cache/docker-1.12.3.tgz
             - update content in file /tmp/kitchen/cache/docker-1.12.3.tgz from none to 626601
             (file sizes exceed 10000000 bytes, diff output suppressed)
             - change mode from '' to '0755'
             - change owner from '' to 'root'
             - change group from '' to 'root'
           * execute[extract tarball] action run (up to date)
           * execute[extract tarball] action nothing (skipped due to action :nothing)
```

Logging in to the container and running `docker --version` returns `1.8.3`... It seems like if the binary file already exists in `/usr/bin/docker` then it doesn't replace it. Or am I doing something wrong?

**Comment by someara** [comment]
Yea. There's no way for the tarball resource to know that it needs to repair. You'll have to go around and manually nuke the binary.

The `installation_binary` and `installation_tarball` resources should only be used for quick testing scenarios. Docker is now dynamically linked against variou system libs.

 I'd strongly suggest using the `installation_package` resource.

**Comment by someara** [comment]
Closing this because there's not really anything that can be done. Sorry.
