### ISSUE TITLE
Problems with guard clauses (again)

### ISSUE THREAD

**Issue by alappe** [chef-cookbooks/docker#770]
### Cookbook version

I tested `2.9.7` (what we're mostly using) and `2.9.8` if something changed recently.

### Chef-client version

I tested `12.5.1` (what we're mostly using) and `12.15.19` just to see if my older version is the source of the problem.

### Platform Details

Ubuntu 14.04.5 LTS

### Scenario:

I'm having trouble with guard clauses for the docker resources again. Depending on the host fqdn, I want to add some proxy options to the docker parameter. To simplify I reduced the example to a very simple guard clause, but it's not working – the first resource is executed, not the latter.

### Steps to Reproduce:

```
  1 docker_service 'default' do
  2  action [:create, :start]
  3  http_proxy 'something special'
  4  https_proxy 'something special'
  5  only_if { false }
  6 end
  7
  8 docker_service 'default' do
  9   action [:create, :start]
 10   not_if { false }
 11 end
```

I also added a [repo](https://github.com/alappe/chef-docker-guards) to simplify testing, but it requires `vagrant`, two vagrant plugins `vagrant-berkshelf` & `vagrant-omnibus` and of course `virtualbox`. So it might not be easier for everybody…

### Expected Result:

Because the first `only_if { false }` is `false`, the resource is *not* executed. The second one is. So `/etc/default/docker` should *not* have the proxy entries.

### Actual Result:

It does have the proxy entries.

### Disclaimer

Maybe I'm missing something massively obvious, but I cannot see it, neither can the `#chef` channel on irc when I tried, so I'm hoping you can…

I had similar problems in #676 and believed it to be a different problem, but I found no solution and as you see, I still have similar issues.

**Comment by someara** [comment]
Hi there.

This is one of those classic subtle "Chef things".

You have two resources named 'docker_service[default]' in the same resource collection.
What's you're hitting the Chef-3694 resource cloning behavior. 

Give the `docker_service` resources unique names and it'll work as expected.

It might be easier to think about it with the `file` resource instead.

```ruby
file '/file-one' do  
  content 'one'
  action :create
  only_if { false }
end

file '/file-one' do
  content 'two'  
  action :create
  not_if { false }
end
```

^ there you'd want to change "file-one" to "file-two".

Closing this issue because there's nothing to do. Feel free to make comments here.

-s

**Comment by alappe** [comment]
Thank you @someara! Helped a lot…
