### ISSUE TITLE
Incompatibility with systemd cookbook

### ISSUE THREAD

**Issue by pd** [chef-cookbooks/docker#772]
### Cookbook version
2.9.9

### Chef-client version
12.16.42

### Platform Details
Centos 7.2.

### Scenario:
After fa654963a, `docker_service_manager_systemd` will fail in any environment where the [systemd](https://github.com/nathwill/chef-systemd) cookbook is also in use. The helper [systemd_conf](https://github.com/chef-cookbooks/docker/blob/fa654963/libraries/helpers_service.rb#L165) conflicts with the name of a [resource in the systemd cookbook](https://github.com/nathwill/chef-systemd/blob/184ec7e/libraries/conf.rb#L31), and for whatever reason, the resource method is taking precedence during method dispatch.

### Steps to Reproduce:
Add `recipe[systemd]` to any of the systemd kitchen tests, then try to converge.

### Expected Result:
The `docker_service_manager_systemd` succeeds as it did on 2.9.8.

### Actual Result:

```
* docker_service_manager_systemd[default] action start

  ================================================================================
  Error executing action `start` on resource 'docker_service_manager_systemd[default]'
  ================================================================================

  ArgumentError
  -------------
  You must supply a name when declaring a systemd_conf resource

  Cookbook Trace:
  ---------------
  /tmp/kitchen/cache/cookbooks/docker/libraries/docker_service_manager_systemd.rb:61:in `block (2 levels) in <class:DockerServiceManagerSystemd>'
  /tmp/kitchen/cache/cookbooks/docker/libraries/docker_service_manager_systemd.rb:53:in `block in <class:DockerServiceManagerSystemd>'

  Resource Declaration:
  ---------------------
  # In /tmp/kitchen/cache/cookbooks/docker_test/recipes/service_systemd.rb

    7: docker_service_manager_systemd 'default' do
    8:   host 'unix:///var/run/docker.sock'
    9:   action :start
   10: end
   11:
```

### Fix

Easiest tactic is to just rename the method, `docker_systemd_conf`. Debugging method dispatch surprises probably isn't worth it ...

**Comment by chasebolt** [comment]
thanks for the info! i have renamed `systemd_conf` to `systemd_args` and pushed out release v2.9.10. hopefully this resolves it for you!

**Comment by pd** [comment]
Yup, b94f1a9 did the trick. Thanks much!
