### ISSUE TITLE
Docker node state (Ohai/Attributes/Handler?)

### ISSUE THREAD

**Issue by rmoriz** [chef-cookbooks/docker#776]
This cookbook makes it very easy to deploy docker, build images and run containers. 

However in ambitious setups you may want to collect information about running containers/used images. Using chef, a good location seems to be attributes/properties that will be stored on the chef-server and be available for search.

- Ohai, as far as I can see, does not collect information about running containers out of the box. I could write a custom ohai plugin but it would also require a (manually timed) ohai reload after the last docker-related resource to update the changed attributes. 

- The resources provided by this cookbook could add those information to the node object.

What do you suggest?

**Comment by someara** [comment]
I suggest using the docker-api gem to inspect the Docker API to get this kind of information in real time.
