### ISSUE TITLE
Version 1.11.2-1.fc24 of docker not found. Did you specify both version and release? (version-release, e.g. 1.84-10.fc6)

### ISSUE THREAD

**Issue by brianjmurrell** [chef-cookbooks/docker#781]
### Cookbook version
2.13.0

### Chef-client version
12.5.1

### Platform Details
Fedora 24

### Scenario:
Trying to install the distro provided "docker" package

### Steps to Reproduce:
```ruby
    docker_installation_package 'default' do
      package_name 'docker'
      action :create
    end
```
### Expected Result:
Install whatever version of docker is shipping with Fedora 24

### Actual Result:
```
  * docker_installation_package[default] action create
    * yum_package[docker] action install
                                                                                                                                                                            ================================================================================                                                                                      Error executing action `install` on resource 'yum_package[docker]'
      ================================================================================
      
      Chef::Exceptions::Package
      -------------------------
      Version 1.11.2-1.fc24 of docker not found. Did you specify both version and release? (version-release, e.g. 1.84-10.fc6)
      
      Cookbook Trace:
      ---------------
      /root/chef/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'
      /root/chef/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:125:in `compile_and_converge_action'
      /root/chef/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'
```

**Comment by chasebolt** [comment]
You need to specify package_version that matches the package you are trying
to install

**Comment by brianjmurrell** [comment]
On Thu, 2016-12-01 at 13:48 -0800, Chase Bolt wrote:
> You need to specify package_version that matches the package you are
> trying
> to install

Well, I actually did try doing that and it still failed.

But in reality, I don't want to specify a version such that I have to
keep updating my recipe every time RH puts out an update.  I just want
to install whatever version is current the way a chef package resource
does.

**Comment by someara** [comment]
https://github.com/chef/chef/issues/4103

**Comment by someara** [comment]
Hi. Unfortunately, you'll have to specify the version until chef/chef#4103 is addressed.
Closing here because there's nothing to do.

-s
