### ISSUE TITLE
docker-compose support

### ISSUE THREAD

**Issue by EugenMayer** [chef-cookbooks/docker#784]
Since this cookbook literally provides anything one could wish, i ask myself, if there is a reason why no docker-compose support has been added.

Surely there is a cookbook for that https://supermarket.chef.io/cookbooks/docker_compose - but in regards of the importance of docker, i thought this would be something for the official docker cookbook.

Are there any design decisions behind that - e.g. you want the implementor to rather create customer networks, create containers using recipes also, and them bind this all together - recipe based, instead of using docker-compose?

I could potentially see and idea behind that , the problem is, the portability. And sometimes docker-compose files are not as simple as listing some services and thats it, they can become pretty complex and one would not really like to see it duplicated.

Would really look forward to have some input from you on that topic.

**Comment by someara** [comment]
The resources in this cookbook effectively make Chef an alternative to docker compose.

A recipe and a compose file literally do the same thing - They let you describe a list of containers, and then speaks directly to the Docker Remote API to make any changes between runs. You can speak to remote docker hosts with the "host" property.

Being in Chef gives you a level of dynamism not available in compose. You can calculate values and feed them into container definitions.

Is there something you can do in a compose file you can't accomplish with this cookbook?

-s

**Comment by EugenMayer** [comment]
After thinking about this for a while i would say, i would never go with chefs way of defining the services, since you cannot ssh on the box and run things like ```docker-compose servicename stop``` ```docker-compose servicename up``` and other things to maintain the running services, inspect things and so on.

docker-compose is a cli tool for the runtime, but chef-client / cookbooks are only for the initial setup. That said, docker-compose wins the raise here - by far. It does autosetup networks, it can handle dependencies (depends_on), it can handle links (rename/map services) and much more.

So if you ask me, doing compose for the containers is a must, also for this cookbook

**Comment by bflad** [comment]
My personal opinion is that `docker` and `docker-compose` have a separation of concerns (installation methods, configuration, running service vs not, etc) and therefore should remain in separate Chef cookbooks. I don't see too many benefits to including it here when the other public cookbook exists. For what its worth, I use the `docker_compose` cookbook in my environment.

**Comment by EugenMayer** [comment]
@bflad i would second you on that in terms this cookbook is more CM, docker-compose is more AM ( application management ). But there is an intersection already (registry authentication) and in addition, be it here, or in an extra cookbook, i would love to see chef kicking in for that, not some random probably maintained cookbook by someone else. There are already a few, one on supermarket and a couple on github, but docker - i think - is way too important to be put into this hands. (IMHO)

**Comment by bflad** [comment]
Having watched the Chef community over the last 5 years (wow has it been that long for me?!), I will say that the community will do what it needs to do to ensure there's a well maintained cookbook if the need is there.

If you goto the very first commits of this cookbook, it used to be solely maintained by in your words, some random probably maintained cookbook by someone else, me (I was never employed by Chef), but when I moved jobs and couldn't properly maintain this myself they graciously extended the helping hand. Shout out to the other maintainers!

Honestly, I wouldn't worry about to much about it living in a separate cookbook. I think the community thrives on the fact that we all get to contribute in our own ways. If there are bits that are necessary to better wire the two cookbooks together, maybe we should discuss those specifically.

**Comment by EugenMayer** [comment]
@bflad well i am with chef for a while now also, but not too active in the past. And i would not really tend to join you, or lets say, it depends or maybe it changed. Back in the days, pre github-era, cookbooks tend to be islands. Maybe this changed and i need to adept my POV.

On the other hand, chef competes agains ansible and they made a clever move towards docker getting a lot of attention. Chef should consider this also a market-strategy at some point. But again, that is my POV.

Really nice input on that @bflad , very valuable! Thank you

**Comment by someara** [comment]
Closing this here for now...

**Comment by EugenMayer** [comment]
@someara so no docker-compose support to be expected, right?

**Comment by someara** [comment]
Correct
