### ISSUE TITLE
documentation typo for docker_volume

### ISSUE THREAD

**Issue by EugenMayer** [chef-cookbooks/docker#785]
![image](https://cloud.githubusercontent.com/assets/136934/21013814/abd4a7c2-bd5b-11e6-9beb-d9b062694f0a.png)

a typo in the section docker_volume under actions, shall not be create a network but rather create a volume

**Comment by someara** [comment]
Thanks for pointing that out!

FIxed up in 3040f1d0b843929cfb1225b8a4686f932c20169f
