### ISSUE TITLE
Remove support for EOL docker versions

### ISSUE THREAD

**Issue by tas50** [chef-cookbooks/docker#788]
Let's nuke some code. Docker 1.6 - 1.8 are no longer supported.

**Comment by CVTJNII** [comment]
Where is this documented from upstream?  I'm searching but not finding.  I'm stuck on 1.8 because of https://github.com/docker/docker/issues/19758 so this caught my attention.

**Comment by tas50** [comment]
https://success.docker.com/Policies/Maintenance_Lifecycle

**Comment by someara** [comment]
I've been removing old versions from the test harness... the actual code impact is extremely minimal.

It's going to be things like shasums for binary installation helpers and odd blips like this:

https://github.com/chef-cookbooks/docker/blob/b0b0d79df3835da57fbf38764d0975c8c7190855/libraries/helpers_container.rb#L61

I'd probably just leave that stuff in.

-s

**Comment by tas50** [comment]
the main part was the testing so I'm fine with this.
