### ISSUE TITLE
Docker fails to start on Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by orarnon** [chef-cookbooks/docker#790]
### Cookbook version
'docker', '~> 2.0'

### Chef-client version
12.17.44

### Platform Details
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty

### Scenario:
Trying to install and start a simple Docker service - no special config

### Steps to Reproduce:
Have an Ubuntu 14.04 EC2 instance and run a recipe with: 
docker_service 'default' do
  action [:create, :start]
end

### Expected Result:
Docker service installed and started

### Actual Result:
* docker_service[default] action restart
    * docker_service_manager_upstart[default] action restart
      * service[docker] action stop (up to date)
      * template[/etc/init/docker.conf] action create (up to date)
      * file[/etc/docker-firstconverge] action create (up to date)
      * service[docker] action start

        ================================================================================
        Error executing action `start` on resource 'service[docker]'
        ================================================================================

        Mixlib::ShellOut::ShellCommandFailed
        ------------------------------------
        Expected process to exit with [0], but received '1'
        ---- Begin output of /sbin/start docker ----
        STDOUT:
        STDERR: start: Job failed to start
        ---- End output of /sbin/start docker ----
        Ran /sbin/start docker returned 1

        Cookbook Trace:
        ---------------
        /var/chef/cache/cookbooks/docker/libraries/docker_service_manager_upstart.rb:46:in `block in <class:DockerServiceManagerUpstart>'

        Resource Declaration:
        ---------------------
        # In /var/chef/cache/cookbooks/docker/libraries/docker_service_manager_upstart.rb

         29:       service 'docker' do
         30:         provider Chef::Provider::Service::Upstart
         31:         supports status: true
         32:         action :start
         33:       end
         34:     end

        Compiled Resource:
        ------------------
        # Declared in /var/chef/cache/cookbooks/docker/libraries/docker_service_manager_upstart.rb:29:in `block in <class:DockerServiceManagerUpstart>'

        service("docker") do
          provider Chef::Provider::Service::Upstart
          action [:start]
          supports {:status=>true}
          retries 0
          retry_delay 2
          default_guard_interpreter :default
          service_name "docker"
          pattern "docker"
          declared_type :service
          cookbook_name "is-tagMediation"
        end

        Platform:
        ---------
        x86_64-linux

      ================================================================================
      Error executing action `restart` on resource 'docker_service_manager_upstart[default]'
      ================================================================================

      Mixlib::ShellOut::ShellCommandFailed
      ------------------------------------
      service[docker] (/var/chef/cache/cookbooks/docker/libraries/docker_service_manager_upstart.rb line 29) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
      ---- Begin output of /sbin/start docker ----
      STDOUT:
      STDERR: start: Job failed to start
      ---- End output of /sbin/start docker ----
      Ran /sbin/start docker returned 1

      Cookbook Trace:
      ---------------
      /var/chef/cache/cookbooks/docker/libraries/docker_service_manager_upstart.rb:46:in `block in <class:DockerServiceManagerUpstart>'

      Resource Declaration:
      ---------------------
      # In /var/chef/cache/cookbooks/docker/libraries/docker_service.rb

       64:           svc = docker_service_manager(name, &block)
       65:         when 'execute'
       66:           svc = docker_service_manager_execute(name, &block)
       67:         when 'sysvinit'
       68:           svc = docker_service_manager_sysvinit(name, &block)
       69:         when 'upstart'
       70:           svc = docker_service_manager_upstart(name, &block)
       71:         when 'systemd'
       72:           svc = docker_service_manager_systemd(name, &block)
       73:         end
       74:         copy_properties_to(svc)
       75:         svc
       76:       end
       77:     end
       78:
       79:     #########
       80:     # Actions
       81:     #########
       82:
       83:     action :create do
       84:       installation do
       85:         action :create
       86:         notifies :restart, new_resource
       87:       end
       88:     end
       89:
       90:     action :delete do
       91:       installation do
       92:         action :delete
       93:       end
       94:     end
       95:
       96:     action :start do
       97:       svc_manager do
       98:         action :start
       99:       end
      100:     end
      101:
      102:     action :stop do
      103:       svc_manager do
      104:         action :stop
      105:       end
      106:     end
      107:
      108:     action :restart do
      109:       svc_manager do
      110:         action :restart
      111:       end
      112:     end
      113:   end
      114: end

      Compiled Resource:
      ------------------
      # Declared in /var/chef/cache/cookbooks/docker/libraries/docker_service.rb:64:in `svc_manager'

      docker_service_manager_upstart("default") do
        action [:restart]
        retries 0
        retry_delay 2
        default_guard_interpreter :default
        declared_type :docker_service_manager
        cookbook_name "is-tagMediation"
        pidfile "/var/run/docker.pid"
        logfile "/var/log/docker.log"
      end

      Platform:
      ---------
      x86_64-linux

    ================================================================================
    Error executing action `restart` on resource 'docker_service[default]'
    ================================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    docker_service_manager_upstart[default] (/var/chef/cache/cookbooks/docker/libraries/docker_service.rb line 64) had an error: Mixlib::ShellOut::ShellCommandFailed: service[docker] (/var/chef/cache/cookbooks/docker/libraries/docker_service_manager_upstart.rb line 29) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
    ---- Begin output of /sbin/start docker ----
    STDOUT:
    STDERR: start: Job failed to start
    ---- End output of /sbin/start docker ----
    Ran /sbin/start docker returned 1

    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/docker/libraries/docker_service_manager_upstart.rb:46:in `block in <class:DockerServiceManagerUpstart>'

    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/is-tagMediation/recipes/default.rb

     12: docker_service 'default' do
     13:   action [:create, :start]
     14: end

    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/is-tagMediation/recipes/default.rb:12:in `from_file'

    docker_service("default") do
      action [:create, :start]
      updated true
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :docker_service
      cookbook_name "is-tagMediation"
      recipe_name "default"
      install_method "auto"
      service_manager "auto"
    end

    Platform:
    ---------
    x86_64-linux

  * service[sensu-client] action restart
    - restart service service[sensu-client]

**Comment by someara** [comment]
I just spot checked the `auto-ubuntu-1404` test-kitchen suite and it's working fine there...

https://gist.github.com/someara/65a26d3218230c884cfb1fae4fef29ab

What does /var/log/docker.log say?

-s

**Comment by orarnon** [comment]
It's empty actually.

**Comment by someara** [comment]
Can you try cookbook v2.13.2?

**Comment by orarnon** [comment]
Yes it does! Thanks
I can't figure out how it worked up until now with Ubuntu 14.04

**Comment by prein** [comment]
I've experience identical issue today and can confirm that downgrading the cookbook to 2.13.2 helped. Thanks.

**Comment by someara** [comment]
What version of chef-client? 

I'm pretty sure the upstart provider was busted for a while.

-s
