### ISSUE TITLE
Missing argument to start docker daemon via init

### ISSUE THREAD

**Issue by sepek** [chef-cookbooks/docker#792]
### Cookbook version
2.13.2

### Chef-client version
12.13.37-1

### Platform Details
ubuntu 16.04 (xenial)

### Docker version 
1.11.2-0~xenial

### Scenario:
Try to start docker 1.11.2 via cookbook but fails

### Steps to Reproduce:
deploy docker 1.11 via cookbook

### Expected Result:
systemctl status docker should report up and running

### Actual Result:
journctl gives the help output of docker

### source:
docker modifies the systemd unit file and drops the "daemon" parameter
commit 1be2feea21786e63afc28c400feda55dfef9f7ec

**Comment by someara** [comment]
Is this really systemd specific or is it just the wrong CLI args for the docker engine version

**Comment by sepek** [comment]
Actually for starting a docker daemon it is the wrong CLI arg.

I tried to upgrade to 1.12 too which is broken too => 07decaa5a4a923e28fa0c864fdb881f8918a2402

**Comment by someara** [comment]
Revered and released as 2.13.3

**Comment by smgt** [comment]
Wow, didn't even hive time to finish my comment before this was fixed.

**Comment by sepek** [comment]
Thanks!
