### ISSUE TITLE
Not pulling image updates from private registries.

### ISSUE THREAD

**Issue by neclimdul** [chef-cookbooks/docker#796]
### Cookbook version
2.13.9

### Chef-client version
12.12.15

### Platform Details
Ubuntu 16.04.1
Docker: 1.12.5
Private repository hosted in gitlab

### Scenario:
Deploy an updated image.

### Steps to Reproduce:
Here's a simplified version of my recipe.
```ruby
include_recipe 'chef-vault'
registry = 'mygitlab.example.com:5005'

docker_service 'default' do
  action [:create, :start]
end

login = chef_vault_item('data_bag', 'data_bag_item')
docker_registry registry do
  username login['username']
  password login['password']
end

image = "#{registry}/group/projectname"
docker_image image do
  tag 'latest'
  action :pull
  notifies :redeploy, 'docker_container[imageContainer]'
end
docker_container 'imageContainer' do
  repo image
  tag 'latest'
  restart_policy 'always'
  action :run_if_missing
end
```

### Expected Result:
continuously deploys updated images.

### Actual Result:
It seems to be stuck on old images. Container has to be killed and image deleted then chef will pull and deploy a new image.

Images like `nginx` or `redis` from the dockerhub registry seem to be deploying fine.

**Comment by chasebolt** [comment]
i dont believe this is a chef issue. i think this is actually a docker issue. underlying code for chef docker actually does a `docker pull "#{repo}:#{tag}"` on every chef run. then it compares the original image id with the new pulled image id, if they dont match you get the pretty green text saying a new image was pulled. if they do match then the image we pulled and the image we originally had were the same.

here is the bit of code if you want to check it out. https://github.com/chef-cookbooks/docker/blob/master/libraries/helpers_image.rb#L65-L75

if you want to debug further you can run this https://gist.github.com/chasebolt/3e58bc05203a6fcf5d71 in a separate window, then run `chef-client`. it will dump all the docker http calls.

**Comment by neclimdul** [comment]
Useful! After weeks of not working and giving up and posting this, I continued poking and it broke worse complaining about the image not existing then magically started working. Unfortunately I'm not sure what happened to fix it because I set everything back just the way it was and it still works.

If I'm able to get it broken again I'll use that to post some deeper details.
