### ISSUE TITLE
docker_install_package provider no longer works with Ubuntu 14.04

### ISSUE THREAD

**Issue by jeffb-stell** [chef-cookbooks/docker#797]
### Cookbook version
2.13.5 - 2.13.9

### Chef-client version
12.10.24

### Platform Details
AWS, Ubuntu 14.04, Docker Enginer 1.11.2

### Scenario:
Install and use docker service

### Steps to Reproduce:
Install docker 1.11.2 using docker_install_package resource

### Expected Result:
I expected /etc/init.d/docker start to succeed.

### Actual Result:
starting the docker service stalls forever

From 2.13.5 on, the upstart template for docker installed by this cookbook sets a variable DOCKERD=/usr/bin/dockerd, however that binary does not exist with the 1.11.2 docker-engine package that is installed. There is logic in the docker_service_manager.rb and related files to handle using 'docker' as the docker daemon and passing '-d' for 'dockerd' and 'daemon' for 'docker', but all of that logic does not seem to get exercised when the upstart and default templates are evaluated.

We are forced to pin this cookbook to 2.13.4 on Ubuntu 14.04 at this time.

**Comment by gavinheavyside** [comment]
I've just hit this too

**Comment by smgt** [comment]
After restart of the service was removed the tests never test the new upstart file that is generated by docker cookbook. This makes the tests pass but if you enter the VM and try to restart docker it will get stuck in a loop. If you run tests in `v1.12.8` suite `service-upstart-ubuntu-1404` will hang forever.

**Comment by someara** [comment]
This should be fixed up in 2.14.0
