### ISSUE TITLE
Update docker -> dockerd in template

### ISSUE THREAD

**Issue by keithyau** [chef-cookbooks/docker#804]
### Cookbook version
latest

### Chef-client version
Chef 12

### Platform Details
AWS AmazonLinux

### Scenario:
Docker unable to start
### Steps to Reproduce:
All docker_service, docker_installation_xxx tried

### Expected Result:
Docker can start

### Actual Result:
Failed to start 

Reason: the template that copy to init.d should be updated 

https://github.com/chef-cookbooks/docker/blob/master/templates/default/sysvinit/docker-rhel.erb

Line27: exec="/usr/bin/$prog" -> exec="/usr/bin/${prog}d"

**Comment by eric-tucker** [comment]
Can we get this fixed please?  This is blocking usage of docker version 1.12 onwards on any Redhat system still using systemd.

**Comment by someara** [comment]
This is fixed in 2.14.0
