### ISSUE TITLE
No such image from aws ecs registry

### ISSUE THREAD

**Issue by oleg-filiutsich** [chef-cookbooks/docker#806]
### Cookbook version
2.13.9

### Chef-client version
12.18.31

### Platform Details
CentOS 7
Docker: 1.13.0

### Scenario:
try pull docker image from ecs registry via chef docker cookbook

### Steps to Reproduce:
1. Push docker image to aws ecs registry
2. Get aws login in the host (`aws ecr get-login --region eu-west-1`)
3. Run chef recipe like 
docker_image 'docker-app-experiments-image' do
  repo 544444444.dkr.ecr.eu-west-1.amazonaws.com/my2experiments
  tag 1
  action :pull
  read_timeout 600
end

### Expected Result:
Pulled docker image

### Actual Result:
    Docker::Error::NotFoundError
    ----------------------------
    No such image: 544444444.dkr.ecr.eu-west-1.amazonaws.com/my2experiments:17

### Try manual
docker pull 544444444.dkr.ecr.eu-west-1.amazonaws.com/my2experiments:17 
works success

**Comment by AlehFiliutsich** [comment]
I tried trick like
`  # get-aws-docker-registry credls
  template '/root/.aws/credentials' do
    source 'credentials.erb'
    action :create
    mode '0600'
  end

  # get-aws-docker-registry credls
  template '/etc/get-aws-credls.sh' do
    source 'get-aws-credls.sh.erb'
    action :create
    mode '0744'
  end

  cron 'get-aws-docker-registry-credls' do
    minute '30'
    command '/etc/get-aws-credls.sh'
    notifies :run, 'execute[get-dkr-credls]', :immediately
  end

  execute "get-dkr-credls" do
    command "bash /etc/get-aws-credls.sh"
    action :nothing
  end

  require 'json'
  file = File.read('/root/.docker/config.json')
  data_hash = JSON.parse(file)

  docker_registry 'https://544444444.dkr.ecr.eu-west-1.amazonaws.com' do
    username 'AWS'
    password "#{data_hash['auths']['544444444.dkr.ecr.eu-west-1.amazonaws.com']['auth']}"
  end`

but authentication failed.

Then I runned command from command line all was fine.

**Comment by eric-tucker** [comment]
Unrelated but how did you get Docker to even install?  The install script doesn't even work on Amazon Linux right now:

https://github.com/chef-cookbooks/docker/issues/812

**Comment by zvymazal** [comment]
Hi @oleg-filiutsich , I got it working based on your "workaround". You just missed that auth information in .docker/config.json is base64 encoded. Here's my code:

`require 'json'
require 'base64'

bash "get ECR credentials" do
  code "eval $(aws ecr get-login --region us-east-1)"
end

file = File.read('/root/.docker/config.json')
docker_config = JSON.parse(file)

docker_registry 'https://1234567890.dkr.ecr.us-east-1.amazonaws.com' do
  username Base64.decode64(docker_config['auths']['https://1234567890.dkr.ecr.us-east-1.amazonaws.com']['auth']).split(':').first
  password Base64.decode64(docker_config['auths']['https://1§234567890.dkr.ecr.us-east-1.amazonaws.com']['auth']).split(':').last
end`

**Comment by someara** [comment]
Closing this and linking to https://github.com/chef-cookbooks/docker/issues/826

**Comment by zvymazal** [comment]
@lifeofguenter We switched to https://github.com/awslabs/amazon-ecr-credential-helper

**Comment by lifeofguenter** [comment]
thanks @zvymazal - solved the issue, turns out  you first need a `docker_image` resource before using the image directly in `docker_container`...
