### ISSUE TITLE
Error while installing docker_service

### ISSUE THREAD

**Issue by SaravananPerumal23** [chef-cookbooks/docker#829]
### Cookbook version
2.15.2

### Chef-client version
12.10.24

### Platform Details
MacOS

### Scenario:
Trying to run Docker service in my Kitchen instance with Centos 7

### Steps to Reproduce:
Have included Docker cookbook as a dependency in my cookbook and tried to install Docker service in Kitchen instance which has centos7, but am facing issue while installing docker-engine which is installed by this docker cookbook.

### Expected Result:
docker_service should be  running in this kitchen instance

### Actual Result:
Getting error while the Docker cookbook installs docker-engine,

Note: I had this same cookbook working fine earlier and now when i tried to do some changes, i tried to run this cookbook in my local box but it throws the below error. So guess it is because of the recent version am facing this issue 

* docker_service[default] action create
           * docker_installation_script[default] action create
             * yum_package[curl] action install (up to date)
             * execute[install docker] action run
        
        ================================================================================
        Error executing action `run` on resource 'execute[install docker]'
        ================================================================================
        
        Mixlib::ShellOut::ShellCommandFailed
        ------------------------------------
        Expected process to exit with [0], but received '1'
        ---- Begin output of curl -sSL https://get.docker.com/ | sh ----
        STDOUT: You could try using --skip-broken to work around the problem
         You could try running: rpm -Va --nofiles --nodigest
        STDERR: + sh -c 'sleep 3; yum -y -q install docker-engine'
        Error: Package: docker-engine-selinux-1.13.1-1.el7.centos.noarch (docker-main-repo)
                   Requires: selinux-policy-base >= 3.13.1-102
                   Installed: selinux-policy-targeted-3.13.1-60.el7_2.3.noarch (@Centos7-updates)
                       selinux-policy-base = 3.13.1-60.el7_2.3
                   Available: selinux-policy-minimum-3.13.1-23.el7.noarch (Centos7)
                       selinux-policy-base = 3.13.1-23.el7
                   Available: selinux-policy-minimum-3.13.1-23.el7_1.7.noarch (Centos7-updates)
                       selinux-policy-base = 3.13.1-23.el7_1.7
                   Available: selinux-policy-minimum-3.13.1-23.el7_1.8.noarch (Centos7-updates)
                       selinux-policy-base = 3.13.1-23.el7_1.8
                   Available: selinux-policy-minimum-3.13.1-23.el7_1.13.noarch (Centos7-updates)
                       selinux-policy-base = 3.13.1-23.el7_1.13
                   Available: selinux-policy-minimum-3.13.1-23.el7_1.17.noarch (Centos7-updates)
                       selinux-policy-base = 3.13.1-23.el7_1.17
                   Available: selinux-policy-minimum-3.13.1-23.el7_1.18.noarch (Centos7-updates)
                       selinux-policy-base = 3.13.1-23.el7_1.18
                   Available: selinux-policy-minimum-3.13.1-23.el7_1.21.noarch (Centos7-updates)
                       selinux-policy-base = 3.13.1-23.el7_1.21
                   Available: selinux-policy-minimum-3.13.1-60.el7.noarch (Centos7)
                       selinux-policy-base = 3.13.1-60.el7
                   Available: selinux-policy-minimum-3.13.1-60.el7_2.3.noarch (Centos7-updates)
                       selinux-policy-base = 3.13.1-60.el7_2.3
                   Available: selinux-policy-minimum-3.13.1-60.el7_2.7.noarch (Centos7-updates)
                       selinux-policy-base = 3.13.1-60.el7_2.7
                   Available: selinux-policy-minimum-3.13.1-60.el7_2.9.noarch (Centos7-updates)
                       selinux-policy-base = 3.13.1-60.el7_2.9
                   Available: selinux-policy-mls-3.13.1-23.el7.noarch (Centos7)
                       selinux-policy-base = 3.13.1-23.el7
                   Available: selinux-policy-mls-3.13.1-23.el7_1.7.noarch (Centos7-updates)
                       selinux-policy-base = 3.13.1-23.el7_1.7
                   Available: selinux-policy-mls-3.13.1-23.el7_1.8.noarch (Centos7-updates)
                       selinux-policy-base = 3.13.1-23.el7_1.8
                   Available: selinux-policy-mls-3.13.1-23.el7_1.13.noarch (Centos7-updates)
                       selinux-policy-base = 3.13.1-23.el7_1.13
                   Available: selinux-policy-mls-3.13.1-23.el7_1.17.noarch (Centos7-updates)
                       selinux-policy-base = 3.13.1-23.el7_1.17
                   Available: selinux-policy-mls-3.13.1-23.el7_1.18.noarch (Centos7-updates)
                       selinux-policy-base = 3.13.1-23.el7_1.18
                   Available: selinux-policy-mls-3.13.1-23.el7_1.21.noarch (Centos7-updates)
                       selinux-policy-base = 3.13.1-23.el7_1.21
                   Available: selinux-policy-mls-3.13.1-60.el7.noarch (Centos7)
                       selinux-policy-base = 3.13.1-60.el7
                   Available: selinux-policy-mls-3.13.1-60.el7_2.3.noarch (Centos7-updates)
                       selinux-policy-base = 3.13.1-60.el7_2.3
                   Available: selinux-policy-mls-3.13.1-60.el7_2.7.noarch (Centos7-updates)
                       selinux-policy-base = 3.13.1-60.el7_2.7
                   Available: selinux-policy-mls-3.13.1-60.el7_2.9.noarch (Centos7-updates)
                       selinux-policy-base = 3.13.1-60.el7_2.9
                   Available: selinux-policy-targeted-3.13.1-23.el7.noarch (Centos7)
                       selinux-policy-base = 3.13.1-23.el7
                   Available: selinux-policy-targeted-3.13.1-23.el7_1.7.noarch (Centos7-updates)
                       selinux-policy-base = 3.13.1-23.el7_1.7
                   Available: selinux-policy-targeted-3.13.1-23.el7_1.8.noarch (Centos7-updates)
                       selinux-policy-base = 3.13.1-23.el7_1.8
                   Available: selinux-policy-targeted-3.13.1-23.el7_1.13.noarch (Centos7-updates)
                       selinux-policy-base = 3.13.1-23.el7_1.13
                   Available: selinux-policy-targeted-3.13.1-23.el7_1.17.noarch (Centos7-updates)
                       selinux-policy-base = 3.13.1-23.el7_1.17
                   Available: selinux-policy-targeted-3.13.1-23.el7_1.18.noarch (Centos7-updates)
                       selinux-policy-base = 3.13.1-23.el7_1.18
                   Available: selinux-policy-targeted-3.13.1-23.el7_1.21.noarch (Centos7-updates)
                       selinux-policy-base = 3.13.1-23.el7_1.21
                   Available: selinux-policy-targeted-3.13.1-60.el7.noarch (Centos7)
                       selinux-policy-base = 3.13.1-60.el7
                   Available: selinux-policy-targeted-3.13.1-60.el7_2.7.noarch (Centos7-updates)
                       selinux-policy-base = 3.13.1-60.el7_2.7
                   Available: selinux-policy-targeted-3.13.1-60.el7_2.9.noarch (Centos7-updates)
                       selinux-policy-base = 3.13.1-60.el7_2.9

**Comment by ChiefAlexander** [comment]
Relates to https://github.com/docker/docker/issues/30377

**Comment by someara** [comment]
Strange that https://travis-ci.org/chef-cookbooks/docker/jobs/201887351#L385
is passing then...

Sounds like a bug in Docker's packaging....
https://github.com/docker/docker/pull/30380

I won't have time to look deeply into this for at last a week.

-s

**Comment by cheeseplus** [comment]
Closing as this is an upstream bug.
