### ISSUE TITLE
Weird behavior when using port ranges 

### ISSUE THREAD

**Issue by sbaehring** [chef-cookbooks/docker#830]
### Cookbook version
2.15.2

### Chef-client version
12.18.31

### Platform Details
Debian Jessie 4.8.15-2~bpo8+2 

### Scenario:
I'm trying to create a new container running ProFTPd accepting connections passive mode.
The container should bind ports 50000-50010 to the same ports on the host.
I use this port config option:

port ['20:20', '21:21', '50000-50010:50000-50010']

### Steps to Reproduce:
As the issue has nothing todo with ProFTPD, it can reproduced with a simple alpine container:

```
docker_container 'test' do
  repo 'alpine'
  tag 'latest'
  port ['20:20', '21:21', '50000-50010:50000-50010']
  command 'tail -f /dev/null'
  kill_after 3
  action :run
end
```

### Expected Result:
docker ps output regarding ports:

```
0.0.0.0:20-21->20-21/tcp, 
0.0.0.0:50000-50010->50000-50010/tcp
```

### Actual Result:
```
0.0.0.0:20-21->20-21/tcp, 
0.0.0.0:50005->50005/tcp, 
0.0.0.0:50010->50000/tcp, 
0.0.0.0:50009->50001/tcp, 
0.0.0.0:50008->50002/tcp, 
0.0.0.0:50007->50003/tcp, 
0.0.0.0:50006->50004/tcp, 
0.0.0.0:50004->50006/tcp, 
0.0.0.0:50003->50007/tcp, 
0.0.0.0:50002->50008/tcp, 
0.0.0.0:50001->50009/tcp, 
0.0.0.0:50000->50010/tcp   
```

The ports in the container are not bound to their corresponding ports on the host. Only port 50005 is bound correctly.

**Comment by caleb** [comment]
I ran into this as well. This is what I did:

```ruby
...
port ['21:21', '990:990'] + (10090..10100).collect { |p| "#{p}:#{p}" }
...
```
