### ISSUE TITLE
Incorrect Documentation: docker_container defaults to :pull action

### ISSUE THREAD

**Issue by iancward** [chef-cookbooks/docker#831]
### Cookbook version
2.15.2

### Chef-client version
12.16.42

### Platform Details
RHEL 7

### Scenario:
I wrote a chefspec assertion for a docker_image resource, expecting it to default to a `pull_if_missing` action, which is what is documented in the README.

### Steps to Reproduce:
Follow the directions in the README, see different result.

### Expected Result:
The information provided in the README should match the the default action in the resource code: I should not get an error.

### Actual Result:
I got an error that `[:pull]` does not include `:pull_if_missing`

### Relevant code lines:
Documentation explains that `:pull_if_missing` is the default: https://github.com/chef-cookbooks/docker/blob/master/README.md#actions-1

Default is actually `:pull`: https://github.com/chef-cookbooks/docker/blob/master/libraries/docker_image.rb#L31

**Comment by iennae** [comment]
Thanks for letting us know. I've updated the README to reflect the default action.
