### ISSUE TITLE
Fails to install docker since docker-engine replaced by docker-ce

### ISSUE THREAD

**Issue by holmesb** [chef-cookbooks/docker#832]
### Cookbook version
2.15.2

### Chef-client version
12.19.36

### Platform Details
Ubuntu 14.04

### Scenario:
Can't install docker-engine\docker-ce

### Steps to Reproduce:
docker_service 'default' do
      action [:create, :start]
end

### Expected Result:
Docker is installed.

### Actual Result:
Docker fails to be installed.  chef-client run returns multiple errors, probably because it's trying to install the old docker-engine instead of the new docker-ce:
"Error executing action `run` on resource 'execute[apt-get -q update]'"
"Error executing action `update` on resource 'apt_update[docker]'"
"Error executing action `run` on resource 'execute[install docker]'"
"Error executing action `create` on resource 'docker_installation_script[default]'"
"Error executing action `create` on resource 'docker_service[default]'"

[chef-client.txt](https://github.com/chef-cookbooks/docker/files/852702/chef-client.txt)

**Comment by cheeseplus** [comment]
Closing as dupe of https://github.com/chef-cookbooks/docker/issues/835
