### ISSUE TITLE
Support for new docker version starting from v17.03.0-ce

### ISSUE THREAD

**Issue by lbdremy** [chef-cookbooks/docker#835]
Docker introduces a change in its release model, it is not possible anymore to upgrade docker from this cookbook. 

Do you plan to support this change soon ?

Thanks a lot

**Comment by someara** [comment]
Of course. Just haven't gotten around to it yet.

**Comment by someara** [comment]
Fixed as of 2.15.3

**Comment by holmesb** [comment]
I can't see that this is fixed.  Still getting error: "Unable to locate package docker-engine" when running code:
docker_service 'default' do
      action [:create, :start]
end
