### ISSUE TITLE
docker_image :pull triggers on each converge

### ISSUE THREAD

**Issue by rmoriz** [chef-cookbooks/docker#837]
We've the following setup:

```ruby

# fetch the image that we use as base image
docker_image 'debian' do
  tag 'jessie'
  action :pull
  notifies :build, 'docker_image[tools-remote]' # should only be triggered on updated image
end

# render Dockerfile and other things
remote_directory '/srv/docker-build/tools-remote' do
  notifies :build, 'docker_image[tools-remote]'
end

# build our custom image (based on debian:jessie)
docker_image 'tools-remote' do
  source '/srv/docker-build/tools-remote'
  action :build_if_missing
  notifies :redeploy, 'docker_container[tools-remote]'
end

# deploy the image initially
docker_container 'tools-remote' do
  repo 'tools-remote'
  ...
  restart_policy 'unless-stopped'
  action :run
end
```
The idea is to trigger a rebuild and redeployment of the container on changes in the base image (which is debian:jessie) or changes in the Dockerfile which is deployed using `remote_directory?.

However on each converge, the docker_image is notifying the image build

```
tools01.example.com   * docker_image[debian] action pull
tools01.example.com     - Pull image debian:jessie  # <--- !
..
tools01.example.com   * docker_image[tools-remote] action build
tools01.example.com     - Build image tools-remote:latest
tools01.example.com   * docker_container[tools-remote] action redeploy
tools01.example.com     - stopping tools-remote 
tools01.example.com     - deleting tools-remote
tools01.example.com     - create tools-remotein

```

Doing `:pull_if_missing` does not work for us because the tagged images get's updated regularly (and we want to consume those updates to prevent stale/insecure base images).

**Comment by cheeseplus** [comment]
Is it possible you can protect this with a `not_if`? 

I haven't spent a ton of time digging into this one but I expect that `:pull` will always run b/c if there isn't anything new, then nothing happens (from a docker standpoint). It seems like a `not_if` would suffice as a workaround but I'm not sure just yet if this merits a new action like `:pull_only_updated` or if that is really worth pursuing in the resource itself.

**Comment by someara** [comment]
Just spot checked this and `:pull` seems to be working as expected.

Here's a gist from manually converging a smoke suite twice

https://gist.github.com/someara/d0ad285c101546da0bfa60a111b34f76#file-gistfile1-txt-L734

I bet debian updated their "jessie" tag on you. I'd try using the numerical tags instead. 

Even then, tags aren't immutable and there's nothing stopping upstream from changing the image on you.

-s
