### ISSUE TITLE
Deploying files to running containers

### ISSUE THREAD

**Issue by clarkent86** [chef-cookbooks/docker#838]
Is there a way to deploy files to a running container?
Basically, I'm looking to combine the existing docker_container sections with docker cp https://docs.docker.com/engine/reference/commandline/cp/ .

If there is an easier way to deploy files that I'm overcomplicating please let me know!

Essentially I've built local config files containing secrets from chef-vault and I would like to deploy them to a running ruby on rails container.

**Comment by CVTJNII** [comment]
Is there a reason you can't deploy the files to the filesystem using the normal Chef providers and then bind the local directory into the container?  I've been using this paradigm and it works well.

**Comment by clarkent86** [comment]
@CVTJNII That sounds like a better option. Thanks! I'll try that out. Do you have a reference I can take a look at?

**Comment by CVTJNII** [comment]
It's pretty simple, just set up the files in #{host_directory} and then bind map them in to the container with the binds argument:

```ruby
   binds ["#{host_directory}:#{container_directory}"]
```

This works just like docker run -v ${host_directory}:${container_directory} container.

**Comment by clarkent86** [comment]
Can I use this syntax within a docker_container section or would I need to invoke the binding somewhere else? Also, would the container_directory only contain what the host_directory contains? Essentially I'd want to add everything in the host_directory to an already existing directory on the container without losing it's existing contents.

I apologize, I'm pretty new to docker. I seem to be having some trouble finding the documentation for that binds function; even just pointing me there should help me out.

Thanks!

**Comment by CVTJNII** [comment]
Looks like it was renamed to volumes.  Search volumes in the README and you'll find it.

Mounting in the directory will mask any other files in the container directory.  You can mount in individual files, though.

**Comment by clarkent86** [comment]
Works flawlessly, thanks for your help @CVTJNII . Volumes totally makes sense for what I was asking. I think the use case for volumes could be better defined in the README though, or maybe I just need to be more technical :).
