### ISSUE TITLE
2.15.2 breaks upstart on Docker 1.8

### ISSUE THREAD

**Issue by CVTJNII** [chef-cookbooks/docker#839]
### Cookbook version
2.15.2

### Chef-client version
2.19.36

### Platform Details
Ubuntu 14.04.1 LTS

### Docker Version
1.8.2

### Scenario:
Unable to start Docker

### Steps to Reproduce:
"service docker start" hangs as Docker can't start.  This also blocks convergence.

### Expected Result:
Docker should start

### Actual Result:
Docker doesn't start

This appears to be a breaking change between 2.6.1 and 2.15.2.  In 2.15.2 the --raw-logs flag was added to the daemon flags in /etc/init/docker.conf:

```
root@default-ubuntu-1404:~# grep raw.logs /etc/ -ir
/etc/init/docker.conf:    exec "$DOCKER" daemon $DOCKER_OPTS --raw-logs
```

This is not compatible with the older version of Docker, which is still supported per the readme (or at least 1.8.3).  We are pinned back to the older Docker version due to blocking Docker bugs.  It would be nice if this breaking change could be resolved in the same major version.  (I won't complain about dropping the older versions, but please bump major, and I think it's late for that.)  Thanks!

**Comment by iennae** [comment]
Did #870 resolve this for you?

**Comment by chasebolt** [comment]
closing  for now. please reopen if this is still an issue with the latest version.
