### ISSUE TITLE
systemd template has diverged from docker causing issues with live-restore functionality 

### ISSUE THREAD

**Issue by timgriffiths** [chef-cookbooks/docker#840]
### Cookbook version
2.15.2

### Chef-client version
1.13.1

### Platform Details
Centos 7

### Scenario:
Trying to use the live-restore functionality

### Steps to Reproduce:

1. add the option  _"misc_opts '--live-restore'"_ into the docker_service dsl 
2. restart docker service so it picks up this new change
3. start a new container
4. restart the docker service again

### Expected Result:
Your docker container should not go down.

### Actual Result:
Docker server restarts all the containers running on that host.

This issue is identical to https://forums.docker.com/t/docker-v1-12-unable-to-live-restore-solved/23658 

Think the key is you just have to update the systemd template to match the one docker packages up in their rpm's
https://github.com/docker/docker/blob/master/contrib/init/systemd/docker.service.rpm

**Comment by timgriffiths** [comment]
it looks like you could swap over to using the docker configuration file and not worry about maintaining the systemd file ... might be a better option, then we could do reloads of the service to get label changes and things like that

https://docs.docker.com/engine/reference/commandline/dockerd/#linux-configuration-file

**Comment by chasebolt** [comment]
this should be resolved in 23751117a46520ca4e859acda2296908e5330a91. please reopen if it is not the case.
