### ISSUE TITLE
Tests for the libraries?

### ISSUE THREAD

**Issue by rmoriz** [chef-cookbooks/docker#843]
just out of curiosity: Don't you test the libraries/resources? 

I've seen the example cookbook and its recipes which get checked using the chefspec matchers, but no tests about the library/implementation itself?

**Comment by someara** [comment]
Nope. Never got around to it. It'd be great if somebody was to start writing those
-s

**Comment by rmoriz** [comment]
I can feel your pain. I was just looking for good examples to get myself started on writing some on my own cookbooks. meh ;)
