### ISSUE TITLE
docker_service doesn't converge properly when properties are updated

### ISSUE THREAD

**Issue by aespinosa** [chef-cookbooks/docker#849]
### Cookbook version
2.15.5

### Chef-client version
12.19.36
### Platform Details
debian-8.6

### Scenario:
Make the `docker_service` converge to its desired properties

### Steps to Reproduce:
1. Create version 1 of a recipe:

```
# recipes/default.rb
# version1
docker_service 'default' do
   auto_restart true
    action %w(create start)
end
```

2. converge chef

3. Update recipe to version2:

```
# recipes/default.rb
# version2
docker_service 'default' do
    auto_restart true
    pidfile '/var/run/another-file.pid'
    action %w(create start)
end
```

4. converge Chef again

### Expected Result:
The docker daemon should be running with `--pidfile=/var/run/another-file.pid` commandline option.

```
● docker.service - Docker Application Container Engine
   Loaded: loaded (/etc/systemd/system/docker.service; enabled)
   Active: active (running) since Tue 2017-04-25 03:26:32 UTC; 7min ago
     Docs: http://docs.docker.com
  Process: 23697 ExecStartPost=/usr/lib/docker/docker-wait-ready (code=exited, status=0/SUCCESS)
  Process: 23596 ExecStartPre=/sbin/sysctl -w net.ipv6.conf.all.forwarding=1 (code=exited, status=0/SUCCESS)
  Process: 23593 ExecStartPre=/sbin/sysctl -w net.ipv4.ip_forward=1 (code=exited, status=0/SUCCESS)
 Main PID: 23598 (dockerd)
   CGroup: /system.slice/docker.service
           ├─23598 /usr/bin/dockerd --pidfile=/var/run/another-file.pid
           └─23604 docker-containerd -l unix:///var/run/docker/libcontainerd/docker-containerd.sock --metrics-interval=0 --start-timeout 2m --state-dir /var/run/doc...

```

### Actual Result:

The docker daemon is still running with the old commandline flags in place.  The docker daemon is not restarted because there are notifications when `/lib/systemd/system/docker.service` is updated to restart the service.  Only the systemd unit is reinitialized.

```
● docker.service - Docker Application Container Engine
   Loaded: loaded (/etc/systemd/system/docker.service; enabled)
   Active: active (running) since Tue 2017-04-25 03:25:16 UTC; 1min 0s ago
     Docs: http://docs.docker.com
 Main PID: 23009 (dockerd)
   CGroup: /system.slice/docker.service
           ├─23009 /usr/bin/dockerd --bip=10.0.72.1/24 --mtu=1472 --pidfile=/var/run/docker.pid
           └─23014 docker-containerd -l unix:///var/run/docker/libcontainerd/docker-containerd.sock --metrics-interval=0 --start-timeout 2m --state-dir /var/run/doc...
```

**Comment by mlcooper** [comment]
I ran into this same exact thing, only I was updating the `host` parameter in `docker_service` instead of `pidfile`.  Once I manually restarted the docker service after a chef run, my new `host` parameter was running properly.

Chef client 12.14.89, RHEL7, Cookbook v2.15.6

**Comment by iennae** [comment]
Please be aware that we are looking into this. There is a known issue with restarting the service as per Issue #799 where release [2.15.2](https://github.com/chef-cookbooks/docker/blob/master/CHANGELOG.md) reverted restart changes.

**Comment by eyalzek** [comment]
I'm seeing the same behavior when using `docker_service_manager_upstart`, after the initial run `dockerd` is running with the default values:
`27808 ?        Ssl    0:00 /usr/bin/dockerd --raw-logs`

after a manual restart the correct configuration from `/etc/default/docker` is picked up. Is there a way to force a restart somehow at the moment?

**Comment by lamont-granquist** [comment]
It looks like all we need is https://github.com/chef-cookbooks/docker/commit/00707bf5e0c4d2d3a73dfc41cebc7053157cd6fd but we need an execute resource in the action to target the notification against.

**Comment by iennae** [comment]
@eyalzek can you open a separate issue for upstart? Thanks.

**Comment by iennae** [comment]
@aespinosa can you check whether #880 solves your problem?

**Comment by aespinosa** [comment]
Just tested the master branch.  It works now @iennae . Thanks!
