### ISSUE TITLE
Error executing action `redeploy` on resource 'docker_container

### ISSUE THREAD

**Issue by SergeySevruk** [chef-cookbooks/docker#851]
### Cookbook version
2.15.5

### Chef-client version
12.19.36

### Platform Details
Ubuntu 16.04.2 (x64)

### Scenario:

```
# Pull latest image
docker_image "...some path..." do
  tag node 'latest'
  action :pull
  retries 3
  notifies :redeploy, 'docker_container[office]'
end

docker_container 'office' do
  repo "...some path..."
  tag 'latest'
  port '80:80'
  env ['NODE_ENV=cd']
end
```

### Steps to Reproduce:
Error is produced at the time of first running on clean VM.

### Expected Result:
Looks like some incorrect work of `redeploy` function.

### Actual Result:
10.35.36.11     ================================================================================
10.35.36.11     Error executing action `redeploy` on resource 'docker_container[office]'
10.35.36.11     ================================================================================
10.35.36.11     
10.35.36.11     Docker::Error::TimeoutError
10.35.36.11     ---------------------------
10.35.36.11     Container failed to stop, consider adding kill_after to the container office
10.35.36.11     
10.35.36.11     Cookbook Trace:
10.35.36.11     ---------------
10.35.36.11     /var/chef/cache/cookbooks/docker/libraries/docker_container.rb:353:in `rescue in block (2 levels) in <class:DockerContainer>'
10.35.36.11     /var/chef/cache/cookbooks/docker/libraries/docker_container.rb:347:in `block (2 levels) in <class:DockerContainer>'
10.35.36.11     /var/chef/cache/cookbooks/docker/libraries/docker_container.rb:346:in `block in <class:DockerContainer>'
10.35.36.11     /var/chef/cache/cookbooks/docker/libraries/docker_container.rb:172:in `call_action'
10.35.36.11     /var/chef/cache/cookbooks/docker/libraries/docker_container.rb:416:in `block in <class:DockerContainer>'
10.35.36.11     /var/chef/cache/cookbooks/docker/libraries/docker_container.rb:172:in `call_action'
10.35.36.11     /var/chef/cache/cookbooks/docker/libraries/docker_container.rb:409:in `block in <class:DockerContainer>'
10.35.36.11

**Comment by SergeySevruk** [comment]
solution: kill_after 1

**Comment by someara** [comment]
This is in purpose. The docker CLI ends up doing a hard kill on a container if it doesn't properly shut down after a timeout. The `docker_container` Chef resource dies. This is to prevent data corruption when running things like databases where it is unsafe to just "pull the plug".

I'd recommend running some sort of service monitor to properly handle TERM signals (15)

Two good ones are:

https://github.com/Yelp/dumb-init
https://github.com/habitat-sh/

-s
