### ISSUE TITLE
Error executing action `pull` on resource 'docker_image[busybox]'

### ISSUE THREAD

**Issue by twnicholas** [chef-cookbooks/docker#852]
### Cookbook version
??

### Chef-client version
12.19.36

### Platform Details
Centos 7

### Scenario:
```ruby
docker_service 'default' do
  action [:create, :start]
end

docker_image 'busybox' do
  action :pull
end
```

### Steps to Reproduce:
I've created a default.rb recipe file containing the above.  Uploaded it to my server and run chef-client on my client and I get the error:  "Error executing action `pull` on resource 'docker_image[busybox]'"

I'm very new to Chef and "cloudy things" so I'm sure I'm missing something but I cannot find a cogent answer to this anywhere I've looked.

If I'm in the wrong forum, I apologize.  If I'm in the wrong forum, please suggest a more proper forum.

### Expected Result:
I expected this to be successful and not generate an error.

### Actual Result:
Error executing action `pull` on resource 'docker_image[busybox]'
I'm not sure what a "gist" is but I can provide the chef-stacktrace.out if necessary.

**Comment by twnicholas** [comment]
chef-stacktrace.out.  Where/how do I configure where to "pull" from?

Generated at 2017-04-28 14:11:33 -0600
Excon::Error::Socket: docker_image[busybox] (kong-chef::default line 18) had an error: Excon::Error::Socket: Connection refused - connect(2) for /var/run/docker.sock (Errno::ECONNREFUSED)
/opt/chef/embedded/lib/ruby/2.3.0/socket.rb:1207:in `__connect_nonblock'
/opt/chef/embedded/lib/ruby/2.3.0/socket.rb:1207:in `connect_nonblock'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/excon-0.55.0/lib/excon/unix_socket.rb:15:in `connect'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/excon-0.55.0/lib/excon/socket.rb:29:in `initialize'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/excon-0.55.0/lib/excon/connection.rb:401:in `new'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/excon-0.55.0/lib/excon/connection.rb:401:in `socket'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/excon-0.55.0/lib/excon/connection.rb:100:in `request_call'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/excon-0.55.0/lib/excon/middlewares/base.rb:16:in `request_call'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/excon-0.55.0/lib/excon/middlewares/mock.rb:48:in `request_call'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/excon-0.55.0/lib/excon/middlewares/instrumentor.rb:26:in `request_call'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/excon-0.55.0/lib/excon/middlewares/base.rb:16:in `request_call'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/excon-0.55.0/lib/excon/middlewares/base.rb:16:in `request_call'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/excon-0.55.0/lib/excon/middlewares/base.rb:16:in `request_call'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/excon-0.55.0/lib/excon/middlewares/base.rb:16:in `request_call'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/excon-0.55.0/lib/excon/connection.rb:249:in `request'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/excon-0.55.0/lib/excon/middlewares/idempotent.rb:27:in `error_call'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/excon-0.55.0/lib/excon/middlewares/base.rb:11:in `error_call'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/excon-0.55.0/lib/excon/middlewares/base.rb:11:in `error_call'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/excon-0.55.0/lib/excon/middlewares/base.rb:11:in `error_call'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/excon-0.55.0/lib/excon/connection.rb:272:in `rescue in request'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/excon-0.55.0/lib/excon/connection.rb:215:in `request'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/excon-0.55.0/lib/excon/middlewares/idempotent.rb:27:in `error_call'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/excon-0.55.0/lib/excon/middlewares/base.rb:11:in `error_call'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/excon-0.55.0/lib/excon/middlewares/base.rb:11:in `error_call'

**Comment by someara** [comment]
Buy default the docker engine API pulls from the Docker Hub.

It will error if you have firewall rules preventing you from doing so. 

If that is actually the case you'll likely need to configure your `docker_service` with `http_proxy` and `https_proxy` properties.

Closing this as `docker_image` is extensively tested

-s

PS: A gist is kinda like a pastebin but more githubby. https://gist.github.com/
