### ISSUE TITLE
CHANGELOG version numbers do not align with version found in metadata.rb

### ISSUE THREAD

**Issue by mlcooper** [chef-cookbooks/docker#855]
In the metadata.rb, it says the cookbook version is `2.15.6`:  https://github.com/chef-cookbooks/docker/blob/master/metadata.rb#L6

In the CHANGELOG, the latest update says it is for `12.15.6`:
https://github.com/chef-cookbooks/docker/blob/master/CHANGELOG.md#12156-2017-05-01

**Comment by someara** [comment]
Nice catch. Fixed up. Thanks!
-s
