### ISSUE TITLE
"Docker::Error::NotFoundError: No such image" when trying to pull large images.

### ISSUE THREAD

**Issue by sathed** [chef-cookbooks/docker#858]
### Cookbook version
2.15.6

### Chef-client version
12

### Platform Details
Hosting on AWS
OS: Amazon Linux 2016.09

### Scenario:
I'm trying to pull a large image (~10 GB) from AWS ECR. However, after a minute or two, it will fail saying that the image doesn't exist.

_Note: Before you say anything about the size of the image, yes, I know it's an incredibly large image or that it almost defeats the purpose of using Docker, etc, etc._ 

### Steps to Reproduce:
1. Find a large docker image.
2. Try pulling it down with:

```
docker_image 'http://some/repo/here' do
    repo 'http://some/repo/here'
    tag "latest"
    action :pull
end
```

It's that simple. If the image is large, then it will fail every time. I haven't played with the different sizes to find out at what point it's breaking. I have played with the `read_timeout` and `write_timeout` options, setting it to 3600 (more than enough time to pull 10 GB) but that didn't work either. 

### Expected Result:
Docker should pull down the image.

### Actual Result:
An error is produced saying that the image does not exist.

```
[2017-05-15T17:45:37+00:00] ERROR: Running exception handlers
[2017-05-15T17:45:37+00:00] ERROR: Exception handlers complete
[2017-05-15T17:45:37+00:00] FATAL: Stacktrace dumped to /var/chef/runs/a5726df5-8f11-439e-9828-ede14636d1f6/local-mode-cache/cache/chef-stacktrace.out
[2017-05-15T17:45:37+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2017-05-15T17:45:37+00:00] ERROR: docker_image[**********.dkr.ecr.us-west-2.amazonaws.com/imagename] (addrgeo::default line 4) had an error: Docker::Error::NotFoundError: No such image: **********.dkr.ecr.us-west-2.amazonaws.com/imagename:latest
[2017-05-15T17:45:37+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by chasebolt** [comment]
i dont use AWS ECR but my guess is that chef docker isnt properly logged
into the registry

**Comment by sathed** [comment]
@chasebolt - I have confirmed that it is logged in properly. I can pull small images just fine. For example, I pulled busybox, re-tagged it, pushed to AWS with a different tag. I can pull that image from the same repo just fine.

**Comment by chasebolt** [comment]
you verified the busybox pull via chef and not cli correct?

**Comment by chasebolt** [comment]
just double checking as chef and cli work 100% independently of each other. so while cli may work that doesnt guarantee chef will.

**Comment by chasebolt** [comment]
not sure if this applies to you https://github.com/chef-cookbooks/docker/issues/826

**Comment by sathed** [comment]
@chasebolt - yes, I did verify with Chef.

**Comment by CVTJNII** [comment]
I've seen this on pulls from the public hub and from our internal registry.  The "no such image" is a false error that I've seen thrown on multiple errors.  From my chair when an image fails to pull for any reason the real error is swallowed and "no such image" is thrown.

I haven't dug into the mechanics of it as whenever I've seen this it's been a symptom of another problem, so I've focused my efforts on fixing that.  Based on my experience I'd say this is a timeout getting falsely reported as no such image.  Check out the read_timeout and write_timeout parameters on the docker_image resource.  I had to up them for big images in my environment.

**Comment by sathed** [comment]
@CVTJNII - The first thing I did was up the `read_timeout` and `write_timeout`. I had them up to 3600 and it was still failing. I'm with you though - I'm pretty sure this is a timeout issue that isn't handled properly.

**Comment by chasebolt** [comment]
if you want to get into some debugging you can run this before your chef run and watch the docker api calls to see where it fails/timeout.

https://gist.github.com/chasebolt/3e58bc05203a6fcf5d71

**Comment by sathed** [comment]
Thanks @chasebolt! I'll give that a shot.

**Comment by sathed** [comment]
After running the script that @chasebolt linked, I can confirm that it's a timeout issue. The download starts, but fails consistently after a period of time and throws the `Docker::Error::NotFoundError: No such image` error.

**Comment by sathed** [comment]
Somehow I missed this last night after hastily giving it another go. Turns out this is user error - I was running out of storage on disk. However, the error that is being thrown needs to be fixed...

The Docker API is throwing:

```
{"errorDetail":{"message":"write /var/lib/docker/tmp/GetImageBlob934167277: no space left on device"},"error":"write /var/lib/docker/tmp/GetImageBlob934167277: no space left on device"}
```

Chef is throwing:

```
Docker::Error::NotFoundError: No such image
```

**Comment by chasebolt** [comment]
thanks for the followup!
