### ISSUE TITLE
Support Environment Variables in the `docker_service` library

### ISSUE THREAD

**Issue by skylerto** [chef-cookbooks/docker#859]
It would be nice to be able to add Environment variables to the docker_service.

The use case here is for the [aws cloudwatch logging driver](https://docs.docker.com/engine/admin/logging/awslogs/), the docker daemon needs to be able to have access to the aws credentials.

**Comment by chasebolt** [comment]
Can the `misc_opts` do what you need?

https://github.com/chef-cookbooks/docker/blob/master/libraries/docker_service_base.rb#L69-L70

**Comment by skylerto** [comment]
I'm not sure how docker daemon opts would help.

The solution I ended up going with was to mount a volume and use the awslogs service on the host.

I could still see adding environment variables to the service that start the docker daemon useful.

**Comment by chasebolt** [comment]
pending rebase on #865

**Comment by chasebolt** [comment]
released in `v2.15.24`

**Comment by elijah** [comment]
This should probably have been a new issue instead of being tagged onto a question about docker_service.

Try this pattern:

docker_container 'blah' do
  action :run 
  env ['PORT=8001', 'NODE_REJECT_TLS_UNAUTHORIZED=0', 'VAULT_AUTH_DEFAULT=TOKEN']
end
