### ISSUE TITLE
Docker Swarm provisioning

### ISSUE THREAD

**Issue by mshahat** [chef-cookbooks/docker#862]
Hi, 

What would be the best approach to provision a Docker Swarm of few machines using this cookbook ? would it support docker-machine ? or support swarm creation in a way ? 

or should i just code everything on top of that cookbook ? 

Thanks,

**Comment by chasebolt** [comment]
i dont personally use docker swarm. but majority of commands you can pass to docker you can pass as a property to `docker_container`. i have seen people get a swarm setup using this cookbook so i do know it is possible.
