### ISSUE TITLE
Docker service fails to start when using: storage_driver 'vfs'

### ISSUE THREAD

**Issue by monokal** [chef-cookbooks/docker#869]
### Cookbook version
2.15.6

### Chef-client version
12.13.37

### Platform Details
Centos 7

### Scenario:
Set the Docker storage driver to "vfs".

### Steps to Reproduce:
```ruby
docker_service 'docker' do
  storage_driver 'vfs'
  action [:create, :start]
end
```

### Expected Result:
Storage driver is set to vfs and Docker service is running.

### Actual Result:
Storage driver is set to vfs in the systemd unit, however, the Docker service fails to run:

/etc/systemd/system/docker-docker.service
```
[Unit]
Description=Docker Application Container Engine
Documentation=http://docs.docker.com
After=network.target

[Service]
Type=notify
ExecStartPre=/sbin/sysctl -w net.ipv4.ip_forward=1
ExecStartPre=/sbin/sysctl -w net.ipv6.conf.all.forwarding=1
ExecStart=/usr/bin/dockerd  --pidfile=/var/run/docker-docker.pid --storage-driver=vfs
ExecStartPost=/usr/libexec/docker/docker-docker-wait-ready
Restart=always
MountFlags=slave
LimitNOFILE=1048576
LimitNPROC=1048576
LimitCORE=infinity


[Install]
WantedBy=multi-user.target
```

journalctl -xe
```
Jun 12 12:21:46 b6bfbc08a41e systemd[1]: start request repeated too quickly for docker.service
Jun 12 12:21:46 b6bfbc08a41e systemd[1]: Failed to start Docker Application Container Engine.
-- Subject: Unit docker.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit docker.service has failed.
--
-- The result is failed.
Jun 12 12:21:46 b6bfbc08a41e systemd[1]: docker.service failed.
```

**Comment by chasebolt** [comment]
can you provide more debug on why the service failed to start? maybe run `/usr/bin/dockerd  --pidfile=/var/run/docker-docker.pid --storage-driver=vfs` and see if you get more output.

i dont think this is a cookbook issue though as it is setting up the service start properly.

**Comment by iennae** [comment]
Please reopen if you are still having this problem. Please include the additional information as requested by @chasebolt.
