### ISSUE TITLE
TasksMax=infinity setting should be configurable or dynamically enabled

### ISSUE THREAD

**Issue by mlcooper** [chef-cookbooks/docker#871]
### Cookbook version
`2.15.11` and higher

Docker says that the `TasksMax=infinity` setting is only compatible with a certain version, `226`, or higher, of `systemd`:
https://github.com/moby/moby/blob/v17.04.0-ce/contrib/init/systemd/docker.service#L20-L22

Looking on my RHEL7 box, which is full updated/patched, the latest available to me is `219-30.el7_3.9`, so if this setting is on by default via the template in this cookbook, then it may cause an issue.

The specific template I'm looking at is:
https://github.com/chef-cookbooks/docker/blob/v2.15.11/templates/default/systemd/docker.service-override.erb#L35

Perhaps this cookbook could check the version of `systemd` found on the server and enable `TasksMax=infinity` if the version supports it.

**Comment by iancward** [comment]
related: https://github.com/moby/moby/issues/20036

**Comment by iancward** [comment]
On RHEL7, With the TasksMax line in the `/etc/systemd/system/docker.service`, I see this error in `journalctl` after a `systemctl daemon-reload`:
`[/etc/systemd/system/docker.service:17] Unknown lvalue 'TasksMax' in section 'Service'`

But the reload succeeds and I'm able to restart docker without issue.

**Comment by chasebolt** [comment]
besides the complaint of unknown value, i havent seen this have an adverse effect. when i get time i will look into it more.

**Comment by chasebolt** [comment]
closing this for now. please reopen if you find any issues besides the warning about the unknown value in the systemd log.

**Comment by morrisjones** [comment]
The error involving TasksMax on RHEL 7.3 and other machines with older systemd versions is not a warning, it's a fatal error that prevents the docker service from starting. To work around this problem, I have to find a way to override the default systemd docker.service template that does not include TasksMax.

**Comment by chasebolt** [comment]
Please post some log info that show it is a fatal error causing it to fail
to start. We have tests for centos 7 which throws the warning but continues
fine - along with other distros behaving the same.

**Comment by morrisjones** [comment]
You may be right -- I thought my failure was because of TasksMax, but it might be masked by the docker.socket dependency failure. I have a log, but I have to solve the socket group problem first.

**Comment by chasebolt** [comment]
what version of the cookbook are you running? `v2.15.21` was released with a fix for docker.socket dependency.

**Comment by morrisjones** [comment]
I am running 2.15.21, but needed to add supporting attributes for a local included cookbook to support it. I appear to be running fine now. Sorry for the trouble!
