### ISSUE TITLE
[QUESTION] docker env_file

### ISSUE THREAD

**Issue by pantocrator27** [chef-cookbooks/docker#872]
Does this cookbook support the docker `env_file` parameter?

**Comment by chasebolt** [comment]
currently it does not support `env_file`

**Comment by jamesyale** [comment]
Looks like this was previously supported? https://github.com/chef-cookbooks/docker/commit/a12c58f4e305f0aa7dcfbf4f930d29935c24dd91

**Comment by chaim1221** [comment]
As a reminder, it's still in the documentation.
