### ISSUE TITLE
Support Debian 9 (stretch)

### ISSUE THREAD

**Issue by ramereth** [chef-cookbooks/docker#873]
### Cookbook version
2.9.7

### Chef-client version
12.18.31

### Platform Details
Debian 9.0 (stretch)

### Scenario:
Using ``docker_installation_package`` to install a specific version of docker failed on Debian 9.

### Steps to Reproduce:

When I add the following:

``` ruby
docker_installation_package 'default' do
  version '1.10.3'
end
```

It returns an error that it can't find the version. However when I run ``apt-cache policy docker-engine``, it does show the version exists. Digging deeper it seems that stretch support needs to be added to the helper library for this resource as it appends the proper ``-0~release_name`` to the end of the version.

### Expected Result:
Expect it to install the version I stated on Debian 9 (stretch)

### Actual Result:
Chef run fails with apt-get not finding the version.

**Comment by iennae** [comment]
We're in the process of building a bento box for Debian 9 and we just added Debian 9 to Fauxhai. Once these ship we can get this cleaned up and tested
