### ISSUE TITLE
Cookbook still installing Docker 1.12.6 on Amazon Linux

### ISSUE THREAD

**Issue by eric-tucker** [chef-cookbooks/docker#874]
### Cookbook version
2.15.13

### Chef-client version
12.5.1

### Platform Details
Amazon Linux 2017.03

### Scenario
docker-17.03.1ce-1.50.amzn1 is available on Amazon Linux from the amzn-updates repository but the cookbook is still defaulting to 1.12.6.

Any chance we can get a default docker version bump in [helpers_installation_package.rb](https://github.com/chef-cookbooks/docker/blob/master/libraries/helpers_installation_package.rb#L109)?

**Comment by iennae** [comment]
Thanks for reporting this issue. We'll work on getting this updated.

**Comment by someara** [comment]
This is fixed up in c1c52267c84b18f3025fd929be4b5168338e89fa and released in 2.15.14
