### ISSUE TITLE
Support non detach  mode for docker container

### ISSUE THREAD

**Issue by ruanton29** [chef-cookbooks/docker#879]
Hi all
Sorry for offtopic, but can you add like "docker run -ti" command for one time running with verbose output or add verbose for docker exec, because i need run some pre warmed  command or checks what but it's hide all output ( at latest chef 12 ) 
Thx 
Best regards

**Comment by chasebolt** [comment]
im not sure i fully understand. can you give me some example code of how you would like it to work along the the use case?

**Comment by chasebolt** [comment]
closing for now

**Comment by ruanton29** [comment]
Sorry i miss notification about this issues: 
for example  
docker_container node['jenkins2_master']['docker']['run_default']['name'] do
    repo node['jenkins2_master']['docker']['image']['name']
    tag node['jenkins2_master']['docker']['image']['tag']
    volumes [home_folder]
    env ["REF=/var/jenkins_home/plugins"]
    entrypoint "Some command "
    action [:create, :start]
  end

Add option verbose to make visible output for running command 
For example i need to check that this container run correct script etc 
Best regards
