### ISSUE TITLE
Deprecated resources warnings

### ISSUE THREAD

**Issue by chaim-sw** [chef-cookbooks/docker#881]
### Cookbook version
2.15.6

### Chef-client version
12.19.36

### Platform Details
Ubuntu 16.04 with ChefDK

### Scenario:
Using Docker cookbook resources in a recipe to setup postgres

### Steps to Reproduce:
Reference Docker cookbook v2.15.6 in a recipe
Create a kitchen run that uses the recipe
`kitchen test`

### Expected Result:
I can use the Docker cookbook's resources without deprecated method warnings.

### Actual Result:
https://gist.github.com/chaim-sw/5c413f257691d7d9e6476b7aa542501c

**Comment by tas50** [comment]
These should definitely get fixed before 14 ships

**Comment by someara** [comment]
Fixed up in 2.15.23
