### ISSUE TITLE
Docker Daemon crashed and unable to restart

### ISSUE THREAD

**Issue by AlvinFeng** [chef-cookbooks/docker#888]
### Cookbook version
2.15.17

### Docker version
1.10

### Chef-client version
12.15.19

### Platform Details
RHEL 7.0

Our converges yesterday were repeatedly successful on 2.15.16. Our converge today pulled in 2.15.17, which seems to change /lib/systemd/system/docker.service and /etc/systemd/system/docker.service. This caused the docker daemon to crash, and be unable to restart. Even pinning and converging with the older version of the cookbook doesn't fix the issue, and our docker daemon is down and we are unable to restart it.

Relevant converge logs and output of journalctl @ https://gist.github.com/AlvinFeng/09bc9ea6067f4df67a7e8cfd6b3a9ab9

We were able to reproduce this on multiple boxes, where the docker daemon crashes and we are unable to restart it.

Please let me know how to fix this and get the docker daemon back up and running, and if any other info is needed. Thanks!

**Comment by chasebolt** [comment]
do you have a group named `docker`? it appears your logs are complaining about that not existing.

**Comment by chasebolt** [comment]
previous releases were not properly setting the group, matching upstream docker installs. there should be a group `docker` installed.

if this is not the case please paste your `docker_service` resource block.

**Comment by chasebolt** [comment]
@AlvinFeng please see if your issue is resolved in `v2.15.18`

**Comment by chasebolt** [comment]
please reopen if this is still an issue. this should be resolved in the latest release though.
