### ISSUE TITLE
Docker_service resource fails on RHEL with Centos Docker Repos

### ISSUE THREAD

**Issue by ChiefAlexander** [chef-cookbooks/docker#894]
### Cookbook version
2.15.18

### Chef-client version
12.20.3

### Platform Details
RHEL

### Scenario:
When using the docker_service resource it fails when restarting the docker service

### Steps to Reproduce:
Use RHEL and install docker with the centos yum repo

### Expected Result:
Expecting chef to not fail

### Actual Result:
Chef fails

### Extra:
I tracked down this issue to this change: https://github.com/chef-cookbooks/docker/commit/136382cd83152f0b7017c038110890247ed109e1

Since we are using the docker yum repo from centos and not the repos from redhat we enter into a issue where the cookbook is defaulting to the wrong group. I have updated our resources to use the correct group overwriting the cookbook default.

**Comment by chasebolt** [comment]
thanks for the report. looks like i need to figure out how to detect if someone is installing via the docker repo or not. that way we can set the proper group.

**Comment by ChiefAlexander** [comment]
Yes, i'm not really sure how you would go about that either. I think updating the docs to be clear about this is a good first step however.

**Comment by chasebolt** [comment]
i have documented the docker group issue here https://github.com/chef-cookbooks/docker#docker-group
