### ISSUE TITLE
Breaking Change - Package name changed for RHEL7

### ISSUE THREAD

**Issue by mlcooper** [chef-cookbooks/docker#909]
I believe with this commit, https://github.com/chef-cookbooks/docker/commit/69781c91ec6c9177f6cf14f4fbd76c9c17f05aef, a breaking change was introduced into this cookbook, but it was released as 2.5.20 instead of 3.0.0.  

In this commit, the package name for RHEL7 appears to be effectively changed from `docker-engine` to `docker-ce`.

**Comment by chasebolt** [comment]
the problem this comes down to is docker changing its name in the official docker repo. this cookbook is tested against the official repo and both cookbooks (docker and chef-yum/apt-docker) were released at the same time to prevent breakage.

in hindsight bumping to 3.0 would have done no harm though.
