### ISSUE TITLE
push need to pass the credentials and a specific tag to the push docker-api function

### ISSUE THREAD

**Issue by argoLein** [chef-cookbooks/docker#910]
### Cookbook version
2.15.26

### Chef-client version
13.2.20

### Platform Details
all platforms

### Scenario:
Hint: I fixed that. I need a Issue for a issue-number in my PR.

Push in private registry doesn't work. Because the ressource miss 2 thinks:

1) The saved run_state credentials from the docker_registry ressource were not passed to the push function (docker-api)

2) if you want to push a specific tag, it doesnt work. The defined ressource tag not passed to the push function (docker-api). So the push function use internally the first tag from the image list. if you have a tag like 1.0 and want to push a tag 1.1 function use allways 1.0.

### Steps to Reproduce:
login in a private private repo with docker_registry. try to push an image. no image were in the registry. Use the docker.authenticate (docker-api) function and login. Then create 2 tags for the same image (1.0, 1.1). And then try to push the 1.1 image.

### Expected Result:
i expect to see the 1.1 image in the private registry

### Actual Result:
only the 1.0 will be pushed all the time.

**Comment by iennae** [comment]
This looks to have been merged in by @chasebolt so I'm going to go ahead and close. Thanks for contributing to this cookbook!
