### ISSUE TITLE
Can we ping to an arbitrary version of Docker (e.g. 'stable')

### ISSUE THREAD

**Issue by aaronkjones** [chef-cookbooks/docker#923]
### Cookbook version
2.15.28

### Chef-client version
12.21.1

### Platform Details
Ubuntu 14.04.5 LTS

### Scenario:
Can we pin to an arbitrary version of docker-ce such as 'stable', instead of,

``` default['docker']['version'] = '17.06.0' ```

**Comment by tas50** [comment]
At the moment you'll need to specify a version. If we could programmatically determine what docker considers to be stable perhaps we could add that in the future.
