### ISSUE TITLE
gitter link does not work

### ISSUE THREAD

**Issue by rljohnsn** [chef-cookbooks/docker#926]
Clicking the gitter link in the readme does not connect correctly

<img width="855" alt="screen shot 2017-09-27 at 11 17 59 am" src="https://user-images.githubusercontent.com/830382/30930149-9455e272-a375-11e7-9c07-2e42f4caf5c1.png">

**Comment by tas50** [comment]
I'm actually going to remove the gitter badge. If you'd like to chat about this cookbook come over to the Chef Community Slack.
