### ISSUE TITLE
Add support for arbitrary command line options for docker_container

### ISSUE THREAD

**Issue by rjlee** [chef-cookbooks/docker#929]
### Scenario:
[What you are trying to achieve and you can't?]

I'm trying to setup a `docker_container` configuration to run [blackbox-exporter](https://hub.docker.com/r/prom/blackbox-exporter/).

The recommended config looks like:

`docker run -d -p 9115:9115 --name blackbox_exporter -v pwd:/config blackbox_exporter -config.file=/config/blackbox.yml`

Looking through the documentation for `docker_container` I can't see any way to pass arbitrary command line options like `-config.file=/config/blackbox.yml`

Could this be added as a feature to the `docker_container` resource ?

**Comment by chasebolt** [comment]
im not familiar with the `-config.file` command. can you point me to the docs on this?

**Comment by rjlee** [comment]
It looks to be that a running container can access command line options passed in, for example here are a set of options used by the prometheus container:

http://demo.robustperception.io:9090/flags

So it's less about the specific `-config.file` option and more the general capability for options to be passed on the command line to then be accessed by the container.

**Comment by chasebolt** [comment]
this should work for you

```ruby
docker_container 'blackbox_exporter' do
  repo 'blackbox_exporter'
  port '9115:9115'
  volumes '/localpath/config:/config'
  command '-config.file=/config/blackbox.yml'
end
```

**Comment by rjlee** [comment]
Ah - thank you, sorry I'd misread that as setting the entrypoint.
