### ISSUE TITLE
Using "install_method" under "docker_service" does not install docker.lst repo

### ISSUE THREAD

**Issue by atmosx** [chef-cookbooks/docker#933]
### Cookbook version
cookbook "docker", "~> 2.15.29"

### Chef-client version
12.19.36

### Platform Details
Vagrant / Ubuntu 16.04

### Scenario:
I'm trying to install a specific version of docker: 17.09-ce 

### Steps to Reproduce:
Use the following recipe:

```
docker_service 'default' do
   host    ['tcp://0.0.0.0:2376', 'unix:///var/run/docker.sock']
   group   node['tb_docker']['docker']['group']
   version node['docker']['version']
   install_method 'package'
   action  [:create, :start]
  end
```

### Expected Result:
Get docker 17.09-ce installed

### Actual Result:

I get an error saying "no version was found" because the `docker.lst` repository is not installed.

### Further explanation

If I use the following recipe (I removed _version_ and _install_method_):

```
docker_service 'default' do
   host    ['tcp://0.0.0.0:2376', 'unix:///var/run/docker.sock']
   group   node['tb_docker']['docker']['group']
   action  [:create, :start]
  end
```

The apt repo `docker.lst` is properly installed in `/etc/apt/sources.list.d/docker.lst` and the docker version I get is `17.10-ce` because `docker.lst` is set to `edge` releases.

Shouldn't `install_method: package` also imply "add the repo"? I can add the repo manually of course, but this behaviour is a bit tricky.

Am I missing something?

**Comment by chasebolt** [comment]
you need use this cookbook to install the apt repo
https://github.com/chef-cookbooks/chef-apt-docker

**Comment by atmosx** [comment]
Thanks
