### ISSUE TITLE
CLI arguments to dockerd need to be quoted

### ISSUE THREAD

**Issue by gavacho** [chef-cookbooks/docker#936]
### Cookbook version
2.15.29

### Chef-client version
n/a

### Platform Details
n/a

### Scenario:

I want to provide a log-opt to dockerd whose value contains a space character. If I were doing this from the CLI, I would do something like `--log-opt "tag=my value with space"`. 

### Steps to Reproduce:

Have a section like:

```
 docker_service 'default' do
    systemd_opts ['MountFlags=slave']
    version node['redacted']['docker']['version']
    install_method 'package'
    package_name node['redacted']['docker']['package_name']
    log_driver 'syslog'
    log_opts ['tag=my value with spaces', 'other=something']
    action [:create, :start]
  end
```

### Expected Result:

In the systemd config file, I expect to see:

```
ExecStart=/usr/bin/dockerd  --group=docker --log-driver=syslog --log-opt "tag=my value with spaces" --log-opt "other=something" --pidfile=/var/run/docker.pid
```

### Actual Result:

My log_opt value is not correctly quoted resulting in my ExecStart command being invalid.

```
ExecStart=/usr/bin/dockerd  --group=docker --log-driver=syslog --log-opt tag=my value with spaces --log-opt other=something --pidfile=/var/run/docker.pid
```

I can work around this by quoting the `log_opts` strings myself like:

```
 docker_service 'default' do
    ...
    log_opts ['"tag=my value with spaces"', '"other=something"']
  end
```

But this feels like a leaky abstraction because the only way I know to quote those values is to know that this cookbook is going to (1) put them on the CLI and (2) assume that the values don't contain spaces.

I'm sorry if I've used unclear terminology, I'm very new to chef

**Comment by chasebolt** [comment]
thanks for letting us know! this has been fixed in `v2.16.4`
