### ISSUE TITLE
docker_exec fails to run command

### ISSUE THREAD

**Issue by kleiner08** [chef-cookbooks/docker#943]
### Cookbook version
2.17.0

### Chef-client version
13.6.4

### Platform Details
RedHat 3.10.0-693.2.2.el7.x86_64

### Scenario:
I am attempting to run a sed command inside the docker container via docker_exec.  The command run via the command line with 'docker exec' works just fine
`docker exec ui sed -i 's,http.*8080,,'   /path/file.txt`
but when it is run via the docker_exec resource it doesn't do anything even though it states that it ran the command
```
docker_exec 'Configure ui' do 
    container 'ui'
    command ["sed -i 's,http.*8080,,' /path/file.txt"]
end
```
I have tried many different ways for the command line:
`command ["sed", "-i", "'s,http.*8080,,'", "/path/file.txt"]`

I also tried the following command and it also logged that it was executed, but file.txt wasn't created:
`command['script /dev/null -c "echo test > file.txt"']`

### Expected Result:
The /path/file.txt should have the substitutions completed.

### Actual Result:
The /path/file.txt remains unchanged

**Comment by rendler-denis** [comment]
I am experiencing the same issues on Ubuntu 16.04 with chef-client 13.6.4. The container does not seem to receive the command at all.

**Comment by chasebolt** [comment]
give this a try

```ruby
docker_exec 'Configure ui' do 
    container 'ui'
    command ["sh", "-c", "sed -i 's,http.*8080,,' /path/file.txt"]
end
```

**Comment by kleiner08** [comment]
@chasebolt That did the trick.  Thanks a ton!

**Comment by rendler-denis** [comment]
sorry for taking this long to answer. it worked for me too, but I don't understand why we need the sh? the recipe does not use docker's exec?
