### ISSUE TITLE
docker_container not redeploying newer "latest" tag when  it is updated in image repo

### ISSUE THREAD

**Issue by isuftin** [chef-cookbooks/docker#982]
### Cookbook version
4.0.1

### Chef-client version
12.21.26

### Platform Details
CentOS in AWS

### Scenario:
I need docker_container to recognize that the "latest" tag has been updated via docker_image and redeploy the latest container based on a new IMAGE ID

### Steps to Reproduce:
Pull "latest" image from local or remote resource using docker_image resource. Update the "latest" image in that resource with a new build. Rerun docker_image and docker_container

### Expected Result:
- docker_image resource pulls newer tag for "latest" (working)
- docker_container resource redeploys newest tag as container on next chef-client run (not werking)

### Actual Result:
When a newer tag for "latest" shows up, docker_container does not recognize that "latest" has been updated and does not redeploy

**Comment by chasebolt** [comment]
you need to place a notify `:redeploy` on the docker_image resource

**Comment by isuftin** [comment]
@chasebolt So I have a wrapper cookbook. I have two recipes. 

my_cookbook.docker_image:
```
#
# Cookbook Name:: owi_docker
# Recipe:: docker_image

return unless node[:owi_docker].attribute?(:image)

node['owi_docker']['image'].each do |image_name, image_properties|
  actions = %i[pull]

  if image_properties.key?('actions')
    actions = [image_properties['actions'].map(&:to_sym)]
  end

  docker_image image_name do
    destination image_properties['destination'] unless image_properties['destination'].nil?
...
    tag image_properties['tag'] unless image_properties['tag'].nil?

    action actions
  end
end

```

my_cookbook.docker_container:
```
return unless node[:owi_docker].attribute?(:container)

node['owi_docker']['container'].each do |container_name, container_properties|
  actions = %i[run]

  if container_properties.key?('actions')
    actions = [container_properties['actions'].map(&:to_sym)]
  end

  docker_container container_name do
    attach_stderr container_properties['attach_stderr'] unless container_properties['attach_stderr'].nil?
    
...

    working_dir container_properties['working_dir'] unless container_properties['working_dir'].nil?

    action actions

    subscribes :pull, "docker_docker_image[#{docker_image}]", :immediately
  end
end

```

And during a run, what the error I see is:
```
       NoMethodError
       -------------
       undefined method `docker_image' for DockerCookbook::DockerContainer
```

I wonder how to properly call out a subscribes (or notifies) from one recipe for a resource not called out directly in the recipe

**Comment by chasebolt** [comment]
why is your subscribes on docker_docker_image and not just docker_image?
typo?

**Comment by isuftin** [comment]
@chasebolt Was trying to work through an error. In the end it does look like this...

`subscribes :redeploy, "docker_image[#{container_name}]", :immediately`

And this seems to work the way I want. 

Thank you for your help.
