### ISSUE TITLE
zesty? helper method missing from docker_installation_package

### ISSUE THREAD

**Issue by akkinenivijay** [chef-cookbooks/docker#988]
### Cookbook version
4.1.1

### Chef-client version
12.22.1

### Platform Details
centos-7.4

### Scenario:
Install docker via docker_service. 
docker_service 'default' do
  install_method 'package'
  package_name 'docker-engine'
  version "#{docker_version}"
  storage_driver 'overlay'
  action [:create, :start]
end

### Actual Result:
NoMethodError
           -------------
           docker_installation_package[default] (/tmp/kitchen/cache/cookbooks/docker/libraries/docker_service.rb line 61) had an error: NoMethodError: undefined method `zesty?' for DockerCookbook::DockerInstallationPackage

           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/docker/libraries/docker_installation_package.rb:134:in `version_string'
           /tmp/kitchen/cache/cookbooks/docker/libraries/docker_installation_package.rb:11:in `block in <class:DockerInstallationPackage>'
           /tmp/kitchen/cache/cookbooks/docker/libraries/docker_installation_package.rb:43:in `block (2 levels) in <class:DockerInstallationPackage>'
           /tmp/kitchen/cache/cookbooks/docker/libraries/docker_installation_package.rb:42:in `block in <class:DockerInstallationPackage>'

**Comment by tas50** [comment]
Fixed on master. I'll try to get this pushed to Supermarket today. Thanks for the report.
