### ISSUE TITLE
Version 4.1.1 on supermarket is not 4.1.1 in this repository. bad deploy?

### ISSUE THREAD

**Issue by potato20** [chef-cookbooks/docker#991]
first of all thank you for fixing chef 14 bugs quickly, but the version 4.1.1 of this cookbook on supermarket doesn't have the changes that were made 12 hours ago. must have been a bad deploy?

**Comment by oleg-filiutsich** [comment]
Please release new version

**Comment by tas50** [comment]
The version stays the same in github until we push up to Supermarket. I've pushed the 4.2.0 release now to Supermarket.
